### PR TITLE
Update to reference only the container_name field

### PR DESCRIPTION
**Pull request by portante**
We no longer need to reference the `.raw` subfield since the mapping for the `container_name` now uses `not_analyzed`.

### CODE REVIEW

**Comment by nhosoi** [comment]
Still failing?
```
FAILURE after 0.505s: test/zzz-correct-index-names.sh:31: executing 'curl_es logging-es-data-master-xa6wxvm8-1-kx8nq /project.*/_count -X POST -d '{"query":{"term":{"kubernetes.namespace_name":"openshift"}}}' | get_count_from_json' expecting success and text '^0$': the output content test failed
Standard output from the command:
5
```

**Comment by richm** [comment]
/test json-file
curator flake

**Pull request merged**
