### PR TITLE
fix smoke test to use 5.1

### PR DESCRIPTION
**Pull request by jcantrill**
### Description
This PR fixes the smoke test to use CLO, EO from 5.1

cc @ewolinetz @vimalk78

### CODE REVIEW

**Comment by ewolinetz** [comment]
/hold
@jcantrill can you also fix the following in `hack/deploy-logging` ?
`export IMAGE_ELASTICSEARCH_OPERATOR_REGISTRY=${IMAGE_ELASTICSEARCH_OPERATOR_REGISTRY:-registry.svc.ci.openshift.org` ?

**Review by vimalk78 — APPROVED** [review]
/lgtm

**Pull request merged**
