### PR TITLE
Bug 1494912 - metrics indexes should not save the _source

### PR DESCRIPTION
**Pull request by richm**
https://bugzilla.redhat.com/show_bug.cgi?id=1494912
Completely disable the _source and _all for ovirt-metrics-*
/test

### CODE REVIEW

**Comment by richm** [comment]
why do we keep getting this message
```
Submit Queue — Required Github CI test is not green: ci/openshift-jenkins/logging 
```
when
```
ci/openshift-jenkins/logging — Jenkins job succeeded.
```
????? @stevekuznetsov 
/test logging

**Comment by stevekuznetsov** [comment]
@richm unclear why sometimes the munger doesn't pick up the status ... sorry!

**Pull request merged**
