### PR TITLE
fluentd: use fluent-plugin-viaq version 0.0.11

### PR DESCRIPTION
**Pull request by wozniakjan**

### CODE REVIEW

**Comment by richm** [comment]
[test]

**Comment by wozniakjan** [comment]
[(8) [SCCFSI] flow Master events to the log stack[logging][epic-ois-agl-exp]](https://trello.com/c/RXMD3VJZ/496-8-sccfsi-flow-master-events-to-the-log-stackloggingepic-ois-agl-exp)

**Comment by richm** [comment]
[test] flake provisioning aws machine

**Comment by richm** [comment]
[merge]

**Pull request merged**
