### PR TITLE
Add fluentd-plugin-grafana-loki to fluentd image

### PR DESCRIPTION
**Pull request by alanconway**
PR has two commits, the first updates the kafka plugin, which had dependency problems.
The second adds the loki plugin.

/assign jcantril
/cc jcantril

### CODE REVIEW

**Comment by alanconway** [comment]
/hold

I got a ton of warnings and an error from building the image so I've got something wrong. Will investigate but any hints appreciated.


```
STEP 24: RUN cd ${HOME}/vendored_gem_src/ && ./install-gems.sh && cd / && rm -rf ${HOME}/vendored_gem_src/
2.7.6.2
  Successfully built RubyGem
  Name: activemodel
  Version: 5.2.4.3
  File: activemodel-5.2.4.3.gem
  Successfully built RubyGem
  Name: activesupport
  Version: 5.2.4.3
  File: activesupport-5.2.4.3.gem
  Successfully built RubyGem
  Name: addressable
  Version: 2.7.0
  File: addressable-2.7.0.gem
WARNING:  open-ended dependency on gem-release (>= 0, development) is not recommended
  if gem-release is semantically versioned, use:
    add_development_dependency 'gem-release', '~> 0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: aes_key_wrap
  Version: 1.1.0
  File: aes_key_wrap-1.1.0.gem
WARNING:  description and summary are identical
WARNING:  open-ended dependency on rake (>= 0, development) is not recommended
  if rake is semantically versioned, use:
    add_development_dependency 'rake', '~> 0'
WARNING:  open-ended dependency on simplecov (>= 0, development) is not recommended
  if simplecov is semantically versioned, use:
    add_development_dependency 'simplecov', '~> 0'
WARNING:  open-ended dependency on rspec (>= 0, development) is not recommended
  if rspec is semantically versioned, use:
    add_development_dependency 'rspec', '~> 0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: attr_required
  Version: 1.0.1
  File: attr_required-1.0.1.gem
  Successfully built RubyGem
  Name: aws-eventstream
  Version: 1.1.0
  File: aws-eventstream-1.1.0.gem
  Successfully built RubyGem
  Name: aws-partitions
  Version: 1.396.0
  File: aws-partitions-1.396.0.gem
  Successfully built RubyGem
  Name: aws-sdk-cloudwatchlogs
  Version: 1.38.0
  File: aws-sdk-cloudwatchlogs-1.38.0.gem
  Successfully built RubyGem
  Name: aws-sdk-core
  Version: 3.109.3
  File: aws-sdk-core-3.109.3.gem
  Successfully built RubyGem
  Name: aws-sigv4
  Version: 1.2.2
  File: aws-sigv4-1.2.2.gem
WARNING:  open-ended dependency on rake (>= 12.3.3, development) is not recommended
  if rake is semantically versioned, use:
    add_development_dependency 'rake', '~> 12.3', '>= 12.3.3'
WARNING:  open-ended dependency on rake-compiler (>= 0.9, development) is not recommended
  if rake-compiler is semantically versioned, use:
    add_development_dependency 'rake-compiler', '~> 0.9'
WARNING:  open-ended dependency on pry (>= 0, development) is not recommended
  if pry is semantically versioned, use:
    add_development_dependency 'pry', '~> 0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: bigdecimal
  Version: 3.0.0
  File: bigdecimal-3.0.0.gem
WARNING:  open-ended dependency on rake (>= 0, development) is not recommended
  if rake is semantically versioned, use:
    add_development_dependency 'rake', '~> 0'
WARNING:  open-ended dependency on coveralls (>= 0, development) is not recommended
  if coveralls is semantically versioned, use:
    add_development_dependency 'coveralls', '~> 0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: bindata
  Version: 2.4.7
  File: bindata-2.4.7.gem
  Successfully built RubyGem
  Name: concurrent-ruby
  Version: 1.1.8
  File: concurrent-ruby-1.1.8.gem
WARNING:  description and summary are identical
WARNING:  open-ended dependency on bundler (>= 0, development) is not recommended
  if bundler is semantically versioned, use:
    add_development_dependency 'bundler', '~> 0'
WARNING:  open-ended dependency on minitest (>= 5.0.0, development) is not recommended
  if minitest is semantically versioned, use:
    add_development_dependency 'minitest', '~> 5.0', '>= 5.0.0'
WARNING:  open-ended dependency on rake (>= 0, development) is not recommended
  if rake is semantically versioned, use:
    add_development_dependency 'rake', '~> 0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: connection_pool
  Version: 2.2.3
  File: connection_pool-2.2.3.gem
WARNING:  open-ended dependency on rspec (>= 2.13.0, development) is not recommended
  if rspec is semantically versioned, use:
    add_development_dependency 'rspec', '~> 2.13', '>= 2.13.0'
WARNING:  open-ended dependency on rdoc (>= 3.6.0, development) is not recommended
  if rdoc is semantically versioned, use:
    add_development_dependency 'rdoc', '~> 3.6', '>= 3.6.0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: cool.io
  Version: 1.7.1
  File: cool.io-1.7.1.gem
WARNING:  pessimistic dependency on minitest (~> 5.8.0, development) may be overly strict
  if minitest is semantically versioned, use:
    add_development_dependency 'minitest', '~> 5.8', '>= 5.8.0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: dig_rb
  Version: 1.0.1
  File: dig_rb-1.0.1.gem
  Successfully built RubyGem
  Name: digest-crc
  Version: 0.6.3
  File: digest-crc-0.6.3.gem
WARNING:  pessimistic dependency on test-unit (~> 2.5.5, development) may be overly strict
  if test-unit is semantically versioned, use:
    add_development_dependency 'test-unit', '~> 2.5', '>= 2.5.5'
WARNING:  open-ended dependency on bundler (>= 1.2.0, development) is not recommended
  if bundler is semantically versioned, use:
    add_development_dependency 'bundler', '~> 1.2', '>= 1.2.0'
WARNING:  open-ended dependency on rake (>= 0.9.2.2, development) is not recommended
  if rake is semantically versioned, use:
    add_development_dependency 'rake', '~> 0.9', '>= 0.9.2.2'
WARNING:  open-ended dependency on rdoc (>= 2.4.2, development) is not recommended
  if rdoc is semantically versioned, use:
    add_development_dependency 'rdoc', '~> 2.4', '>= 2.4.2'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: domain_name
  Version: 0.5.20190701
  File: domain_name-0.5.20190701.gem
WARNING:  open-ended dependency on bundler (>= 0, development) is not recommended
  if bundler is semantically versioned, use:
    add_development_dependency 'bundler', '~> 0'
WARNING:  open-ended dependency on elasticsearch-extensions (>= 0, development) is not recommended
  if elasticsearch-extensions is semantically versioned, use:
    add_development_dependency 'elasticsearch-extensions', '~> 0'
WARNING:  open-ended dependency on ansi (>= 0, development) is not recommended
  if ansi is semantically versioned, use:
    add_development_dependency 'ansi', '~> 0'
WARNING:  open-ended dependency on shoulda-context (>= 0, development) is not recommended
  if shoulda-context is semantically versioned, use:
    add_development_dependency 'shoulda-context', '~> 0'
WARNING:  open-ended dependency on mocha (>= 0, development) is not recommended
  if mocha is semantically versioned, use:
    add_development_dependency 'mocha', '~> 0'
WARNING:  open-ended dependency on yard (>= 0, development) is not recommended
  if yard is semantically versioned, use:
    add_development_dependency 'yard', '~> 0'
WARNING:  open-ended dependency on pry (>= 0, development) is not recommended
  if pry is semantically versioned, use:
    add_development_dependency 'pry', '~> 0'
WARNING:  open-ended dependency on minitest (>= 0, development) is not recommended
  if minitest is semantically versioned, use:
    add_development_dependency 'minitest', '~> 0'
WARNING:  open-ended dependency on minitest-reporters (>= 0, development) is not recommended
  if minitest-reporters is semantically versioned, use:
    add_development_dependency 'minitest-reporters', '~> 0'
WARNING:  open-ended dependency on ruby-prof (>= 0, development) is not recommended
  if ruby-prof is semantically versioned, use:
    add_development_dependency 'ruby-prof', '~> 0'
WARNING:  open-ended dependency on require-prof (>= 0, development) is not recommended
  if require-prof is semantically versioned, use:
    add_development_dependency 'require-prof', '~> 0'
WARNING:  open-ended dependency on simplecov-rcov (>= 0, development) is not recommended
  if simplecov-rcov is semantically versioned, use:
    add_development_dependency 'simplecov-rcov', '~> 0'
WARNING:  open-ended dependency on cane (>= 0, development) is not recommended
  if cane is semantically versioned, use:
    add_development_dependency 'cane', '~> 0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: elasticsearch
  Version: 7.8.0
  File: elasticsearch-7.8.0.gem
WARNING:  open-ended dependency on multi_json (>= 0) is not recommended
  if multi_json is semantically versioned, use:
    add_runtime_dependency 'multi_json', '~> 0'
WARNING:  open-ended dependency on ansi (>= 0, development) is not recommended
  if ansi is semantically versioned, use:
    add_development_dependency 'ansi', '~> 0'
WARNING:  open-ended dependency on bundler (>= 0, development) is not recommended
  if bundler is semantically versioned, use:
    add_development_dependency 'bundler', '~> 0'
WARNING:  open-ended dependency on elasticsearch (>= 0, development) is not recommended
  if elasticsearch is semantically versioned, use:
    add_development_dependency 'elasticsearch', '~> 0'
WARNING:  open-ended dependency on elasticsearch-extensions (>= 0, development) is not recommended
  if elasticsearch-extensions is semantically versioned, use:
    add_development_dependency 'elasticsearch-extensions', '~> 0'
WARNING:  open-ended dependency on elasticsearch-transport (>= 0, development) is not recommended
  if elasticsearch-transport is semantically versioned, use:
    add_development_dependency 'elasticsearch-transport', '~> 0'
WARNING:  open-ended dependency on minitest (>= 0, development) is not recommended
  if minitest is semantically versioned, use:
    add_development_dependency 'minitest', '~> 0'
WARNING:  open-ended dependency on minitest-reporters (>= 0, development) is not recommended
  if minitest-reporters is semantically versioned, use:
    add_development_dependency 'minitest-reporters', '~> 0'
WARNING:  open-ended dependency on mocha (>= 0, development) is not recommended
  if mocha is semantically versioned, use:
    add_development_dependency 'mocha', '~> 0'
WARNING:  open-ended dependency on pry (>= 0, development) is not recommended
  if pry is semantically versioned, use:
    add_development_dependency 'pry', '~> 0'
WARNING:  open-ended dependency on shoulda-context (>= 0, development) is not recommended
  if shoulda-context is semantically versioned, use:
    add_development_dependency 'shoulda-context', '~> 0'
WARNING:  open-ended dependency on yard (>= 0, development) is not recommended
  if yard is semantically versioned, use:
    add_development_dependency 'yard', '~> 0'
WARNING:  open-ended dependency on jsonify (>= 0, development) is not recommended
  if jsonify is semantically versioned, use:
    add_development_dependency 'jsonify', '~> 0'
WARNING:  open-ended dependency on hashie (>= 0, development) is not recommended
  if hashie is semantically versioned, use:
    add_development_dependency 'hashie', '~> 0'
WARNING:  open-ended dependency on cane (>= 0, development) is not recommended
  if cane is semantically versioned, use:
    add_development_dependency 'cane', '~> 0'
WARNING:  open-ended dependency on escape_utils (>= 0, development) is not recommended
  if escape_utils is semantically versioned, use:
    add_development_dependency 'escape_utils', '~> 0'
WARNING:  open-ended dependency on jbuilder (>= 0, development) is not recommended
  if jbuilder is semantically versioned, use:
    add_development_dependency 'jbuilder', '~> 0'
WARNING:  open-ended dependency on require-prof (>= 0, development) is not recommended
  if require-prof is semantically versioned, use:
    add_development_dependency 'require-prof', '~> 0'
WARNING:  open-ended dependency on simplecov-rcov (>= 0, development) is not recommended
  if simplecov-rcov is semantically versioned, use:
    add_development_dependency 'simplecov-rcov', '~> 0'
WARNING:  open-ended dependency on ruby-prof (>= 0, development) is not recommended
  if ruby-prof is semantically versioned, use:
    add_development_dependency 'ruby-prof', '~> 0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: elasticsearch-api
  Version: 7.8.0
  File: elasticsearch-api-7.8.0.gem
WARNING:  open-ended dependency on multi_json (>= 0) is not recommended
  if multi_json is semantically versioned, use:
    add_runtime_dependency 'multi_json', '~> 0'
WARNING:  open-ended dependency on cane (>= 0, development) is not recommended
  if cane is semantically versioned, use:
    add_development_dependency 'cane', '~> 0'
WARNING:  open-ended dependency on curb (>= 0, development) is not recommended
  if curb is semantically versioned, use:
    add_development_dependency 'curb', '~> 0'
WARNING:  open-ended dependency on elasticsearch-extensions (>= 0, development) is not recommended
  if elasticsearch-extensions is semantically versioned, use:
    add_development_dependency 'elasticsearch-extensions', '~> 0'
WARNING:  open-ended dependency on minitest (>= 0, development) is not recommended
  if minitest is semantically versioned, use:
    add_development_dependency 'minitest', '~> 0'
WARNING:  open-ended dependency on minitest-reporters (>= 0, development) is not recommended
  if minitest-reporters is semantically versioned, use:
    add_development_dependency 'minitest-reporters', '~> 0'
WARNING:  open-ended dependency on require-prof (>= 0, development) is not recommended
  if require-prof is semantically versioned, use:
    add_development_dependency 'require-prof', '~> 0'
WARNING:  open-ended dependency on ruby-prof (>= 0, development) is not recommended
  if ruby-prof is semantically versioned, use:
    add_development_dependency 'ruby-prof', '~> 0'
WARNING:  open-ended dependency on simplecov-rcov (>= 0, development) is not recommended
  if simplecov-rcov is semantically versioned, use:
    add_development_dependency 'simplecov-rcov', '~> 0'
WARNING:  open-ended dependency on ansi (>= 0, development) is not recommended
  if ansi is semantically versioned, use:
    add_development_dependency 'ansi', '~> 0'
WARNING:  open-ended dependency on hashie (>= 0, development) is not recommended
  if hashie is semantically versioned, use:
    add_development_dependency 'hashie', '~> 0'
WARNING:  open-ended dependency on httpclient (>= 0, development) is not recommended
  if httpclient is semantically versioned, use:
    add_development_dependency 'httpclient', '~> 0'
WARNING:  open-ended dependency on mocha (>= 0, development) is not recommended
  if mocha is semantically versioned, use:
    add_development_dependency 'mocha', '~> 0'
WARNING:  open-ended dependency on net-http-persistent (>= 0, development) is not recommended
  if net-http-persistent is semantically versioned, use:
    add_development_dependency 'net-http-persistent', '~> 0'
WARNING:  open-ended dependency on patron (>= 0, development) is not recommended
  if patron is semantically versioned, use:
    add_development_dependency 'patron', '~> 0'
WARNING:  open-ended dependency on pry (>= 0, development) is not recommended
  if pry is semantically versioned, use:
    add_development_dependency 'pry', '~> 0'
WARNING:  open-ended dependency on shoulda-context (>= 0, development) is not recommended
  if shoulda-context is semantically versioned, use:
    add_development_dependency 'shoulda-context', '~> 0'
WARNING:  open-ended dependency on yard (>= 0, development) is not recommended
  if yard is semantically versioned, use:
    add_development_dependency 'yard', '~> 0'
WARNING:  open-ended dependency on bundler (>= 0, development) is not recommended
  if bundler is semantically versioned, use:
    add_development_dependency 'bundler', '~> 0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: elasticsearch-transport
  Version: 7.8.0
  File: elasticsearch-transport-7.8.0.gem
WARNING:  open-ended dependency on ffi (>= 1.3.0) is not recommended
  if ffi is semantically versioned, use:
    add_runtime_dependency 'ffi', '~> 1.3', '>= 1.3.0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: ethon
  Version: 0.12.0
  File: ethon-0.12.0.gem
WARNING:  open-ended dependency on rspec (>= 3.5.0, development) is not recommended
  if rspec is semantically versioned, use:
    add_development_dependency 'rspec', '~> 3.5', '>= 3.5.0'
WARNING:  open-ended dependency on activesupport (>= 0, development) is not recommended
  if activesupport is semantically versioned, use:
    add_development_dependency 'activesupport', '~> 0'
WARNING:  open-ended dependency on delorean (>= 0, development) is not recommended
  if delorean is semantically versioned, use:
    add_development_dependency 'delorean', '~> 0'
WARNING:  open-ended dependency on eventmachine (>= 1.0.4, development) is not recommended
  if eventmachine is semantically versioned, use:
    add_development_dependency 'eventmachine', '~> 1.0', '>= 1.0.4'
WARNING:  open-ended dependency on open4 (>= 0, development) is not recommended
  if open4 is semantically versioned, use:
    add_development_dependency 'open4', '~> 0'
WARNING:  open-ended dependency on rake (>= 0, development) is not recommended
  if rake is semantically versioned, use:
    add_development_dependency 'rake', '~> 0'
WARNING:  open-ended dependency on rdoc (>= 0, development) is not recommended
  if rdoc is semantically versioned, use:
    add_development_dependency 'rdoc', '~> 0'
WARNING:  open-ended dependency on shindo (>= 0, development) is not recommended
  if shindo is semantically versioned, use:
    add_development_dependency 'shindo', '~> 0'
WARNING:  open-ended dependency on sinatra (>= 0, development) is not recommended
  if sinatra is semantically versioned, use:
    add_development_dependency 'sinatra', '~> 0'
WARNING:  open-ended dependency on sinatra-contrib (>= 0, development) is not recommended
  if sinatra-contrib is semantically versioned, use:
    add_development_dependency 'sinatra-contrib', '~> 0'
WARNING:  open-ended dependency on json (>= 1.8.5, development) is not recommended
  if json is semantically versioned, use:
    add_development_dependency 'json', '~> 1.8', '>= 1.8.5'
WARNING:  open-ended dependency on puma (>= 0, development) is not recommended
  if puma is semantically versioned, use:
    add_development_dependency 'puma', '~> 0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: excon
  Version: 0.75.0
  File: excon-0.75.0.gem
  Successfully built RubyGem
  Name: faraday
  Version: 1.0.1
  File: faraday-1.0.1.gem
patching file ext/ffi_c/Call.c
patching file ext/ffi_c/Call.h
patching file ext/ffi_c/Closure.c
patching file ext/ffi_c/Closure.h (renamed from ext/ffi_c/ClosurePool.h)
patching file ext/ffi_c/ClosurePool.c
patching file ext/ffi_c/Function.c
patching file ext/ffi_c/Function.h
patching file ext/ffi_c/FunctionInfo.c
patching file ext/ffi_c/MethodHandle.c
patching file ext/ffi_c/ffi.c
patching file ffi.gemspec
+ sed -e s@ext/ffi_c/ClosurePool.c@ext/ffi_c/Closure.c@ -e s@ext/ffi_c/ClosurePool.h@ext/ffi_c/Closure.h@ -i ffi.gemspec
WARNING:  pessimistic dependency on rspec (~> 2.14.1, development) may be overly strict
  if rspec is semantically versioned, use:
    add_development_dependency 'rspec', '~> 2.14', '>= 2.14.1'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: ffi
  Version: 1.11.3
  File: ffi-1.11.3.gem
+ sed -e '/^[ 	][ 	]*s[.]cert_chain[ 	=]/d' -e '/^[     ][      ]*s[.]signing_key[       =]/d' -i ffi-compiler.gemspec
WARNING:  license value 'Apache 2.0' is invalid.  Use a license identifier from
http://spdx.org/licenses or 'Nonstandard' for a nonstandard license.
Did you mean 'Apache-2.0'?
WARNING:  open-ended dependency on rake (>= 0) is not recommended
  if rake is semantically versioned, use:
    add_runtime_dependency 'rake', '~> 0'
WARNING:  open-ended dependency on ffi (>= 1.0.0) is not recommended
  if ffi is semantically versioned, use:
    add_runtime_dependency 'ffi', '~> 1.0', '>= 1.0.0'
WARNING:  open-ended dependency on rspec (>= 0, development) is not recommended
  if rspec is semantically versioned, use:
    add_development_dependency 'rspec', '~> 0'
WARNING:  open-ended dependency on rubygems-tasks (>= 0, development) is not recommended
  if rubygems-tasks is semantically versioned, use:
    add_development_dependency 'rubygems-tasks', '~> 0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: ffi-compiler
  Version: 1.0.1
  File: ffi-compiler-1.0.1.gem
directory ffi-compiler.gemspec.patch.sh has no gemspec - assuming not a gem dir - skipping
directory ffi.gemspec.patch.sh has no gemspec - assuming not a gem dir - skipping
directory ffi.gemspec0001.patch has no gemspec - assuming not a gem dir - skipping
directory ffi.source0001.patch has no gemspec - assuming not a gem dir - skipping
WARNING:  licenses is empty, but is recommended.  Use a license identifier from
http://spdx.org/licenses or 'Nonstandard' for a nonstandard license.
WARNING:  open-ended dependency on appraisal (>= 0, development) is not recommended
  if appraisal is semantically versioned, use:
    add_development_dependency 'appraisal', '~> 0'
WARNING:  open-ended dependency on rake (> 10.0, development) is not recommended
  if rake is semantically versioned, use:
    add_development_dependency 'rake', '~> 10.0', '> 10.0'
WARNING:  open-ended dependency on test-unit (> 3, development) is not recommended
  if test-unit is semantically versioned, use:
    add_development_dependency 'test-unit', '~> 3', '> 3'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: fluent-config-regexp-type
  Version: 1.0.0
  File: fluent-config-regexp-type-1.0.0.gem
WARNING:  open-ended dependency on fluentd (>= 0) is not recommended
  if fluentd is semantically versioned, use:
    add_runtime_dependency 'fluentd', '~> 0'
WARNING:  open-ended dependency on uuidtools (>= 2.1.5) is not recommended
  if uuidtools is semantically versioned, use:
    add_runtime_dependency 'uuidtools', '~> 2.1', '>= 2.1.5'
WARNING:  open-ended dependency on rake (>= 0, development) is not recommended
  if rake is semantically versioned, use:
    add_development_dependency 'rake', '~> 0'
WARNING:  open-ended dependency on test-unit (>= 0, development) is not recommended
  if test-unit is semantically versioned, use:
    add_development_dependency 'test-unit', '~> 0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: fluent-mixin-config-placeholders
  Version: 0.4.0
  File: fluent-mixin-config-placeholders-0.4.0.gem
WARNING:  open-ended dependency on fluentd (>= 0.14.15) is not recommended
  if fluentd is semantically versioned, use:
    add_runtime_dependency 'fluentd', '~> 0.14', '>= 0.14.15'
WARNING:  open-ended dependency on bundler (>= 0, development) is not recommended
  if bundler is semantically versioned, use:
    add_development_dependency 'bundler', '~> 0'
WARNING:  open-ended dependency on rake (>= 0, development) is not recommended
  if rake is semantically versioned, use:
    add_development_dependency 'rake', '~> 0'
WARNING:  open-ended dependency on test-unit (>= 0, development) is not recommended
  if test-unit is semantically versioned, use:
    add_development_dependency 'test-unit', '~> 0'
WARNING:  open-ended dependency on test-unit-rr (>= 0, development) is not recommended
  if test-unit-rr is semantically versioned, use:
    add_development_dependency 'test-unit-rr', '~> 0'
WARNING:  open-ended dependency on mocha (>= 0, development) is not recommended
  if mocha is semantically versioned, use:
    add_development_dependency 'mocha', '~> 0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: fluent-plugin-cloudwatch-logs
  Version: 0.7.6
  File: fluent-plugin-cloudwatch-logs-0.7.6.gem
WARNING:  description and summary are identical
WARNING:  open-ended dependency on bundler (>= 0, development) is not recommended
  if bundler is semantically versioned, use:
    add_development_dependency 'bundler', '~> 0'
WARNING:  open-ended dependency on test-unit (>= 3.1.0, development) is not recommended
  if test-unit is semantically versioned, use:
    add_development_dependency 'test-unit', '~> 3.1', '>= 3.1.0'
WARNING:  open-ended dependency on test-unit-rr (>= 0, development) is not recommended
  if test-unit-rr is semantically versioned, use:
    add_development_dependency 'test-unit-rr', '~> 0'
WARNING:  open-ended dependency on appraisal (>= 0, development) is not recommended
  if appraisal is semantically versioned, use:
    add_development_dependency 'appraisal', '~> 0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: fluent-plugin-concat
  Version: 2.4.0
  File: fluent-plugin-concat-2.4.0.gem
WARNING:  description and summary are identical
WARNING:  open-ended dependency on fluentd (>= 0.14.22) is not recommended
  if fluentd is semantically versioned, use:
    add_runtime_dependency 'fluentd', '~> 0.14', '>= 0.14.22'
WARNING:  open-ended dependency on excon (>= 0) is not recommended
  if excon is semantically versioned, use:
    add_runtime_dependency 'excon', '~> 0'
WARNING:  open-ended dependency on elasticsearch (>= 0) is not recommended
  if elasticsearch is semantically versioned, use:
    add_runtime_dependency 'elasticsearch', '~> 0'
WARNING:  open-ended dependency on rake (>= 0, development) is not recommended
  if rake is semantically versioned, use:
    add_development_dependency 'rake', '~> 0'
WARNING:  pessimistic dependency on test-unit (~> 3.3.0, development) may be overly strict
  if test-unit is semantically versioned, use:
    add_development_dependency 'test-unit', '~> 3.3', '>= 3.3.0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: fluent-plugin-elasticsearch
  Version: 4.1.1
  File: fluent-plugin-elasticsearch-4.1.1.gem
WARNING:  description and summary are identical
WARNING:  open-ended dependency on bundler (>= 0, development) is not recommended
  if bundler is semantically versioned, use:
    add_development_dependency 'bundler', '~> 0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: fluent-plugin-grafana-loki
  Version: 1.2.7
  File: fluent-plugin-grafana-loki-1.2.7.gem
patching file lib/fluent/plugin/kafka_plugin_util.rb
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file lib/fluent/plugin/kafka_plugin_util.rb.rej
Error: error building at STEP "RUN cd ${HOME}/vendored_gem_src/ && ./install-gems.sh && cd / && rm -rf ${HOME}/vendored_gem_src/": error while running runtime: exit status 1
make: *** [Makefile:19: build-fluentd-image] Error 125
```

**Comment by alanconway** [comment]
update script runs smootly
make suceeds
only one unexpected diff in oj.gemspec - looks harmless.
@jcantrill can I get an LGTM?

**Review by jcantrill — COMMENTED** [review]
/lgtm

**Pull request merged**
