### PR TITLE
fixes for ansible based deployment

### PR DESCRIPTION
**Pull request by richm**
These are some fixes for the ansible based deployment, for testing,
and to help debug curator issues

### CODE REVIEW

**Comment by richm** [comment]
@jcantrill @ewolinetz these follow on to pr/328 so that we can test ansible based deployments in the CI

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
@ewolinetz @jcantrill This should pass once https://github.com/openshift/openshift-ansible/pull/3526 is merged.  These also depend on https://github.com/openshift/origin-aggregated-logging/pull/328.  What do you guys want to do?  merge pr/328 first, then this?  Or should I just include the changes in 328 in this pr?  Should I squash all of the commits or leave them separate?

**Comment by jcantrill** [comment]
@richm I think we should move to ansible based deployment as soon as possible as that is what we will be using going forward and it seems to be stable.  In regards to squashing, I intended to squash and think it makes the most sense; there doesnt seem any value in my mind in keeping any of the individual commits.  I am fine closing #328 given you have a working PR that incorporates it.

**Comment by richm** [comment]
[test]

**Comment by jcantrill** [comment]
[merge]

**Pull request merged**
