### PR TITLE
add rsyslog_exporter for prometheus

### PR DESCRIPTION
**Pull request by richm**
https://jira.coreos.com/browse/LOG-9

This adds the source for the soundcloud rsyslog_exporter
to the rsyslog image and builds it in the Dockerfile.
Requires openshift/cluster-logging-operator#164 to configure it.

### CODE REVIEW

**Comment by richm** [comment]
aws flake
/test full-integ-aws

**Comment by richm** [comment]
aws flake
/test full-integ-aws

**Comment by nhosoi** [comment]
Currently, zzz-rsyslog.sh is failing since rsyslog pod fails to start (or times out).  The CLO log shows this error [1] once (this is _not_ an error but just checking if the secret exists or not; if it does not, it generates it) followed by the repeated "Updating status" messages [2] for 10 minutes, then the zzz-rsyslog.sh test times out.  This symptom is observed in 2 OAL pr's (another failed pr: https://github.com/openshift/origin-aggregated-logging/pull/1649), which does not look introduced by them...

[1] time="2019-05-24T21:18:17Z" level=error msg="Unable to read file to get contents: open /tmp/_working_dir/kibana-proxy-oauth.secret: no such file or directory"

[2]
time="2019-05-24T21:18:17Z" level=info msg="Updating status of Kibana for \"instance\""
time="2019-05-24T21:18:17Z" level=info msg="Updating status of Curator"
time="2019-05-24T21:18:18Z" level=info msg="Updating status of Rsyslog"

**Comment by richm** [comment]
although https://github.com/openshift/cluster-logging-operator/pull/192 has merged, the image is still not available in ci as registry.svc.ci.openshift.org/origin/4.2:cluster-logging-operator - trying to figure out where the image is

**Comment by richm** [comment]
finally passed!  please review and lgtm

**Pull request merged**
