### PR TITLE
Fix logging to console

### PR DESCRIPTION
**Pull request by josefkarasek**
When LOGGING_FILE_PATH=console, fluentd logs to file `$HOME/console`
instead to stdout/err

fixes https://bugzilla.redhat.com/show_bug.cgi?id=1690232

### CODE REVIEW

**Comment by josefkarasek** [comment]
@richm I was seeing a lot of logs in the console when running with 
http://pastebin.test.redhat.com/740515
```
fluentd --no-supervisor -o /var/log/fluentd/fluentd.log --log-rotate-age 10 --log-rotate-size 1024000 -r /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluent-plugin-elasticsearch-3.3.2/lib/fluent/plugin/elasticsearch_simple_sniffer.rb -q --suppress-config-dump
```

**Comment by josefkarasek** [comment]
Let's wait for the next CI run and check fluentd logs...

**Comment by richm** [comment]
The first fluentd log is this one: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_origin-aggregated-logging/1566/pull-ci-openshift-origin-aggregated-logging-master-full-integ-aws/312/artifacts/full-integ-aws/scripts/check-EFK-running/artifacts/fluentd-hk9gb.fluentd.log

I don't see any info/debug/trace level logs

next one is this: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_origin-aggregated-logging/1566/pull-ci-openshift-origin-aggregated-logging-master-full-integ-aws/312/artifacts/full-integ-aws/scripts/test-json-parsing/artifacts/json-parsing-fluentd-pod.log

I don't see any info/debug/trace level logs, but I do see a lot of these:
```
2019-03-21 17:09:50 +0000 [warn]: [systemd-input] event loop does NOT exit until hard timeout.
2019-03-21 17:09:50 +0000 [error]: [systemd-input] Exception emitting record: undefined method `emit' for nil:NilClass
2019-03-21 17:09:50 +0000 [error]: [systemd-input] Exception emitting record: undefined method `emit' for nil:NilClass
...
2019-03-21 17:09:51 +0000 [error]: [systemd-input] Exception emitting record: undefined method `emit' for nil:NilClass
2019-03-21 17:09:51 +0000 [warn]: [systemd-input] killing existing thread thread=#<Thread:0x00007f9b37012c80@/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.4.1/lib/fluent/plugin_helper/thread.rb:70 sleep>
2019-03-21 17:09:51 +0000 [warn]: [systemd-input] thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::SystemdInput title=:event_loop thread=#<Thread:0x00007f9b37012c80@/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.4.1/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
```

next one is https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_origin-aggregated-logging/1566/pull-ci-openshift-origin-aggregated-logging-master-full-integ-aws/312/artifacts/full-integ-aws/scripts/test-read-throttling/artifacts/fluentd-fdb98.log

I don't see any info/debug/trace level logs

etc.

So I'm not sure where the log level was being reset

**Comment by richm** [comment]
@jcantrill can we remove the hold on this one?

**Comment by jcantrill** [comment]
> @jcantrill can we remove the hold on this one?

Yes if you are satisfied with it resolves the issue in question.

**Pull request merged**
