### PR TITLE
Update container registry to registry.ci.openshift.org

### PR DESCRIPTION
**Pull request by jcantrill**
### Description
This PR updates the container registry per dev email regarding the decommissioning of the other registry

cc @ewolinetz @vimalk78

### CODE REVIEW

**Review by igor-karpukhin — APPROVED** [review]
/lgtm

**Comment by jcantrill** [comment]
/override ci/prow/cluster-logging-operator-e2e

All tests passing except event router which is unrelated to this change

**Comment by jcantrill** [comment]
/hold

hoping https://github.com/openshift/cluster-logging-operator/pull/899 will push the right CLO image to be used by this test

**Comment by jcantrill** [comment]
/override ci/prow/cluster-logging-operator-e2e

This tests is broken on CLO eventrouter change that has is awaiting the eventrouter that is needed from this PR.  All other tests pass consistently aside from the normal flakes

**Pull request merged**
