### PR TITLE
kibana_proxy: point submodule to post OOM fix

### PR DESCRIPTION
**Pull request by wozniakjan**
Update kibana_proxy submodule to point to commit after OOM fix

### CODE REVIEW

**Comment by jcantrill** [comment]
We will have to wait on this one until #527 merges

**Comment by jcantrill** [comment]
@wozniakjan Please fix the conflict and we will merge

**Comment by wozniakjan** [comment]
@jcantrill  rebased on top of master and pointing to the latest commit in kibana-proxy repo

**Comment by jcantrill** [comment]
[merge][severity:blocker]

**Pull request merged**
