### PR TITLE
use common submodule

### PR DESCRIPTION
**Pull request by sosiouxme**
The common submodule includes openshift-auth-proxy for the convenience of tagging and releasing from a single repo.
    
It also contains genericized elasticsearch and curator definitions which will replace the specialized ones in the near future.
    
It also includes test and deployer/validation utilities which should be used in the deployer eventually (which is why the submodule is placed under the deployer).

### CODE REVIEW

**Comment by sosiouxme** [comment]
[test]

**Comment by sosiouxme** [comment]
[test]

**Comment by sosiouxme** [comment]
[test]

**Comment by sosiouxme** [comment]
Tests should pass once https://bugzilla.redhat.com/show_bug.cgi?id=1337083 is resolved.

@ewolinetz @richm PTAL

**Comment by ewolinetz** [comment]
awesome! LGTM

**Comment by sosiouxme** [comment]
[merge]

**Comment by sosiouxme** [comment]
apparently i don't have merge. [test] then

**Pull request merged**
