### PR TITLE
LOG-867: Creating es rh-manifest.txt file and script to recreate it

### PR DESCRIPTION
**Pull request by ewolinetz**
Leverages JBoss's 'tattletale' jar to crawl the classpath and discover archives used.

/cc @jcantrill

### CODE REVIEW

**Review by jcantrill — COMMENTED** [review]
/approve

**Comment by ewolinetz** [comment]
@jcantrill mind giving it a `lgtm` if it does? it already had an approve from me :)

**Review by jcantrill — COMMENTED** [review]
/lgtm

**Comment by ewolinetz** [comment]
/hold
due to smoke tests

**Pull request merged**
