### PR TITLE
issue-169 fluentd cannot process datetimes in the future in /var/log/…

### PR DESCRIPTION
**Pull request by richm**
…messages

https://github.com/openshift/origin-aggregated-logging/issues/169
If the log file is not of the form /var/log/messages-YYYYMMDD then just
assume the future date is the current year.

### CODE REVIEW

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
@ewolinetz @sosiouxme PTAL

**Comment by ewolinetz** [comment]
can we update this PR to do the volume mount to set Fluentd's tz to match the tz of the node?

**Comment by richm** [comment]
@ewolinetz I think we need both the bind mount and the fluentd fix, just to be safe

**Comment by ewolinetz** [comment]
lgtm

**Comment by richm** [comment]
[merge]

**Comment by richm** [comment]
retest

**Comment by richm** [comment]
recheck

**Comment by richm** [comment]
@travis-ci recheck

**Pull request merged**
