### PR TITLE
Dockerfile: remove python-setuptools

### PR DESCRIPTION
**Pull request by sosiouxme**
This package from base RHEL causes problems with container grading downstream; easiest to fix here by simply removing it.

### CODE REVIEW

**Comment by jcantrill** [comment]
@sosiouxme cherrypick to 3.11? and master?

**Comment by sosiouxme** [comment]
@jcantrill no need there. might need it in 3.9 at some point (feel free to cp it there). right now it's complaining about the pkg but not lowering the grade.

**Comment by sosiouxme** [comment]
nevermind; this got solved in a better place.

**Pull request closed without merging**
