### PR TITLE
[WIP] Bug 1823305: updating kibana plugin to use sign_off endpoint for oauth proxy

### PR DESCRIPTION
**Pull request by ewolinetz**
Part of fix to address https://bugzilla.redhat.com/show_bug.cgi?id=1823305

### CODE REVIEW

**Comment by ewolinetz** [comment]
Works with https://github.com/openshift/oauth-proxy/pull/176

**Comment by ewolinetz** [comment]
is there a way we can bypass the need to have a cherry pick for this? this functionality no longer exists for 4.5 so there would be nothing to cherrypick...

**Comment by jcantrill** [comment]
@ewolinetz this may be a duplicate to https://github.com/openshift/origin-aggregated-logging/pull/1894

**Comment by jcantrill** [comment]
Closing in favor of https://github.com/openshift/origin-aggregated-logging/pull/1894

**Pull request closed without merging**
