### PR TITLE
fix fluent unit test image

### PR DESCRIPTION
**Pull request by jcantrill**
This PR fixes the unit test image that runs fluent unit tests

### CODE REVIEW

**Comment by jcantrill** [comment]
cc @periklis 

Blocking https://github.com/openshift/origin-aggregated-logging/pull/2010

**Comment by ewolinetz** [comment]
that smoke test failed due to a panic...
```
 F1021 19:00:07.331134    1952 helpers.go:115] The connection to the server api.ci-op-dc1ql0pi-61ec3.origin-ci-int-aws.dev.rhcloud.com:6443 was refused - did you specify the right host or port?
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc00092b301, 0xc001336a20, 0xc1, 0x112)
	/go/src/github.com/openshift/oc/vendor/k8s.io/klog/v2/klog.go:996 +0xb8
k8s.io/klog/v2.(*loggingT).output(0x521c060, 0xc000000003, 0x0, 0x0, 0xc000531490, 0x4d9c898, 0xa, 0x73, 0x41c400)
	/go/src/github.com/openshift/oc/vendor/k8s.io/klog/v2/klog.go:945 +0x19d
k8s.io/klog/v2.(*loggingT).printDepth(0x521c060, 0x3, 0x0, 0x0, 0x2, 0xc001743998, 0x1, 0x1)
	/go/src/github.com/openshift/oc/vendor/k8s.io/klog/v2/klog.go:718 +0x15e
k8s.io/klog/v2.FatalDepth(...)
	/go/src/github.com/openshift/oc/vendor/k8s.io/klog/v2/klog.go:1449
k8s.io/kubectl/pkg/cmd/util.fatal(0xc00136ab40, 0x92, 0x1)
	/go/src/github.com/openshift/oc/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:93 +0x1e8
k8s.io/kubectl/pkg/cmd/util.checkErr(0x35176a0, 0xc001c840f0, 0x30b8bd8)
	/go/src/github.com/openshift/oc/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:188 +0x958
k8s.io/kubectl/pkg/cmd/util.CheckErr(...)
	/go/src/github.com/openshift/oc/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:115
k8s.io/kubectl/pkg/cmd/delete.NewCmdDelete.func1(0xc00073e2c0, 0xc000b2aa80, 0x2, 0x8)
	/go/src/github.com/openshift/oc/vendor/k8s.io/kubectl/pkg/cmd/delete/delete.go:142 +0x18c
github.com/spf13/cobra.(*Command).execute(0xc00073e2c0, 0xc000b2aa00, 0x8, 0x8, 0xc00073e2c0, 0xc000b2aa00)
	/go/src/github.com/openshift/oc/vendor/github.com/spf13/cobra/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xc000bfc000, 0x2, 0xc000bfc000, 0x2)
	/go/src/github.com/openshift/oc/vendor/github.com/spf13/cobra/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/openshift/oc/vendor/github.com/spf13/cobra/command.go:887
main.main()
	/go/src/github.com/openshift/oc/cmd/oc/oc.go:110 +0x81a
goroutine 6 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x521c060)
	/go/src/github.com/openshift/oc/vendor/k8s.io/klog/v2/klog.go:1131 +0x8b
created by k8s.io/klog/v2.init.0
	/go/src/github.com/openshift/oc/vendor/k8s.io/klog/v2/klog.go:416 +0xd6
goroutine 11 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x521bf80)
	/go/src/github.com/openshift/oc/vendor/k8s.io/klog/klog.go:1010 +0x8b
created by k8s.io/klog.init.0
	/go/src/github.com/openshift/oc/vendor/k8s.io/klog/klog.go:411 +0xd6
goroutine 27 [select]:
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x30b8b00, 0x3515d00, 0xc0014b4570, 0x1, 0xc0000543c0)
	/go/src/github.com/openshift/oc/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x13f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x30b8b00, 0x12a05f200, 0x0, 0xc001497601, 0xc0000543c0)
	/go/src/github.com/openshift/oc/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/src/github.com/openshift/oc/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/apimachinery/pkg/util/wait.Forever(0x30b8b00, 0x12a05f200)
	/go/src/github.com/openshift/oc/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:81 +0x4f
created by k8s.io/component-base/logs.InitLogs
	/go/src/github.com/openshift/oc/vendor/k8s.io/component-base/logs/logs.go:58 +0x8a
goroutine 15 [select]:
io.(*pipe).Read(0xc000c73f80, 0xc000922000, 0x1000, 0x1000, 0x2984a60, 0x1, 0xc000922000)
	/opt/rh/go-toolset-1.14/root/usr/lib/go-toolset-1.14-golang/src/io/pipe.go:57 +0xe7
io.(*PipeReader).Read(0xc001880380, 0xc000922000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/opt/rh/go-toolset-1.14/root/usr/lib/go-toolset-1.14-golang/src/io/pipe.go:134 +0x4c
bufio.(*Scanner).Scan(0xc0008c7d80, 0x0)
	/opt/rh/go-toolset-1.14/root/usr/lib/go-toolset-1.14-golang/src/bufio/scan.go:213 +0xa4
github.com/openshift/oc/pkg/cli/admin/mustgather.newPrefixWriter.func1(0xc0008c7d80, 0x3517720, 0xc000010018, 0x2ed2ff1, 0x17)
	/go/src/github.com/openshift/oc/pkg/cli/admin/mustgather/mustgather.go:424 +0x14d
created by github.com/openshift/oc/pkg/cli/admin/mustgather.newPrefixWriter
	/go/src/github.com/openshift/oc/pkg/cli/admin/mustgather/mustgather.go:423 +0x1c1
[ERROR] jUnit test marker could not be placed, expected suites in flight, got 0 
```

**Review by alanconway — COMMENTED** [review]
/lgtm

**Pull request merged**
