### PR TITLE
Updating kibana build to replace old version of handlebars with 4.7.7

### PR DESCRIPTION
**Pull request by ewolinetz**
### Description
Addresses CVEs found for Kibana6 container -- will link bz to 4.6 cherrypick version

/cc @jcantrill

/cherry-pick release-5.1

### Links
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1883902

### CODE REVIEW

**Comment by jcantrill** [comment]
I'm betting cpaas will not be able to accommodate this change. Can we vendor the new over the old?

**Comment by jcantrill** [comment]
The other option is longer and learn how to build in PNC

**Comment by ewolinetz** [comment]
> I'm betting cpaas will not be able to accommodate this change. Can we vendor the new over the old?

@jcantrill can you expand on this?

**Comment by jcantrill** [comment]
> > I'm betting cpaas will not be able to accommodate this change. Can we vendor the new over the old?
> 
> @jcantrill can you expand on this?

This is attempting to install the dependency using npm which will inherently try to access the web.  CPaaS and brew generally lock down pulling content from external sources so my expectation is this install step will fail.

**Comment by ewolinetz** [comment]
@jcantrill ack, i'll pull it down locally and then vendor it in as well

**Comment by ewolinetz** [comment]
@jcantrill thoughts on this latest approach, will CPaaS and brew work with this?

**Review by jcantrill — COMMENTED** [review]
/lgtm

**Pull request merged**
