### PR TITLE
[release-4.5] Bug 1899419: Add typhoeus for keep-alives in elasticsearch plugin

### PR DESCRIPTION
**Pull request by periklis**
### Description
This PR is a manual backport of #2017 . In addition it includes the smoke tests fixes from #1982 and #2019.

/cc @blockloop 
/assign @ewolinetz 

### Links
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1899419

### CODE REVIEW

**Review by blockloop — APPROVED** [review]
/lgtm

**Comment by sdodson** [comment]
Putting a temporary hold on things to prioritize items that fix test flakes while we're hitting AWS quota limits. I'll clear this later today.
/hold

**Comment by sdodson** [comment]
/hold
Persistent failing CI jobs have prevented this from merging in a timely manner. We'll need to reconsider this next week ideally after we understand what's causing these jobs to fail. Please clear the hold once you've figured out what's up.

**Comment by periklis** [comment]
@markmc Would you mind to add `cherry-pick-approved` here? We had this already but our E2E tests were blocked due to an bug introduced in the upstream `ubi7/rh-ruby25` image (see https://bugzilla.redhat.com/show_bug.cgi?id=1909993). LGTM from the team will follow in a moment. Need to land this fist to unblock further E2E tests on https://github.com/openshift/cluster-logging-operator/pull/805 please.

**Review by igor-karpukhin — APPROVED** [review]
/lgtm

**Pull request merged**
