### PR TITLE
port viaq-data-model test to use hack/lib

### PR DESCRIPTION
**Pull request by richm**
@stevekuznetsov @jcantrill @nhosoi PTAL
[test]

### CODE REVIEW

**Comment by jcantrill** [comment]
[(8) Update tests to use origin/hack libraries[logging][epic-ci][epic-ois-td]](https://trello.com/c/UBias2xZ/525-8-update-tests-to-use-origin-hack-librariesloggingepic-ciepic-ois-td)

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
now we're back to the fluentd performance problem? [test]

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
aws [test] flake

**Comment by richm** [comment]
[merge]

**Pull request merged**
