### PR TITLE
bug 1494612. Orphan records missing namespace_name and/or namespace_id

### PR DESCRIPTION
**Pull request by jcantrill**
bug 1494612. Orphan records missing namespace_name and/or namespace_id

### CODE REVIEW

**Comment by richm** [comment]
fyi, the build pulled in the correct viaq:
```
[openshift/origin-logging-fluentd] Successfully installed fluent-plugin-viaq_data_model-0.0.13
```

**Comment by richm** [comment]
@jcantrill looks like a manual cherrypick for 3.6 is required

**Comment by jcantrill** [comment]
@richm do we care for 3.6 since this is a downstream dockerfile that is only a change in the unused ENV_VAR?

**Comment by richm** [comment]
@jcantrill ah, right - no, no worries

**Pull request merged**
