### PR TITLE
fluentd duplicate entry test - ensure no open deleted files

### PR DESCRIPTION
**Pull request by richm**
has 3 duplicate records
Use loader and verify-loader to look for skips and dups

### CODE REVIEW

**Comment by richm** [comment]
more test flakery
/retest

**Comment by richm** [comment]
more test flakery
/retest

**Comment by ewolinetz** [comment]
@richm I wasn't seeing any duplicates before out of all those records before..

**Comment by richm** [comment]
@ewolinetz please check the final version and lgtm again

**Pull request merged**
