### PR TITLE
Bug 1395170 - Logging upgrade mode: kibana can't present log entries for the older 3.2.0 indices after upgrade

### PR DESCRIPTION
**Pull request by richm**
https://bugzilla.redhat.com/show_bug.cgi?id=1395170
Fix some bugs in the upgrade common data model script.

### CODE REVIEW

**Comment by richm** [comment]
@ewolinetz ptal
[test]

**Comment by ewolinetz** [comment]
LGTM

**Comment by ewolinetz** [comment]
side question - we don't have a CI test for this do we? we attach a PV for the logging-es-ops but not logging-es

**Comment by richm** [comment]
no, we don't have a ci test for this

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
[merge]

**Pull request merged**
