### PR TITLE
Disable curator test

### PR DESCRIPTION
**Pull request by jcantrill**
3.9 cherry pickof #1114

### CODE REVIEW

**Comment by richm** [comment]
do we need to disable curator on 3.9?  the problematic changes are in openshift-ansible 3.9?

**Comment by ewolinetz** [comment]
This only exists on master for now. It is related to https://github.com/openshift/openshift-ansible/pull/7985 which hasn't merged into 3.9 yet.

Also https://github.com/openshift/openshift-ansible/pull/8139 should fix this

**Comment by ewolinetz** [comment]
@richm we will want a cherrypick of 8139, but yes. So long as 7985's cherrypick lands after then we won't see this issue at all.

**Pull request closed without merging**
