### PR TITLE
Add support for close and optimize to curator

### PR DESCRIPTION
**Pull request by portante**

### CODE REVIEW

**Comment by portante** [comment]
We really need this.  We need to give customers a way to optimize their indices to help speed up the loading of them when ES starts, and to close them so that they can keep data around longer without impacting ES itself.

**Comment by richm** [comment]
This is a good start.  We'll also need tests - either add them to hack/testing/test-curator.sh or create a new file

**Comment by jcantrill** [comment]
This is related/partially satisfies: https://trello.com/c/UlmNQ0Av

**Comment by jcantrill** [comment]
[(3) Have curator optimize yesterday's indices [logging][epic-ois-agl-perf]](https://trello.com/c/UlmNQ0Av/381-3-have-curator-optimize-yesterdays-indices-loggingepic-ois-agl-perf)

**Comment by jcantrill** [comment]
We probably should also look at the original work done here: https://github.com/openshift/origin-aggregated-logging/pull/223

**Comment by jcantrill** [comment]
[(3) Have curator optimize yesterday's indices [logging][epic-ois-agl-perf]](https://trello.com/c/UlmNQ0Av/381-3-have-curator-optimize-yesterdays-indices-loggingepic-ois-agl-perf)

**Comment by richm** [comment]
Needs docs too.

**Comment by jcantrill** [comment]
@josefkarasek  Do we need to close this and rework it based on the curator changes you have made?

**Comment by josefkarasek** [comment]
@jcantrill yeah. A change to the config file parser needs to be done.
@portante  have you seen https://github.com/openshift/origin-aggregated-logging/pull/862?

**Comment by portante** [comment]
If somebody else is going to do the work to add close and optimize, you can close this issue.  If you are going to wait for me to do the work, then don't close the issue.

I think at this point you a really creating a yaml spec for how to describe curator operations.  I would work to remove the action "`delete`" as a keyword, and instead have a keyword `action` which takes one of many values (`open`, `close`, `delete`, `optimize`, etc.).

**Comment by josefkarasek** [comment]
@portante do you wanna work on this? If yes, just patch the parser so it recognizes other action keywords.

**Pull request closed without merging**
