### PR TITLE
WIP to test multi-tenant plugin for 6.x

### PR DESCRIPTION
**Pull request by jcantrill**
cc @richm

### CODE REVIEW

**Comment by richm** [comment]
```
+ for es_plugin in '${es_plugins[@]}'
+ '[' -x /usr/share/elasticsearch/bin/elasticsearch-plugin ']'
+ plugincmd=/usr/share/elasticsearch/bin/plugin
+ /usr/share/elasticsearch/bin/plugin install -b https://github.com/jcantrill/openshift-elasticsearch-plugin/releases/download/6.6.2.1-SNAPSHOT/openshift-elasticsearch-plugin-6.6.2.1-SNAPSHOT.zip
ES plugins: https://github.com/jcantrill/openshift-elasticsearch-plugin/releases/download/6.6.2.1-SNAPSHOT/openshift-elasticsearch-plugin-6.6.2.1-SNAPSHOT.zip https://github.com/vvanholl/elasticsearch-prometheus-exporter/releases/download/6.6.2.0/elasticsearch-prometheus-exporter-6.6.2.0.zip
/opt/app-root/src/install.sh: line 16: /usr/share/elasticsearch/bin/plugin: No such file or directory
```
I'm guessing ES6 changed the path and/or name of the plugin command?

**Comment by richm** [comment]
some sort of permissions error: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_origin-aggregated-logging/1574/pull-ci-openshift-origin-aggregated-logging-master-full-integ-aws/353/artifacts/full-integ-aws/pods/openshift-logging_elasticsearch-clientdatamaster-0-1-58965df6df-4h4tj_elasticsearch.log.gz
```
[2019-03-27 15:52:14,673][INFO ][container.run            ] Setting heap dump location /elasticsearch/persistent/heapdump.hprof
[2019-03-27 15:52:14,674][INFO ][container.run            ] Checking if Elasticsearch is ready
[2019-03-27 15:52:14,674][INFO ][container.run            ] ES_JAVA_OPTS: ' -Xms2048m -Xmx2048m -XX:HeapDumpPath=/elasticsearch/persistent/heapdump.hprof -Dsg.display_lic_none=false -Dio.netty.recycler.maxCapacityPerThread=0 -Dio.netty.allocator.type=unpooled'
/usr/share/elasticsearch/bin/elasticsearch-env: line 70: /etc/sysconfig/elasticsearch: Permission denied
```

**Comment by jcantrill** [comment]
Closing as uncertain we will pursue this path

**Pull request closed without merging**
