### PR TITLE
Bug 1510697 - Simplify ES readiness probe

### PR DESCRIPTION
**Pull request by wozniakjan**
https://bugzilla.redhat.com/show_bug.cgi?id=1510697

### CODE REVIEW

**Comment by portante** [comment]
We'll want to verify that this probe always works even when ES is in a "red" state.

**Comment by wozniakjan** [comment]
@portante I did a basic test, deployed a 2 node ES cluster with no replica shards for project indeces and deleted one pod.

cluster status is "red":
```
health status index                                                           pri rep docs.count docs.deleted store.size pri.store.size 
green  open   project.logging.5e1229ae-d99c-11e7-8347-5254004a1511.2017.12.05   1   0          7            0     35.8kb         35.8kb 
red    open   .operations.2017.12.05                                            1   0                                                   
yellow open   .searchguard.logging-es-data-master-ux2jba3z                      1   1          5            0     33.5kb         33.5kb 
green  open   .kibana                                                           1   0          1            0      3.1kb          3.1kb 
red    open   project.logging.165ba370-d9c1-11e7-adcf-5254004a1511.2017.12.05   1   0                                                   
yellow open   .searchguard.logging-es-data-master-7sxfzpu5                      1   1          5            0     33.5kb         33.5kb 
green  open   fluentd                                                           1   0        440            0    369.6kb        369.6kb 
```

and the simplified readiness probe still allows it to run
```
logging  logging-es-data-master-7sxfzpu5-2-zzbwl  2/2    Running  0    1h   10.129.0.156     c2
logging  logging-es-data-master-ux2jba3z-2-p03gh  2/2    Running  0    41m  10.128.1.205     c1
```

Let me know if you'd like me to perform some additional tests

**Comment by richm** [comment]
I don't understand - if the current readiness probe works even when the ES state is red, then what is the actual problem we are trying to solve?

**Comment by portante** [comment]
@wozniakjan, @richm, as we talked earlier, but just to record here, there are a number of reasons Elasticsearch can be in a `red` state where it is not responsive.

One such case is when the PVs have filled 100% and Elasticsearch is unable to record any changes on disk.

**Comment by wozniakjan** [comment]
> One such case is when the PVs have filled 100% and Elasticsearch is unable to record any changes on disk.

@portante I have reproduced this test case using very small 10MB tmpfs disk and our old readiness probe is still responsive (as well as the new one) so I don't think this is the culprit either. If you come up with any other scenario to test, please let me know

```
Filesystem             Size  Used Avail Use% Mounted on
tmpfs                   10M   10M     0 100% /elasticsearch/persistent

NS             NAME                                     READY  STATUS   RST  AGE  IP               NODE
logging        logging-es-data-master-x1tp0qil-2-68l7v  2/2    Running  0    23m  10.129.0.187     c2 

health status index                                                                 pri rep docs.count docs.deleted store.size pri.store.size 
red    open   .operations.2017.12.11                                                  1   0                                                   
green  open   .searchguard.logging-es-data-master-x1tp0qil                            1   0          5            0     33.2kb         33.2kb 
green  open   .kibana                                                                 1   0          1            0        3kb            3kb 
red    open   project.user1-project.393ad9e7-c085-11e7-bdf6-5254004a1511.2017.12.11   1   0                                                   
red    open   project.logging.3189485f-de71-11e7-8893-5254004a1511.2017.12.11         1   0
```

**Comment by portante** [comment]
@wozniakjan, how many ES pods do you have in the ES cluster?  I'd be sure there are three.  And make sure logs are flowing continually so that new indices are attempted to be created during this 100% filled situation for all PVs.

**Pull request merged**
