### PR TITLE
Set ES JVM HEAP Xms equal to Xmx

### LINKED ISSUE #383: Set Xms equal to Xmx at Elasticsearch startup
We should not make it possible to start ES with `Xms < Xmx`. One of the reasons is that we may not be able to fully benefit from **disabled swap** (#206) via mlockall.

### PR DESCRIPTION
**Pull request by lukas-vlcek**
Closes #383

### CODE REVIEW

**Comment by lukas-vlcek** [comment]
//cc @portante

**Comment by lukas-vlcek** [comment]
@jcantrill @ewolinetz Do you think you can point me to the documentation file that should be updated?

**Comment by jcantrill** [comment]
[test]

**Comment by ewolinetz** [comment]
@lukas-vlcek i would update the readme in this repo and also something in the openshift docs, likely in this section https://docs.openshift.org/latest/install_config/aggregate_logging.html#aggregated-elasticsearch

the repo is openshift/openshift-docs

**Comment by jcantrill** [comment]
[merge]

**Pull request merged**
