### PR TITLE
Bug 1860393: LogForwarding GA on 4.5

### PR DESCRIPTION
**Pull request by jcantrill**
This PR brings LogForwarding GA into 4.5

Ref: 
* https://issues.redhat.com/browse/LOG-829
* https://bugzilla.redhat.com/show_bug.cgi?id=1860393

### CODE REVIEW

**Comment by jwforres** [comment]
Before accepting this change into 4.5 the patch manager will need to see clear ack's from docs, QE, and CEE that the feature is ready to be shipped in 4.6. Either list those here or in the 4.6 Jira ticket, and then remove the priority/awaiting-more-evidence label from this PR.

**Comment by crawford** [comment]
I don't see any updates since @jwforres' request, so I'm skipping this again.

**Comment by eparis** [comment]
Skipping until we hear from doc/qe/cee

**Pull request closed without merging**
