### PR TITLE
update instructions for using All-In-One docker container

### PR DESCRIPTION
**Pull request by richm**

### CODE REVIEW

**Comment by jcantrill** [comment]
LGTM

**Comment by jcantrill** [comment]
@richm Can you find the openshift logging docks https://github.com/openshift/openshift-docs and see if there is a place we should be adding a similiar note

**Comment by richm** [comment]
@jcantrill Should we add logging specific instructions to openshift origin docs?

**Comment by jcantrill** [comment]
we already do
https://docs.openshift.org/latest/install_config/aggregate_logging.html
thought i dont know if it is updtodaye

On Mon, Jan 11, 2016 at 11:50 AM, Rich Megginson <notifications@github.com>
wrote:

> @jcantrill <https://github.com/jcantrill> Should we add logging specific
> instructions to openshift origin docs?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin-aggregated-logging/pull/41#issuecomment-170615239>
> .
>



-- 
--
Jeff Cantrill
Senior Software Engineer, Red Hat Engineering
Red Hat, Inc.
*Office*: 703-748-4420 | 866-546-8970 ext. 8162420
jcantril@redhat.com
http://www.redhat.com

**Comment by richm** [comment]
@jcantrill https://github.com/openshift/openshift-docs/pull/1417

**Comment by ewolinetz** [comment]
LGTM

**Pull request merged**
