### PR TITLE
Bug 1843461: Revert fluent to 1.7.4 and dependencies to address performance

### PR DESCRIPTION
**Pull request by jcantrill**
This PR

 * Updates fluent to address performance issues related to 4.4
 * Cherrypicks the needed changes from 4.6
 * Updates lib and vendored gems to be compatible with 4.5 release stream

ref: https://bugzilla.redhat.com/show_bug.cgi?id=1843461

Backport of https://github.com/openshift/origin-aggregated-logging/pull/1953

### CODE REVIEW

**Comment by ewolinetz** [comment]
are all these commits intended?

**Comment by jcantrill** [comment]
cc @vimalk78 please ensure this has changes needed for syslog

**Comment by ewolinetz** [comment]
/approve
i'll let @vimalk78 give the :+1: to push it through

**Pull request merged**
