### PR TITLE
Making changes to preserve time microsecond precision

### PR DESCRIPTION
**Pull request by ewolinetz**

### CODE REVIEW

**Comment by ewolinetz** [comment]
@sosiouxme @jcantrill PTAL

**Comment by jcantrill** [comment]
@ewolinetz LGTM

**Comment by sosiouxme** [comment]
[merge]

**Comment by sosiouxme** [comment]
heh, we don't have a bot do we.

**Comment by ewolinetz** [comment]
@jcantrill can you merge this please?  We aren't able to yet :)

**Comment by jcantrill** [comment]
[merge]  I'm the bot

**Pull request merged**
