### PR TITLE
bump openshift-elasticsearch-plugin to 2.4.4.9

### PR DESCRIPTION
**Pull request by jcantrill**
bug 1456413. Fix Kibana security error message
bug 1459221. Fix null pointer in KibanaUserReindexAction
fix plugin improper evaluation of index pattern
fix plugin improper evaluation of how to retrieve a user from 2.4.4.6

### CODE REVIEW

**Comment by jcantrill** [comment]
[test]

**Comment by jcantrill** [comment]
cc @richm @portante

**Comment by portante** [comment]
@jcantrill, so this will let us get a build, verify it works, and then change the target URL to test the final bits?

**Comment by jcantrill** [comment]
@portante Im just testing that this plugin will pass our CI before I worry about actually releasing...I want to ensure it works first and will change if we get 'success'

**Comment by jcantrill** [comment]
[merge][severity:blocker] flake?

**Comment by jcantrill** [comment]
backport 1.5 in #519

**Pull request merged**
