### PR TITLE
fixing smoke test for release-4.5

### PR DESCRIPTION
**Pull request by ewolinetz**
Hardcoding the CLO and EO branch versions to release-4.5

### CODE REVIEW

**Comment by ewolinetz** [comment]
/cc @jcantrill 

@bparees this is specific only to test and unblocks https://github.com/openshift/origin-aggregated-logging/pull/1944, can we bypass the bz labels?

**Comment by bparees** [comment]
test code change only, overriding BZ req.

**Comment by ewolinetz** [comment]
/hold
going to make this a little more elegant

**Pull request merged**
