### PR TITLE
fix deployer readme links

### PR DESCRIPTION
**Pull request by jcantrill**
Update to:
* fix links for configmap docs
* identify fluentd requires additional steps

cc @sosiouxme @ewolinetz

### CODE REVIEW

**Comment by sosiouxme** [comment]
:+1:

**Comment by ewolinetz** [comment]
:shipit:

**Comment by jcantrill** [comment]
[merge]

**Comment by ewolinetz** [comment]
it says the tests failed... which shouldn't stop this from being [merge]d but they shouldn't be failing...? ill check it out

**Comment by ewolinetz** [comment]
etcd flake... [merge]

**Pull request merged**
