### PR TITLE
Bug 1732058: Move to 5.6.16 to fix Kibana execution flaw

### PR DESCRIPTION
**Pull request by jcantrill**
This PR fixes:

https://bugzilla.redhat.com/show_bug.cgi?id=1732058
https://bugzilla.redhat.com/show_bug.cgi?id=1752853
https://bugzilla.redhat.com/show_bug.cgi?id=1738406
https://bugzilla.redhat.com/show_bug.cgi?id=1731833
https://bugzilla.redhat.com/show_bug.cgi?id=1731780

Backport of :

https://github.com/openshift/origin-aggregated-logging/pull/1754
https://github.com/openshift/origin-aggregated-logging/pull/1742

### CODE REVIEW

**Comment by richm** [comment]
```
    "msg": "The installed kernel version does not meet the required minimum for RHEL 7.5.\nPlease update the kernel before continuing.\nMinimum Kernel Version: 3.10.0-862.31.1\nInstalled Kernel Version: 3.10.0-862.3.3.el7.x86_64\nReference: https://bugzilla.redhat.com/show_bug.cgi?id=1749024\n"
```
???

**Comment by richm** [comment]
looks like https://bugzilla.redhat.com/show_bug.cgi?id=1749024 broke our 3.11 tests - trying to find someone to help

**Comment by jcantrill** [comment]
Manually merging based on infrastructure blocking testing.  4.2 was validated by QE to resolve the issue and there is likely minimal to no differences between the two images

**Pull request merged**
