### PR TITLE
use version 2.x of the elasticsearch libraries

### PR DESCRIPTION
**Pull request by richm**
Work around gem dependency issues in the elasticsearch libraries so
that we can use the 2.x versions of the libraries.
@jcantrill @portante PTAL
[test]

### CODE REVIEW

**Comment by jcantrill** [comment]
[test] flake?

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
@jcantrill @portante can we get this in today?

**Comment by richm** [comment]
[merge]

**Comment by richm** [comment]
curator [merge] flake

**Comment by richm** [comment]
[merge]

**Pull request merged**
