### PR TITLE
Replace logging-dump script with a warning to use must-gather

### PR DESCRIPTION
**Pull request by periklis**
This PR replaces the contents of `hack/logging-dump.sh` with a warning notice to use must-gather.

/cc @jcantrill @blockloop

### CODE REVIEW

**Comment by jcantrill** [comment]
@periklis instead of updating the script maybe consider replacing it with logging-dump.sh.md or other documentation and add notes pointing people to the correct place.

**Comment by periklis** [comment]
> @periklis instead of updating the script maybe consider replacing it with logging-dump.sh.md or other documentation and add notes pointing people to the correct place.

@jcantrill  That was my first thought, but since I now of two cases (QE, CEE) using this script actively via `wget+sh` in their scripts, I would like to make their scripts fail fast so that they can adapt to `must-gather` asap.

**Review by blockloop — APPROVED** [review]
/lgtm

**Comment by ehvs** [comment]
Can we have this merged and added to documentation in the Troubleshooting section from Logging ?

**Comment by periklis** [comment]
> Can we have this merged and added to documentation in the Troubleshooting section from Logging ?
> @periklis @jcantrill

AFAIK, @mburke5678 will add a new section for cluster-logging's must-gather.

**Comment by mburke5678** [comment]
I linked the PR for adding must-gather to the end user docs. Do we want to mention not using `logging-dump.sh`? We do not have the script in the docs. 
See: https://github.com/openshift/openshift-docs/pull/25276/files#diff-ff91f582b15e35251d86b9692dc1e248R15-R18

**Comment by periklis** [comment]
> > @periklis instead of updating the script maybe consider replacing it with logging-dump.sh.md or other documentation and add notes pointing people to the correct place.
> 
> @jcantrill That was my first thought, but since I now of two cases (QE, CEE) using this script actively via `wget+sh` in their scripts, I would like to make their scripts fail fast so that they can adapt to `must-gather` asap.

@jcantrill :point_up:

**Comment by jcantrill** [comment]
overriding valid bz as this is a non-code change

**Pull request merged**
