### PR TITLE
LOG-358. ClusterLogging only supports the name 'instance'

### PR DESCRIPTION
**Pull request by jcantrill**
Support https://github.com/openshift/cluster-logging-operator/pull/123

### CODE REVIEW

**Comment by richm** [comment]
looks like you missed a place
```
Error from server (NotFound): clusterloggings.logging.openshift.io "example" not found
[ERROR] PID 133: hack/testing/entrypoint.sh:57: `oc patch -n ${LOGGING_NS} clusterlogging example --type=json --patch '[
```

**Comment by richm** [comment]
```
error: unable to recognize "openshift/ci-operator/build-image/elasticsearch-catalogsourceconfig.yaml": no matches for kind "CatalogSourceConfig" in version "marketplace.redhat.com/v1alpha1"
```
@bparees Did they get rid of `CatalogSourceConfig` objects, or move them from `marketplace.redhat.com/v1alpha1`?

**Comment by bparees** [comment]
> @bparees Did they get rid of CatalogSourceConfig objects, or move them from marketplace.redhat.com/v1alpha1?

I just saw that they're being moved.  See the "Group and version changes of Marketplace APIs" thread on aos-devel.  I guess that has already landed?

**Comment by richm** [comment]
I've added this change to https://github.com/openshift/origin-aggregated-logging/pull/1573 - we may need both of them at the same time in order to pass ci now

**Comment by jcantrill** [comment]
close in favor #1573

**Pull request closed without merging**
