### PR TITLE
updating e2e testing to accomodate daemonset changes

### PR DESCRIPTION
**Pull request by ewolinetz**
Addressing - https://gist.github.com/ewolinetz/f403b9f37a0f79e16086

@richm @sosiouxme PTAL

### CODE REVIEW

**Comment by ewolinetz** [comment]
@richm i'll check that out! if it works as expected i'll also try it out with the other elements we check on

**Comment by ewolinetz** [comment]
@richm looks like that is really only feasible when we have one resource we're looking for (unless we iterate, which might be more complicated?) -- possibly in a future iteration?

**Comment by richm** [comment]
jsonpath supports wildcards and iteration - http://kubernetes.io/v1.1/docs/user-guide/jsonpath.html::

    * 	wildcard. Get all objects 	{.items[*].metadata.name} 	[127.0.0.1 127.0.0.2]
    range, end 	iterate list 	{range .items[*]}[{.metadata.name}, {.status.capacity}] {end} 	[127.0.0.1, map[cpu:4]] [127.0.0.2, map[cpu:8]]

**Comment by ewolinetz** [comment]
@richm awesome! let me try to use that

**Comment by ewolinetz** [comment]
@richm @sosiouxme updating to use jsonpath to simplify getting current EFK objects PTAL

**Comment by richm** [comment]
lgtm

**Pull request merged**
