### PR TITLE
readiness.sh is bloating the dentry cache

### PR DESCRIPTION
**Pull request by normanschlatter**
Dont bloat the dentry cache

### CODE REVIEW

**Comment by richm** [comment]
> Dont bloat the dentry cache

Can you share any data which shows that using curl in the Elasticsearch readiness probe has a significant impact on the dentry cache?

**Comment by normanschlatter** [comment]
> > Dont bloat the dentry cache
> 
> Can you share any data which shows that using curl in the Elasticsearch readiness probe has a significant impact on the dentry cache?

sure, first of all this pull request is related to redhat CASE 02367806

our hosts dentry cache is filled with around ~300GB just from all the curl calls, here are our metrics:

dentry_cache_usage

we ran a systemtap script on the host above which is running the elasticsearch container, thats the output, as you can see its mostly curl:

$ awk '/PROCESS/,/STACK/' dentry_alloc_2.stp_output.log3 | egrep -v '(PROCESS|STACKS)' | tr -s "(" " " | awk '{m[$2] += $1} END {for (i in m) {printf "%5s %s \n", m[i], i} }' | sort -nrk 1 | head
 3250 curl 
 1889 hyperkube 
  357 docker-containe 
  233 docker-runc-cur 
  227 vmtoolsd 
  198 snmpd 
  192 runc:[2:INIT] 
  153 iptables 
  144 node_exporter 
  104 java 

$ grep curl dentry_alloc_2.stp_output.log3 
487	 curl(95499) readiness.sh(95494) docker-containe(95476) docker-containe(12517) dockerd-current(12509)
487	 curl(95499) readiness.sh(95494) docker-containe(95476) docker-containe(12517) dockerd-current(12509)
502	 curl(95630) readiness.sh(95625) docker-containe(95592) docker-containe(12517) dockerd-current(12509)
392	 curl(95782) readiness.sh(95776) docker-containe(95755) docker-containe(12517) dockerd-current(12509)
393	 curl(95705) readiness.sh(95699) docker-containe(95680) docker-containe(12517) dockerd-current(12509)
487	 curl(95499) readiness.sh(95494) docker-containe(95476) docker-containe(12517) dockerd-current(12509)
502	 curl(95630) readiness.sh(95625) docker-containe(95592) docker-containe(12517) dockerd-current(12509)

**Comment by richm** [comment]
Thanks, this is really good data.

> sure, first of all this pull request is related to redhat CASE 02367806

Is there a Red Hat bugzilla associated with that case?  If so, I'd like to associate this PR with that BZ.

**Comment by normanschlatter** [comment]
> Thanks, this is really good data.
> 
> > sure, first of all this pull request is related to redhat CASE 02367806
> 
> Is there a Red Hat bugzilla associated with that case? If so, I'd like to associate this PR with that BZ.

currently only an open redhat support case which is waiting for next steps, after asking how to get this fix into the current enterprise v3.11 image.

"I will get back to you further updates soon."

**Comment by richm** [comment]
> currently only an open redhat support case which is waiting for next steps, after asking how to get this fix into the current enterprise v3.11 image.

We'll need a BZ filed against OCP 3.11 Logging to get this into an 3.11 image update.  IMO this is a bug and should have a BZ.  Usually support opens BZs associated with cases.  If not, then I will.

**Comment by ggore** [comment]
Bug 1720479 for OCP 3.11 Logging.

**Comment by lukas-vlcek** [comment]
We should consider what is the impact of this issue on other scripts that use cURL and are called often. Shall we set this variable on the container level?

**Comment by richm** [comment]
> We should consider what is the impact of this issue on other scripts that use cURL and are called often. Shall we set this variable on the container level?
> //cc @richm @ewolinetz @jcantrill

The Kibana readiness probe uses http not https, so is unaffected.

**Comment by richm** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1720479

**Pull request merged**
