### PR TITLE
bug 1560778. Reduce the number of index-patterns for cluster admins

### PR DESCRIPTION
**Pull request by jcantrill**
This PR depends on:  https://github.com/fabric8io/openshift-elasticsearch-plugin/pull/128/files

### CODE REVIEW

**Comment by jcantrill** [comment]
@richm I see both these tests fail on tests related to rsyslog which is unrelated to the change introduced by this PR.  I'm inclined to manually merge.  Thoughts?

**Comment by richm** [comment]
> @richm I see both these tests fail on tests related to rsyslog which is unrelated to the change introduced by this PR. I'm inclined to manually merge. Thoughts?

CI is failing all over the place, not just at rsyslog, and appears to be unrelated to the PRs which are being tested.  So sure, we can force merge many of the PRs.

**Comment by richm** [comment]
access control failure
/test json-file

**Comment by richm** [comment]
/cherrypick 3.9
@jcantrill is there a different patch for es5.x?

**Comment by jcantrill** [comment]
@richm There will have to be if I already didnt merge it into 5.x.  Was tracking them here: https://github.com/fabric8io/openshift-elasticsearch-plugin/issues/124

**Pull request merged**
