### PR TITLE
utility to check es_cluster_health

### PR DESCRIPTION
**Pull request by jcantrill**
Add quick script to grab cluster health via oc exec:

```oc exec $PODNAME es_cluster_health```
or
```oc exec $PODNAME -- bash -c "INDEX=foo,bar es_cluster_health"```

### CODE REVIEW

**Comment by jcantrill** [comment]
[test]

**Comment by richm** [comment]
lgtm

**Comment by jcantrill** [comment]
[merge]

**Comment by lukas-vlcek** [comment]
LGTM

**Comment by jcantrill** [comment]
[merge]

**Pull request merged**
