### PR TITLE
Bug 1731855: Add jaeger permissions to create ES templates

### PR DESCRIPTION
**Pull request by pavolloffay**
Port of #1699 to 4.1

https://bugzilla.redhat.com/show_bug.cgi?id=1731855

Signed-off-by: Pavol Loffay <ploffay@redhat.com>

### CODE REVIEW

**Comment by jcantrill** [comment]
@pavolloffay you will need to generate a bz and reference it here in order for this to go through the process

**Comment by pavolloffay** [comment]
@jcantrill here is bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1731855

**Comment by eparis** [comment]
I do not see a 4.2 bug or a 4.2 Jira card. How is QE going to verify this in 4.2/master?

**Comment by pavolloffay** [comment]
@eparis for 4.2 I have created https://bugzilla.redhat.com/show_bug.cgi?id=1732364

**Comment by eparis** [comment]
looks like the 4.2 bug (and PR) are still open/outstanding.  please run `/bugzilla refresh` once the 4.2 BZ is VERIFIED by QE.  Thank you!

**Comment by pavolloffay** [comment]
@jcaianirh @richm could this be merged?

**Comment by pavolloffay** [comment]
@richm thanks for the approving.

Do we need to change bug status re https://github.com/openshift/origin-aggregated-logging/pull/1700#issuecomment-515094448?

**Comment by richm** [comment]
> @richm thanks for the approving.
> 
> Do we need to change bug status re [#1700 (comment)](https://github.com/openshift/origin-aggregated-logging/pull/1700#issuecomment-515094448)?

Yes, you need to make sure the bz status is correct so that bugzilla/valid-bug reports that the bz is valid.

**Comment by pavolloffay** [comment]
@richm now it needs cherry-pick-approved label

**Comment by richm** [comment]
> @richm now it needs cherry-pick-approved label

@bparees how do we get the cherry-pick-approved label?

**Comment by bparees** [comment]
> @bparees how do we get the cherry-pick-approved label?

you wait for the patch manager to query all the 4.1 PRs, find yours, confirm your paperwork is in order (PR has a BZ associated, BZ has  4.2 BZ associated with it, 4.2 BZ has been verified by QE, and the 4.1 PR looks substantially similar to the 4.2 PR that resolved the issue in master).  They will then apply the label.

Since we only merge 4.1.z content on mon/tues currently, they typically do their queries on those days.  So just make sure your paperwork is in order before monday and you should be all set.

**Comment by pavolloffay** [comment]
@bparees or @richm I am not sure if the papework/BZ is in order (I do not work in openshift group, I am not falimiar with the process). Could you please check that for me? I do not want to wait another if we miss this one.

**Comment by bparees** [comment]
> @bparees or @richm I am not sure if the papework/BZ is in order

you've referenced your 4.1.z BZ in your PR: https://bugzilla.redhat.com/show_bug.cgi?id=1731855

your 4.1 BZ depends on a 4.2 BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1732364

Your 4.2 BZ is verified

Your 4.2 BZ references a 4.2/master PR that is merged: https://github.com/openshift/origin-aggregated-logging/pull/1699

Your 4.1 + 4.2 PRs look identical.

So i believe you are in good shape and i'd expect the patch manager to approve this

(The bot actually does a fair bit of the BZ validation for you, as you saw in https://github.com/openshift/origin-aggregated-logging/pull/1700#issuecomment-515459127)

**Comment by pavolloffay** [comment]
Thanks @bparees it's very appreciated

**Comment by jwforres** [comment]
This didn't land in the "paperwork done" query because it didn't have the "approved" label, but it doesn't look like Tide is actually complaining about the approved label on this repo. Does this repo not require "approved" for merge @jcantrill @richm  I just don't want you guys to get bit by this in the future. We always look at the paperwork done query first and then make an effort to go through the "paperwork not done" to help things along.

I'm approving the cherry-pick since the folks I'd expect to `/approve` this PR have already ack'ed on it.

**Comment by pavolloffay** [comment]
Steps to test:

1. deploy es-operator and jaeger-operator.
2. create jaeger cr, mind the latest jaeger-collector image
```
# This CR deploys Jaeger and Elasticsearch
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  collector:
    image: jaegertracing/jaeger-collector:latest
  query:
  storage:
    type: elasticsearch
    elasticsearch:
      nodeCount: 1
```
3. wait until jaeger and ES are running
4. jaeger should create jaeger-span and jaeger-dependencies index templates

**Pull request merged**
