### PR TITLE
Bug 1823305: Fix sign-off kibana link

### PR DESCRIPTION
**Pull request by jcantrill**
This PR:
* Corrects the signoff link

Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1823305

blocked by https://github.com/openshift/origin-kibana/pull/35

### CODE REVIEW

**Comment by jcantrill** [comment]
blocked by https://github.com/openshift/origin-aggregated-logging/pull/1895

**Comment by petr-muller** [comment]
/hold

The SHA on this PR hit GitHub's limit of of statuses (reported job results) and possible passing result cannot be reported anymore. You'll need to force-push an amend to get a new SHA once this has a chance to pass tests.

**Comment by petr-muller** [comment]
https://github.com/openshift/origin-aggregated-logging/pull/1894#issuecomment-631371237

Still holds

**Comment by ashcrow** [comment]
Spoke with @jcantrill about this and there is no related master PR as the functionality was removed. Approved.

**Pull request merged**
