### PR TITLE
Update hack/lib vendor

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Update the hack/lib update script to add a changelog

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

Vendor origin/hack/lib at 596d795

Changelog:
52f220e Turn off journald rate limiter when running test-end-to-end-docker.sh
d20057b Correctly place script output at _output/scripts
9449f60 permit OS_GIT_VERSION to have a git hash longer than 7 characters - this occurs when 7 characters are not enough to uniquely describe a given commit
fee1157 Move compress AWK script into hack/lib
493d25c Add $OS_OUTPUT_SCRIPTPATH and rename release/rpm path vars

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

[carry] Remove references to extraneous scripts

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

[carry] Ensure that $OS_ROOT = $OS_O_A_L_DIR

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

[carry] Point os::util::ensure::built_binary_exists at Origin

When the Bash tooling relies on tools built out of Origin, it tries to
build them from the Origin repository. This is not a great hack as it
requires you to have Origin checked out still as a sister repository,
but we need to do more thinking for this.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

[test]

### CODE REVIEW

**Comment by richm** [comment]
[test]

**Comment by stevekuznetsov** [comment]
[merge]

**Comment by stevekuznetsov** [comment]
@richm merge is yours

**Comment by richm** [comment]
[merge]

**Pull request merged**
