### PR TITLE
LOG-2032: Update fluent kubernetes metadata filter to allow reading f…

### PR DESCRIPTION
**Pull request by jcantrill**
…rom /var/log/pods

### Description
This PR:
* Updates the fluent-plugin-kubernetes_metadata to allow reading logs from /var/log/pods
* Preps functional tests for vector
* Blocks https://github.com/openshift/cluster-logging-operator/pull/1273

### Links
 * https://issues.redhat.com/browse/LOG-2032

### CODE REVIEW

**Comment by jcantrill** [comment]
cc @vimalk78 @alanconway

**Review by alanconway — APPROVED** [review]
/lgtm

**Pull request merged**
