### PR TITLE
Bug 1748478: Add more states to init probe

### PR DESCRIPTION
**Pull request by jcantrill**
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1748478

### CODE REVIEW

**Comment by richm** [comment]
not sure if this is a flake - the errors are in es/sg related code - access control and multi-tenancy - maybe something to do with es startup/readiness?

**Comment by richm** [comment]
> not sure if this is a flake - the errors are in es/sg related code - access control and multi-tenancy - maybe something to do with es startup/readiness?

yep - not a flake - it is failing consistently in the same places

**Comment by jcantrill** [comment]
> > not sure if this is a flake - the errors are in es/sg related code - access control and multi-tenancy - maybe something to do with es startup/readiness?
> 
> yep - not a flake - it is failing consistently in the same places

ran the multi-tenant test locally with success.  the access control test failed on a line where I was missing an artifact dir towards the end; hoping this is local env issu

**Comment by richm** [comment]
aws flake
/retest

**Pull request merged**
