### PR TITLE
Adding new plugin for parsing ovn logs LOG-1377(WIP)

### PR DESCRIPTION
**Pull request by ajaygupta978**
### Description
This plugin parses OVN logs and transform into json structure. 

/cc @vimalk78 
/assign @jcantrill 

### Links

- Depending on PR(s): 
- Bugzilla:
- Github issue:
- JIRA: https://issues.redhat.com/browse/LOG-1377 
- Enhancement proposal:

### CODE REVIEW

**Comment by ajaygupta978** [comment]
This plugin will take OVN as input and transform into json structure. 
Example Input:
```
2021-07-06T08:26:58.687Z|00004|acl_log(ovn_pinctrl0)|INFO|name="verify-audit-logging_deny-all", verdict=drop, severity=alert:icmp,vlan_tci=0x0000,dl_src=0a:58:0a:81:02:12,dl_dst=0a:58:0a:81:02:14,nw_src=10.129.2.18,nw_dst=10.129.2.20,nw_tos=0,nw_ecn=0,nw_ttl=64,icmp_type=8,icmp_code=0

```

Output:
```
{"@timestamp":"2021-07-06T08:26:58.687Z",
"level":"info",
"structured":{
   "name":"\"verify-audit-logging_deny-all\"",
    "verdict":"drop",
    "severity":"alert:icmp",
    "vlan_tci":"0x0000",
    "dl_src":"0a:58:0a:81:02:12",
    "dl_dst":"0a:58:0a:81:02:14",
    "nw_src":"10.129.2.18",
    "nw_dst":"10.129.2.20",
    "nw_tos":"0",
    "nw_ecn":"0",
    "nw_ttl":"64",
    "icmp_type":"8",
    "icmp_code”:”0”
}, 
"hostname": "example.com"}
```

**Comment by ajaygupta978** [comment]
@vimalk78 added more tests. Please review.

**Comment by jcantrill** [comment]
Closing given @ajaygupta978  per the path we are on for this feature we determined it was not required

**Pull request closed without merging**
