### PR TITLE
[release-3.7] fluentd must use TLSv1.2 or later to talk to Elasticsearch

### PR DESCRIPTION
**Pull request by richm**
(cherry picked from commit f33cdc402275f16afd3bb784c4dddc737779b2ab)

### CODE REVIEW

**Comment by Reamer** [comment]
Any progress here?

**Comment by jcantrill** [comment]
@richm I played around with the one failing script and I believe its related to the time we wait for a result to arrive.  I was able to subtly tweak the test locally and  got the test to pass.  I am satisfied this breaks nothing else.  Merging

**Pull request merged**
