### PR TITLE
Turn off console logging; add file logging

### PR DESCRIPTION
**Pull request by portante**

### CODE REVIEW

**Comment by jcantrill** [comment]
@portante This change need to be made to the ansible installer for anything 3.5 or more.  3.4 or earlier we will most likely need to provide documentation.  I do not foresee us publishing additional 3.4 images unless they are show stoppers.  We can write a work around correct?

**Comment by portante** [comment]
@jcantrill, is that in openshift-ansible?

**Comment by jcantrill** [comment]
@portante yes

**Comment by portante** [comment]
Moved to https://github.com/openshift/openshift-ansible/pull/3687.

**Pull request closed without merging**
