### PR TITLE
Creating OWNERS file for repo

### PR DESCRIPTION
**Pull request by ewolinetz**

### CODE REVIEW

**Comment by richm** [comment]
It's different than https://github.com/openshift/release/pull/1219/commits/0d73e3edc18aeeaabfc181cdbc52c56d7c2fd76c . . .

**Comment by ewolinetz** [comment]
@richm wouldn't we want more people that can review than approve? I can update this file to match the other one...

**Comment by richm** [comment]
@ewolinetz review is strong - that means merge ability - what does approve do?

**Comment by ewolinetz** [comment]
approve is required, even if its been reviewed... so in my mind approve is gating

**Comment by richm** [comment]
@ewolinetz afaik, I can /lgtm a PR and have it merged without that PR being approved

**Comment by ewolinetz** [comment]
@richm I think that's because you're an approver... so it's automatically approved since you opened it...

**Comment by richm** [comment]
ok - and I'm also not really sure what the purpose is, or if it matters if it is different than https://github.com/openshift/release/commit/0d73e3edc18aeeaabfc181cdbc52c56d7c2fd76c

**Comment by stevekuznetsov** [comment]
If we ensure this OWNERS is identical to that in the `release` repo this is good to go

**Comment by ewolinetz** [comment]
updated to match `release` repo

**Comment by ewolinetz** [comment]
@jcantrill per @stevekuznetsov and @richm I made this to match what we have for release, so I'll defer to them for your question

**Comment by stevekuznetsov** [comment]
All approvers are by default also reviewers

**Comment by stevekuznetsov** [comment]
Silly to test this more

**Pull request merged**
