### PR TITLE
Bug 1868916: Move elasticsearch to OpenJDK 11

### PR DESCRIPTION
**Pull request by yselkowitz**
OpenJDK 11 is supported with ES since 6.5:

https://www.elastic.co/support/matrix#matrix_jvm

The bulk of these changes are needed for changes in supported JVM
options between 8 and 11.

### CODE REVIEW

**Comment by vimalk78** [comment]
needs to be merged downstream

**Comment by ewolinetz** [comment]
@vimalk78 do we know if jdk11 is packaged yet downstream?

**Comment by yselkowitz** [comment]
java-11-openjdk has been in RHEL since 7.6.

**Comment by jcantrill** [comment]
@jupierce please advise if jdk11 is available here https://github.com/openshift/ocp-build-data/blob/openshift-4.6-rhel-8/images/logging-elasticsearch6.yml#L12

**Comment by ewolinetz** [comment]
@yselkowitz we need to also update the other elasticsearch Dockerfiles then, don't we?

**Comment by yselkowitz** [comment]
Repushed to modify all the Dockerfiles.

**Comment by yselkowitz** [comment]
are those real failures or just flakes?

**Comment by ewolinetz** [comment]
@QiaolingTang can we also make sure this is regression tested against our x86 architecture?

**Comment by yselkowitz** [comment]
are those real failures or just flakes?

**Comment by ewolinetz** [comment]
/test smoke
it looks like it failed to deploy the operator

**Comment by QiaolingTang** [comment]
> @QiaolingTang can we also make sure this is regression tested against our x86 architecture?

OK, I'll test it when there has the image.

**Comment by yselkowitz** [comment]
Is the smoke test failure a real issue or a flake?

**Comment by yselkowitz** [comment]
CI fix has merged
/test smoke

**Comment by yselkowitz** [comment]
CI has passed, just needs LGTM now.

**Pull request merged**
