### PR TITLE
update template and patterns for ovirt, collectd, tlog, aushape

### PR DESCRIPTION
**Pull request by richm**
update template and patterns for ovirt, collectd, tlog, aushape
This is the 0.0.5 release of viaq/elasticsearch-templates
@jcantrill @ewolinetz @lukas-vlcek @portante @nhosoi PTAL
[test]

### CODE REVIEW

**Comment by richm** [comment]
[test]

**Comment by ewolinetz** [comment]
just updating the templates? LGTM

**Comment by richm** [comment]
> just updating the templates? LGTM
Yes, thanks. [merge]

**Comment by richm** [comment]
[merge]

**Comment by richm** [comment]
[merge]

**Comment by richm** [comment]
flake? kibana never started? [merge]

**Comment by richm** [comment]
[merge]

**Pull request merged**
