### PR TITLE
[WIP] Add Kafka output support

### PR DESCRIPTION
**Pull request by AlessandroMenti**
This PR adds Kafka output support and is meant to be merged together with the related PR for openshift-docs.

Note that:

* I'm still working on the test suite;
* the PR also requires that the relevant packages added in the Dockerfiles are added to the upstream repositories (SRPMs and SPECs can be found at https://github.com/AlessandroMenti/openshift-kafka-for-fluentd-rpms).

### CODE REVIEW

**Comment by sghosh151** [comment]
Please include TLS support

**Comment by richm** [comment]
> Please include TLS support

https://github.com/fluent/fluent-plugin-kafka#ssl-authentication - the plugin supports it, we just need to allow users to specify those parameters.

**Comment by jcantrill** [comment]
closing in favor of #1853

**Pull request closed without merging**
