### PR TITLE
bug 1427274.  Allow users to provide override styles (e.g. header cus…

### PR DESCRIPTION
**Pull request by jcantrill**
…tomization)

Depends on https://github.com/openshift/origin-kibana/pull/26

### CODE REVIEW

**Comment by jcantrill** [comment]
[test]

**Comment by richm** [comment]
[merge]

**Comment by richm** [comment]
[merge]

**Comment by richm** [comment]
[merge]

**Comment by richm** [comment]
@jcantrill There is no 4.5.1-2 release at https://github.com/openshift/origin-kibana/releases - this is why test/merge is failing

**Comment by jcantrill** [comment]
@richm released 4.5.1-2 of origin-kibana after some testing.  Tested with a deployment by adding a configmap to the desired file here.

**Comment by richm** [comment]
[merge]

**Comment by jcantrill** [comment]
[merge]

**Pull request merged**
