### PR TITLE
bump origin-kibana plugin to v0.6.0

### PR DESCRIPTION
**Pull request by jcantrill**
cc @sosiouxme @ewolinetz 

[test]

### CODE REVIEW

**Comment by ewolinetz** [comment]
LGTM, what changes are a part of the plugin bump?

**Comment by jcantrill** [comment]
@ewolinetz  Notes here. https://github.com/openshift/origin-kibana/releases/tag/v0.6.0  I see only one commit which is minor but should have made into the last release.

**Comment by ewolinetz** [comment]
etcd issue... [test]

**Comment by sosiouxme** [comment]
lgtm
https://ci.openshift.redhat.com/jenkins/job/test-origin-aggregated-logging/526 ruby build failed due to lacking credentials; wondering if there is a race on the registry coming up and credentials propagating to the service account.

Anyway, [test] again wouldja

**Comment by ewolinetz** [comment]
[test]

**Comment by ewolinetz** [comment]
re[test]

**Comment by ewolinetz** [comment]
[merge]

**Pull request merged**
