### PR TITLE
removing targetPort in headless service definition per https://github…

### PR DESCRIPTION
**Pull request by ewolinetz**
….com/kubernetes/kubernetes/issues/20488

@sosiouxme PTAL

### CODE REVIEW

**Comment by sosiouxme** [comment]
LGTM assuming it works :)

**Comment by ewolinetz** [comment]
It works as of 1.2.0-alpha.4  I'll see if I can find an env with an older version of K8S to test on too

**Comment by ewolinetz** [comment]
@sosiouxme works with kubernetes v1.1.0-origin-1107-g4c8e6f4

**Comment by sosiouxme** [comment]
ship it!

**Pull request merged**
