### PR TITLE
[release-3.9] Adding test to check for duplicate records with fluentd and journald …

### PR DESCRIPTION
**Pull request by ewolinetz**
…file rollover

Manual cherry-pick of https://github.com/openshift/origin-aggregated-logging/pull/1074

### CODE REVIEW

**Comment by ewolinetz** [comment]
missed change here: https://github.com/openshift/origin-aggregated-logging/pull/1209/files#diff-8caa6d145971ed042f17c6559038b9ebR372

**Comment by ewolinetz** [comment]
Addressed missed change

**Comment by ewolinetz** [comment]
test pod failed to start for test/zzz-correct-index-names.sh:50

**Comment by richm** [comment]
install flake
/retest

**Comment by richm** [comment]
```
FAILURE after 599.965s: test/cluster/functionality.sh:82: executing 'curl_es 'logging-es-data-master-1elclkoc-1-kj7kj' '/_cat/indices?h=index'' expecting any result and text '^(project|\.operations)\.'; re-trying every 0.2s until completion or 600.000s: the command timed out
```
odd that there are no project.* or .operations indices . . . flake?
/test json-file

**Comment by richm** [comment]
same with journald
/test logging

**Comment by ewolinetz** [comment]
flake
/retest

**Comment by richm** [comment]
remote-syslog flake
/test json-file

**Comment by richm** [comment]
/test json-file
curator flake

**Comment by ewolinetz** [comment]
curator flake again
/test json-file

**Comment by ewolinetz** [comment]
fluentd termination flake
/test json-file

**Comment by ewolinetz** [comment]
@jcantrill @richm we only seem to see the flake where fluentd won't terminate in time for the json-file test (at least, that's when i've seen it most). Is it worth possibly opening up a bug/issue to be investigated on the OCP side? I thought we had a pod termination time on there and it seems that K8s is letting it live past that/is taking a long time to cull it once that time is reached.

**Comment by richm** [comment]
> Is it worth possibly opening up a bug/issue to be investigated on the OCP side?

maybe, but then we'll have to do a lot of work to demonstrate the problem outside of our ci environment . . . at least that's what happened when I opened similar issues upstream in kubernetes about daemonset readiness reporting . . . so if you want to do that extra work, please do

**Comment by ewolinetz** [comment]
fluentd flake again
/retest

**Pull request merged**
