### PR TITLE
Adding clarification on oc new-app output and configmaps

### PR DESCRIPTION
**Pull request by ewolinetz**
To address https://bugzilla.redhat.com/show_bug.cgi?id=1406799
@jcantrill @richm

### CODE REVIEW

**Comment by richm** [comment]
lgtm
will this go away with the ansible based deployer?

**Comment by ewolinetz** [comment]
yes since we won't be using `oc new-app` to instantiate a deployer pod

**Comment by ewolinetz** [comment]
[merge]

**Comment by ewolinetz** [comment]
poor fella, we lost track of him... [merge]

**Pull request merged**
