### PR TITLE
Bug 1886856: Add typhoeus for keep-alives in elasticsearch plugin

### PR DESCRIPTION
**Pull request by periklis**
### Description
This PR add a dependency namely `typhoeus` for fluentd-plugin-elasticsearch to enable keep-alive connections
 
/cc @blockloop 
/assign @ewolinetz 

### Links:
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1886856

### CODE REVIEW

**Comment by jcantrill** [comment]
@periklis how does adding this plugin enable keep-alive connections?  I see this config option but not any info: https://github.com/uken/fluent-plugin-elasticsearch#http_backend

**Comment by periklis** [comment]
> @periklis how does adding this plugin enable keep-alive connections? I see this config option but not any info: https://github.com/uken/fluent-plugin-elasticsearch#http_backend

```
With http_backend typhoeus, elasticsearch plugin uses typhoeus faraday http backend. Typhoeus can handle HTTP keepalive.
```
says in that link.

**Comment by jcantrill** [comment]
@periklis does `excon` not handle keep alive?

**Comment by periklis** [comment]
> @periklis does `excon` not handle keep alive?

From what I can see in docs and code, unfortunately not.

**Comment by jcantrill** [comment]
closing in favor of https://github.com/openshift/origin-aggregated-logging/pull/2010

**Pull request closed without merging**
