### PR TITLE
allow use of fluentd monitor and debug agents

### PR DESCRIPTION
**Pull request by richm**
@jcantrill @ewolinetz @lukas-vlcek @nhosoi @t0ffel ptal
[test]

```
edit daemonset logging-fluentd
add env ENABLE_MONITOR_AGENT true
$ oc exec logging-fluentd-wjm93 -- curl -s http://localhost:24220/api/plugins.json|python -mjson.tool
        {
            "buffer_queue_length": 0,
            "buffer_total_queued_size": 151777,
            "config": {
                "@type": "secure_forward",
...
            }
            "retry_count": 0,
            "type": "secure_forward"
        },
```

### CODE REVIEW

**Comment by ewolinetz** [comment]
LGTM

**Comment by ewolinetz** [comment]
if only there was a way we could dynamically `@include` fluentd configs based on env vars...

**Comment by t0ffel** [comment]
LGTM

**Comment by richm** [comment]
[merge]

**Comment by richm** [comment]
[merge]

**Pull request merged**
