### PR TITLE
Bug 1734083: Add jaeger index templates

### PR DESCRIPTION
**Pull request by pavolloffay**
Signed-off-by: Pavol Loffay <ploffay@redhat.com>

Backport of https://github.com/openshift/origin-aggregated-logging/pull/1712 to 4.1

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1734083
Jaeger jira: https://issues.jboss.org/browse/TRACING-629

### CODE REVIEW

**Comment by richm** [comment]
nack - see the master bz for instructions

**Comment by jwforres** [comment]
/hold
Adding a hold based on @richm's nack

**Comment by richm** [comment]
I rescind my nack, but I would like to know if jaeger needs kibana support - if not, this PR can be merged

**Comment by pavolloffay** [comment]
It's not needed here see https://github.com/openshift/origin-aggregated-logging/pull/1712#issuecomment-516299620

**Comment by pavolloffay** [comment]
it seems tests passed

**Comment by bparees** [comment]
@pavolloffay you need to clean up the BZ you are referencing, per the bot comment:
https://github.com/openshift/origin-aggregated-logging/pull/1711#issuecomment-516028466

**Comment by pavolloffay** [comment]
@bparees I have changed status from on QA to release pending but it didn't help.

**Comment by bparees** [comment]
/hold cancel

this will be reviewed by the patch manager on mon/tues for the next release.

**Comment by bparees** [comment]
@pavolloffay looks like it helped?  the bot says the BZ is valid now.

**Comment by pavolloffay** [comment]
@bparees can this be merged?

**Comment by bparees** [comment]
@pavolloffay this one needs the patch approver to approve it.  That process happens mon+tue.  i'm not sure why it was missed this week, i'll go ask.  hopefully next week.

**Comment by bparees** [comment]
@pavolloffay this should be reviewed by the patch manager next week and merge then.

**Comment by derekwaynecarr** [comment]
Approved for 4.1.z, dependent bug has been VERIFIED in development stream.

**Pull request merged**
