### PR TITLE
bug 1464020. bump kibana-proxy to fix memory switches

### PR DESCRIPTION
**Pull request by jcantrill**
This PR:
* bumps the kibana-proxy used to fix the memory switches used to run the proxy to underscores instead of dashes.

### CODE REVIEW

**Comment by jcantrill** [comment]
[test]

**Comment by richm** [comment]
[merge]

**Comment by jcantrill** [comment]
[merge][severity: bug]

**Comment by jcantrill** [comment]
1.4 fix in #523

**Pull request merged**
