### PR TITLE
Bug 1904380 - Forwarding logs to Kafka using Chained certificates fals with error "state=error: certificate verify failed (unable to get local issuer certificate)

### PR DESCRIPTION
**Pull request by syedriko**
### Description
Configuring log forwarding to Kafka over TLS and specifying a ca_bundle.crt with multiple concatenated PEM files results in the following error: 
2020-11-27 12:26:36 +0000 [warn]: Send exception occurred: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)

/cc @vimalk78 
/assign @jcantrill 

### Links
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1904380

### CODE REVIEW

**Comment by jcantrill** [comment]
Please create a patch fix like https://github.com/openshift/origin-aggregated-logging/pull/1993/files and prepare an upstream fix against https://github.com/fluent/fluent-plugin-kafka .  There was an upstream issue for this but I can not seem to find it

**Comment by syedriko** [comment]
>There was an upstream issue for this but I can not seem to find it

That would be https://github.com/fluent/fluent-plugin-kafka/issues/287

**Comment by syedriko** [comment]
@jcantrill lgtm this please

**Pull request merged**
