### PR TITLE
docs refactor

### PR DESCRIPTION
**Pull request by sosiouxme**
Move topics out of the top README so that it's just for developer info.
Moved to deployer README and then rearranged that some and added table of contents and some other things.

### CODE REVIEW

**Comment by sosiouxme** [comment]
@ewolinetz @richm there are some more updates to make but I thought I'd wait until after I get the fluentd configmap changes merged before describing them here.

**Comment by ewolinetz** [comment]
LGTM so far

**Comment by sosiouxme** [comment]
@ewolinetz I added the fluentd/throttle explanation. Comments welcome. I'm thinking to combine this PR into the fluentd one so they both go in at the same time.

**Comment by ewolinetz** [comment]
the fluentd changes look good; feel free to combine

**Comment by sosiouxme** [comment]
folded into https://github.com/openshift/origin-aggregated-logging/pull/195

**Pull request closed without merging**
