### PR TITLE
Enable SELinux labelling for the Docker daemon

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/cc @jcantrill

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
[test]

**Comment by jcantrill** [comment]
[test]

**Comment by jcantrill** [comment]
closes #401 .  Manually testing doesn't seem to show this issue and @stevekuznetsov says a package landed that may fix it.

**Comment by stevekuznetsov** [comment]
Added SELinux debugging into the job's post-hook, re[test]

**Comment by stevekuznetsov** [comment]
Doesn't seem to show up any AVC denials...

```
+ /usr/bin/vagrant ssh -c 'sudo ausearch -m avc'
<no matches>
```

**Comment by stevekuznetsov** [comment]
Turned off deprovisioning in the job only for this PR. re[test]

**Comment by stevekuznetsov** [comment]
@rhatdan we're seeing the `--selinux-enabled` flag on the Docker daemon fail these tests with permissions issues, but nothing is coming up with `sudo ausearch -m avc` post-facto. We're using the latest `docker` and `container-selinux` packages in the `oso-rhui-` repos. How do you suggest we continue to debug this to determine where the denials are happening?

**Comment by stevekuznetsov** [comment]
re[test]

**Comment by stevekuznetsov** [comment]
As per @rhatdan suggestions, now we run `sudo semodule -DB` to turn off don't-audit rules. We can confirm we have auditing on:

```
$ ps -eZ | grep audit
system_u:system_r:kernel_t:s0     152 ?        00:00:00 kauditd
system_u:system_r:auditd_t:s0     594 ?        00:00:00 auditd
```

We still see no AVC denials, though:
```
$ sudo ausearch -m avc
<no matches>
```

We do see the audit rules changing and the `ausearch` in the system journal, though:
```
$ sudo journalctl --all --no-pager --lines=all | grep -i AVC
May 05 16:40:17 ip-172-18-14-224.ec2.internal dbus-daemon[664]: dbus[664]: avc:  received policyload notice (seqno=2)
May 05 16:40:17 ip-172-18-14-224.ec2.internal dbus[664]: avc:  received policyload notice (seqno=2)
May 05 16:49:08 ip-172-18-14-224.ec2.internal sudo[10195]: ec2-user : TTY=unknown ; PWD=/data/src/github.com/openshift/origin ; USER=root ; COMMAND=/sbin/ausearch -m avc
```

Trying now a more broad `ausearch`: `-m AVC -m USER_AVC -m SELINUX_ERR`...

**Comment by stevekuznetsov** [comment]
re[test]

**Comment by stevekuznetsov** [comment]
OK, on a hunch I checked SELinux status...

```
$ sudo getenforce
Permissive
```

Maybe this is a problem in the `--selinux-enabled` code inside of Docker and not actually an AVC denial. Crucially, we are _still_ seeing no denials:

```
$ sudo ausearch -m AVC -m USER_AVC -m SELINUX_ERR 
<no matches>
```

Checking now to see what SELinux modules are even loaded...

**Comment by stevekuznetsov** [comment]
re[test]

**Comment by stevekuznetsov** [comment]
re[test]

**Comment by stevekuznetsov** [comment]
@rhatdan The extra debugging is not really making any more sense of the situation. To summarize the situation, we see errors in the OpenShift master logs like the following:

<details>
<summary> OpenShift Master Logs </summary>

```
2017-05-05 20:25:14.518332 I | etcdserver/api/v3rpc: grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 172.18.1.138:4001: getsockopt: connection refused"; Reconnecting to {172.18.1.138:4001 <nil>}
2017-05-05 20:25:14.518463 I | embed: peerTLS: cert = /tmp/openshift/origin-aggregated-logging/openshift.local.config/master/etcd.server.crt, key = /tmp/openshift/origin-aggregated-logging/openshift.local.config/master/etcd.server.key, ca = /tmp/openshift/origin-aggregated-logging/openshift.local.config/master/ca.crt, trusted-ca = , client-cert-auth = true
2017-05-05 20:25:14.519225 I | embed: listening for peers on https://172.18.1.138:7001
2017-05-05 20:25:14.519268 I | embed: listening for client requests on 172.18.1.138:4001
...
E0505 20:25:15.513694    4654 reflector.go:199] github.com/openshift/origin/vendor/k8s.io/kubernetes/plugin/pkg/admission/serviceaccount/admission.go:103: Failed to list *api.ServiceAccount: Get https://172.18.1.138:8443/api/v1/serviceaccounts?resourceVersion=0: dial tcp 172.18.1.138:8443: getsockopt: connection refused
...
2017-05-05 20:25:15.519673 W | etcdserver: another etcd process is running with the same data dir and holding the file lock.
2017-05-05 20:25:15.519691 W | etcdserver: waiting for it to exit before starting...
...
E0505 20:25:16.514145    4654 reflector.go:199] github.com/openshift/origin/vendor/k8s.io/kubernetes/plugin/pkg/admission/serviceaccount/admission.go:103: Failed to list *api.ServiceAccount: Get https://172.18.1.138:8443/api/v1/serviceaccounts?resourceVersion=0: dial tcp 172.18.1.138:8443: getsockopt: connection refused
...
2017-05-05 20:25:17.570875 I | etcdserver: name = openshift.local
2017-05-05 20:25:17.570886 I | etcdserver: data dir = /tmp/openshift/origin-aggregated-logging//etcd
2017-05-05 20:25:17.570891 I | etcdserver: member dir = /tmp/openshift/origin-aggregated-logging/etcd/member
2017-05-05 20:25:17.570894 I | etcdserver: heartbeat = 100ms
2017-05-05 20:25:17.570897 I | etcdserver: election = 1000ms
2017-05-05 20:25:17.570900 I | etcdserver: snapshot count = 10000
2017-05-05 20:25:17.570909 I | etcdserver: advertise client URLs = https://172.18.1.138:4001
2017-05-05 20:25:17.570913 I | etcdserver: initial advertise peer URLs = https://172.18.1.138:7001
2017-05-05 20:25:17.570922 I | etcdserver: initial cluster = openshift.local=https://172.18.1.138:7001
...
E0505 20:25:18.516209    4654 reflector.go:199] github.com/openshift/origin/vendor/k8s.io/kubernetes/plugin/pkg/admission/serviceaccount/admission.go:103: Failed to list *api.ServiceAccount: Get https://172.18.1.138:8443/api/v1/serviceaccounts?resourceVersion=0: dial tcp 172.18.1.138:8443: getsockopt: connection refused
...
2017-05-05 20:25:35.513261 I | etcdserver/api/v3rpc: grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: context deadline exceeded"; Reconnecting to {172.18.1.138:4001 <nil>}
```

</details>

When we run the Docker daemon *without* the `--selinux-enabled` flag, everything runs fine. As per your instructions, before the test begins we turn off `dontaudit` rules and ensure that `auditd` is running:

```
+ sudo semodule --disable_dontaudit --build
+ sudo ps -eZ
++ grep audit
system_u:system_r:kernel_t:s0     197 ?        00:00:00 kauditd
system_u:system_r:auditd_t:s0     580 ?        00:00:00 auditd
```

Once the tests fail, we grab the output of some debug statements:

<details>
<summary><code>sudo getenforce</code></summary>

```
+ sudo getenforce
Permissive
```

</details>

<details>
<summary><code>sudo ausearch -m AVC -m USER_AVC -m SELINUX_ERR</code></summary>

```
+ sudo ausearch -m AVC -m USER_AVC -m SELINUX_ERR
<no matches>
```

</details>

<details>
<summary><code>sudo journalctl --no-pager --all --lines=all | grep -i AVC</code></summary>

```
+ sudo journalctl --no-pager --all --lines=all
+ grep -i AVC
May 05 20:17:46 ip-172-18-1-138.ec2.internal dbus-daemon[660]: dbus[660]: avc:  received policyload notice (seqno=2)
May 05 20:17:46 ip-172-18-1-138.ec2.internal dbus[660]: avc:  received policyload notice (seqno=2)
May 05 20:27:32 ip-172-18-1-138.ec2.internal sudo[10313]: ec2-user : TTY=unknown ; PWD=/data/src/github.com/openshift/origin ; USER=root ; COMMAND=/sbin/ausearch -m AVC -m USER_AVC -m SELINUX_ERR

```

</details>

<details>
<summary><code>sudo semodule --list-modules=standard</code></summary>

```
+ sudo semodule --list-modules=standard
abrt	1.4.1
accountsd	1.1.0
acct	1.6.0
afs	1.9.0
aiccu	1.1.0
aide	1.7.1
ajaxterm	1.0.0
alsa	1.12.2
amanda	1.15.0
amtu	1.3.0
anaconda	1.7.0
antivirus	1.0.0
apache	2.7.2
apcupsd	1.9.0
apm	1.12.0
application	1.2.0
arpwatch	1.11.0
asterisk	1.12.1
auditadm	2.2.0
authconfig	1.0.0
authlogin	2.5.1
automount	1.14.1
avahi	1.14.1
awstats	1.5.0
bacula	1.2.0
base	(null)
bcfg2	1.1.0
bind	1.13.1
bitlbee	1.5.0
blkmapd	1.0.0
blueman	1.1.0
bluetooth	3.5.0
boinc	1.1.1
bootloader	1.14.0
brctl	1.7.0
brltty	1.0.0
bugzilla	1.1.0
bumblebee	1.0.0
cachefilesd	1.1.0
calamaris	1.8.0
callweaver	1.1.0
canna	1.12.0
ccs	1.6.0
cdrecord	2.6.0
certmaster	1.3.0
certmonger	1.2.0
certwatch	1.8.0
cfengine	1.1.0
cgdcbxd	1.0.0
cgroup	1.2.0
chrome	1.0.0
chronyd	1.2.0
cinder	1.0.0
cipe	1.6.0
clock	1.7.0
clogd	1.1.0
cloudform	1.0
cmirrord	1.1.0
cobbler	1.2.0
cockpit	1.0.0
collectd	1.0.0
colord	1.1.0
comsat	1.8.0
condor	1.0.1
conman	1.0.0
consolekit	1.9.0
container	1.0.0
couchdb	1.1.1
courier	1.14.0
cpucontrol	1.4.0
cpufreqselector	1.4.0
cpuplug	1.0.0
cron	2.6.3
ctdb	1.1.0
cups	1.16.2
cvs	1.10.2
cyphesis	1.3.0
cyrus	1.13.1
daemontools	1.3.0
dbadm	1.1.0
dbskk	1.6.0
dbus	1.19.0
dcc	1.12.0
ddclient	1.10.0
denyhosts	1.1.0
devicekit	1.3.1
dhcp	1.11.0
dictd	1.8.0
dirsrv	1.0.0
dirsrv-admin	1.0.0
dmesg	1.3.0
dmidecode	1.5.1
dnsmasq	1.10.0
dnssec	1.0.0
dovecot	1.16.1
drbd	1.1.0
dspam	1.1.0
entropyd	1.8.0
exim	1.6.1
fail2ban	1.5.0
fcoe	1.1.0
fetchmail	1.13.2
finger	1.10.0
firewalld	1.1.1
firewallgui	1.1.0
firstboot	1.13.0
fprintd	1.2.0
freeipmi	1.0.0
freqset	1.0.0
fstools	1.16.1
ftp	1.15.1
games	2.3.0
gdomap	1.0.1
geoclue	1.0.0
getty	1.10.0
git	1.3.2
gitosis	1.4.0
glance	1.1.0
glusterd	1.1.2
gnome	2.3.0
gpg	2.8.0
gpm	1.9.0
gpsd	1.2.0
gssproxy	1.0.0
guest	1.3.0
hddtemp	1.2.0
hostname	1.8.1
hsqldb	1.0.0
hwloc	1.0.0
hypervkvp	1.0.0
icecast	1.2.0
inetd	1.13.0
init	1.20.1
inn	1.11.0
iodine	1.1.0
iotop	1.0.0
ipa	1.0.0
ipmievd	1.0.0
ipsec	1.14.0
iptables	1.14.0
irc	2.3.1
irqbalance	1.6.0
iscsi	1.9.0
isns	1.0.0
jabber	1.10.0
jetty	1.0.0
jockey	1.0.0
journalctl	1.0.0
kdump	1.3.0
kdumpgui	1.2.0
keepalived	1.0.0
kerberos	1.12.0
keyboardd	1.1.0
keystone	1.1.0
kismet	1.7.0
kmscon	1.0
ksmtuned	1.1.1
ktalk	1.9.2
l2tp	1.1.0
ldap	1.11.1
libraries	2.10.0
likewise	1.3.0
linuxptp	1.0.0
lircd	1.2.0
livecd	1.3.0
lldpad	1.1.0
loadkeys	1.9.0
locallogin	1.12.0
lockdev	1.5.0
logadm	1.0.0
logging	1.20.1
logrotate	1.15.0
logwatch	1.12.2
lpd	1.14.0
lsm	1.0.0
lttng-tools	1.0.0
lvm	1.15.2
mailman	1.10.0
mailscanner	1.1.0
man2html	1.0.0
mandb	1.1.1
mcelog	1.2.0
mediawiki	1.0.0
memcached	1.3.1
milter	1.5.0
minidlna	0.1
minissdpd	1.0.0
mip6d	1.0.0
mirrormanager	1.0.0
miscfiles	1.11.0
mock	1.0.0
modemmanager	1.2.1
modutils	1.14.0
mojomojo	1.1.0
mon_statd	1.0.0
mongodb	1.1.0
motion	1.0.0
mount	1.16.1
mozilla	2.8.0
mpd	1.1.1
mplayer	2.5.0
mrtg	1.9.0
mta	2.7.3
munin	1.9.1
mysql	1.14.1
mythtv	1.0.0
nagios	1.13.0
namespace	1.0.0
ncftool	1.2.0
netlabel	1.3.0
netutils	1.12.1
networkmanager	1.15.2
ninfod	1.0.0
nis	1.12.0
nova	1.0.0
nscd	1.11.0
nsd	1.8.0
nslcd	1.4.1
ntop	1.10.0
ntp	1.11.0
numad	1.1.0
nut	1.3.0
nx	1.7.0
obex	1.0.0
oddjob	1.10.0
openct	1.6.1
opendnssec	1.0.0
openhpid	1.0.0
openshift	1.0.0
openshift-origin	1.0.0
opensm	1.0.0
openvpn	1.12.2
openvswitch	1.1.1
openwsman	1.0.0
oracleasm	1.0.0
osad	1.0.0
pads	1.1.0
passenger	1.1.1
pcmcia	1.7.0
pcp	1.0.0
pcscd	1.8.0
pegasus	1.9.0
permissivedomains	(null)
pesign	1.0.0
pingd	1.1.0
piranha	1.0.0
pkcs	1.0.1
pki	10.0.11
plymouthd	1.2.0
podsleuth	1.7.0
policykit	1.3.0
polipo	1.1.1
portmap	1.11.0
portreserve	1.4.0
postfix	1.15.1
postgresql	1.16.0
postgrey	1.9.0
ppp	1.14.0
prelink	1.11.0
prelude	1.4.0
privoxy	1.12.0
procmail	1.13.1
prosody	1.0.0
psad	1.1.0
ptchown	1.2.0
publicfile	1.2.0
pulseaudio	1.6.0
puppet	1.4.0
pwauth	1.0.0
qmail	1.6.1
qpid	1.1.0
quantum	1.1.0
quota	1.6.0
rabbitmq	1.0.2
radius	1.13.0
radvd	1.14.0
raid	1.13.1
rasdaemon	1.0.0
rdisc	1.8.0
readahead	1.13.0
realmd	1.1.0
redis	1.0.1
remotelogin	1.8.0
rhcs	1.2.1
rhev	1.0
rhgb	1.9.0
rhnsd	1.0.0
rhsmcertd	1.1.1
ricci	1.8.0
rkhunter	1.0
rlogin	1.11.3
rngd	1.1.0
roundup	1.8.0
rpc	1.15.1
rpcbind	1.6.1
rpm	1.16.0
rshd	1.8.1
rssh	2.3.0
rsync	1.13.0
rtas	1.0.0
rtkit	1.2.0
rwho	1.7.0
samba	1.16.3
sambagui	1.2.0
sandboxX	1.0.0
sanlock	1.1.0
sasl	1.15.1
sbd	1.0.0
sblim	1.1.0
screen	2.6.0
secadm	2.4.0
sectoolm	1.1.0
selinuxutil	1.17.2
sendmail	1.12.1
sensord	1.0.0
setrans	1.8.0
setroubleshoot	1.12.1
seunshare	1.1.0
sge	1.0.0
shorewall	1.4.0
slocate	1.12.2
slpd	1.1.0
smartmon	1.12.0
smokeping	1.2.0
smoltclient	1.2.0
smsd	1.0.0
snapper	1.0.0
snmp	1.14.0
snort	1.11.0
sosreport	1.3.1
soundserver	1.9.0
spamassassin	2.6.1
speech-dispatcher	1.0.0
squid	1.12.1
ssh	2.4.2
sssd	1.2.0
staff	2.4.0
stapserver	1.1.0
stunnel	1.11.0
su	1.12.0
sudo	1.10.0
svnserve	1.1.0
swift	1.0.0
sysadm	2.6.1
sysadm_secadm	1.0.0
sysnetwork	1.15.4
sysstat	1.8.0
systemd	1.0.0
targetd	1.0.0
tcpd	1.5.0
tcsd	1.1.1
telepathy	1.4.2
telnet	1.11.3
tftp	1.13.0
tgtd	1.3.1
thin	1.0
thumb	1.0.0
tmpreaper	1.7.1
tomcat	1.0.0
tor	1.9.0
tuned	1.2.0
tvtime	2.3.0
udev	1.16.2
ulogd	1.3.0
uml	2.3.0
unconfined	3.5.0
unconfineduser	1.0.0
unlabelednet	1.0.0
unprivuser	2.4.0
updfstab	1.6.0
usbmodules	1.3.0
usbmuxd	1.2.0
userdomain	4.9.1
userhelper	1.8.1
usermanage	1.19.0
usernetctl	1.7.0
uucp	1.13.0
uuidd	1.1.0
varnishd	1.2.0
vdagent	1.1.1
vhostmd	1.1.0
virt	1.5.0
vlock	1.2.0
vmtools	1.0.0
vmware	2.7.0
vnstatd	1.1.0
vpn	1.16.0
w3c	1.1.0
watchdog	1.8.0
wdmd	1.1.0
webadm	1.2.0
webalizer	1.13.0
wine	1.11.0
wireshark	2.4.0
xen	1.13.0
xguest	1.2.0
xserver	3.9.4
zabbix	1.6.0
zarafa	1.2.0
zebra	1.13.0
zoneminder	1.0.0
zosremote	1.2.0
```

</details>

<details>
<summary><code>sudo semodule --list-modules=full</code></summary>

```
+ sudo semodule --list-modules=full
200 container         pp         
100 abrt              pp         
100 accountsd         pp         
100 acct              pp         
100 afs               pp         
100 aiccu             pp         
100 aide              pp         
100 ajaxterm          pp         
100 alsa              pp         
100 amanda            pp         
100 amtu              pp         
100 anaconda          pp         
100 antivirus         pp         
100 apache            pp         
100 apcupsd           pp         
100 apm               pp         
100 application       pp         
100 arpwatch          pp         
100 asterisk          pp         
100 auditadm          pp         
100 authconfig        pp         
100 authlogin         pp         
100 automount         pp         
100 avahi             pp         
100 awstats           pp         
100 bacula            pp         
100 base              pp         
100 bcfg2             pp         
100 bind              pp         
100 bitlbee           pp         
100 blkmapd           pp         
100 blueman           pp         
100 bluetooth         pp         
100 boinc             pp         
100 bootloader        pp         
100 brctl             pp         
100 brltty            pp         
100 bugzilla          pp         
100 bumblebee         pp         
100 cachefilesd       pp         
100 calamaris         pp         
100 callweaver        pp         
100 canna             pp         
100 ccs               pp         
100 cdrecord          pp         
100 certmaster        pp         
100 certmonger        pp         
100 certwatch         pp         
100 cfengine          pp         
100 cgdcbxd           pp         
100 cgroup            pp         
100 chrome            pp         
100 chronyd           pp         
100 cinder            pp         
100 cipe              pp         
100 clock             pp         
100 clogd             pp         
100 cloudform         pp         
100 cmirrord          pp         
100 cobbler           pp         
100 cockpit           pp         
100 collectd          pp         
100 colord            pp         
100 comsat            pp         
100 condor            pp         
100 conman            pp         
100 consolekit        pp         
100 couchdb           pp         
100 courier           pp         
100 cpucontrol        pp         
100 cpufreqselector   pp         
100 cpuplug           pp         
100 cron              pp         
100 ctdb              pp         
100 cups              pp         
100 cvs               pp         
100 cyphesis          pp         
100 cyrus             pp         
100 daemontools       pp         
100 dbadm             pp         
100 dbskk             pp         
100 dbus              pp         
100 dcc               pp         
100 ddclient          pp         
100 denyhosts         pp         
100 devicekit         pp         
100 dhcp              pp         
100 dictd             pp         
100 dirsrv            pp         
100 dirsrv-admin      pp         
100 dmesg             pp         
100 dmidecode         pp         
100 dnsmasq           pp         
100 dnssec            pp         
100 docker            pp disabled
100 dovecot           pp         
100 drbd              pp         
100 dspam             pp         
100 entropyd          pp         
100 exim              pp         
100 fail2ban          pp         
100 fcoe              pp         
100 fetchmail         pp         
100 finger            pp         
100 firewalld         pp         
100 firewallgui       pp         
100 firstboot         pp         
100 fprintd           pp         
100 freeipmi          pp         
100 freqset           pp         
100 fstools           pp         
100 ftp               pp         
100 games             pp         
100 gdomap            pp         
100 gear              pp disabled
100 geoclue           pp         
100 getty             pp         
100 git               pp         
100 gitosis           pp         
100 glance            pp         
100 glusterd          pp         
100 gnome             pp         
100 gpg               pp         
100 gpm               pp         
100 gpsd              pp         
100 gssproxy          pp         
100 guest             pp         
100 hddtemp           pp         
100 hostname          pp         
100 hsqldb            pp         
100 hwloc             pp         
100 hypervkvp         pp         
100 icecast           pp         
100 inetd             pp         
100 init              pp         
100 inn               pp         
100 iodine            pp         
100 iotop             pp         
100 ipa               pp         
100 ipmievd           pp         
100 ipsec             pp         
100 iptables          pp         
100 irc               pp         
100 irqbalance        pp         
100 iscsi             pp         
100 isns              pp         
100 jabber            pp         
100 jetty             pp         
100 jockey            pp         
100 journalctl        pp         
100 kdump             pp         
100 kdumpgui          pp         
100 keepalived        pp         
100 kerberos          pp         
100 keyboardd         pp         
100 keystone          pp         
100 kismet            pp         
100 kmscon            pp         
100 ksmtuned          pp         
100 ktalk             pp         
100 l2tp              pp         
100 ldap              pp         
100 libraries         pp         
100 likewise          pp         
100 linuxptp          pp         
100 lircd             pp         
100 livecd            pp         
100 lldpad            pp         
100 loadkeys          pp         
100 locallogin        pp         
100 lockdev           pp         
100 logadm            pp         
100 logging           pp         
100 logrotate         pp         
100 logwatch          pp         
100 lpd               pp         
100 lsm               pp         
100 lttng-tools       pp         
100 lvm               pp         
100 mailman           pp         
100 mailscanner       pp         
100 man2html          pp         
100 mandb             pp         
100 mcelog            pp         
100 mediawiki         pp         
100 memcached         pp         
100 milter            pp         
100 minidlna          pp         
100 minissdpd         pp         
100 mip6d             pp         
100 mirrormanager     pp         
100 miscfiles         pp         
100 mock              pp         
100 modemmanager      pp         
100 modutils          pp         
100 mojomojo          pp         
100 mon_statd         pp         
100 mongodb           pp         
100 motion            pp         
100 mount             pp         
100 mozilla           pp         
100 mpd               pp         
100 mplayer           pp         
100 mrtg              pp         
100 mta               pp         
100 munin             pp         
100 mysql             pp         
100 mythtv            pp         
100 nagios            pp         
100 namespace         pp         
100 ncftool           pp         
100 netlabel          pp         
100 netutils          pp         
100 networkmanager    pp         
100 ninfod            pp         
100 nis               pp         
100 nova              pp         
100 nscd              pp         
100 nsd               pp         
100 nslcd             pp         
100 ntop              pp         
100 ntp               pp         
100 numad             pp         
100 nut               pp         
100 nx                pp         
100 obex              pp         
100 oddjob            pp         
100 openct            pp         
100 opendnssec        pp         
100 openhpid          pp         
100 openshift         pp         
100 openshift-origin  pp         
100 opensm            pp         
100 openvpn           pp         
100 openvswitch       pp         
100 openwsman         pp         
100 oracleasm         pp         
100 osad              pp         
100 pads              pp         
100 passenger         pp         
100 pcmcia            pp         
100 pcp               pp         
100 pcscd             pp         
100 pegasus           pp         
100 permissivedomains cil         
100 pesign            pp         
100 pingd             pp         
100 piranha           pp         
100 pkcs              pp         
100 pki               pp         
100 plymouthd         pp         
100 podsleuth         pp         
100 policykit         pp         
100 polipo            pp         
100 portmap           pp         
100 portreserve       pp         
100 postfix           pp         
100 postgresql        pp         
100 postgrey          pp         
100 ppp               pp         
100 prelink           pp         
100 prelude           pp         
100 privoxy           pp         
100 procmail          pp         
100 prosody           pp         
100 psad              pp         
100 ptchown           pp         
100 publicfile        pp         
100 pulseaudio        pp         
100 puppet            pp         
100 pwauth            pp         
100 qmail             pp         
100 qpid              pp         
100 quantum           pp         
100 quota             pp         
100 rabbitmq          pp         
100 radius            pp         
100 radvd             pp         
100 raid              pp         
100 rasdaemon         pp         
100 rdisc             pp         
100 readahead         pp         
100 realmd            pp         
100 redis             pp         
100 remotelogin       pp         
100 rhcs              pp         
100 rhev              pp         
100 rhgb              pp         
100 rhnsd             pp         
100 rhsmcertd         pp         
100 ricci             pp         
100 rkhunter          pp         
100 rlogin            pp         
100 rngd              pp         
100 roundup           pp         
100 rpc               pp         
100 rpcbind           pp         
100 rpm               pp         
100 rshd              pp         
100 rssh              pp         
100 rsync             pp         
100 rtas              pp         
100 rtkit             pp         
100 rwho              pp         
100 samba             pp         
100 sambagui          pp         
100 sandboxX          pp         
100 sanlock           pp         
100 sasl              pp         
100 sbd               pp         
100 sblim             pp         
100 screen            pp         
100 secadm            pp         
100 sectoolm          pp         
100 selinuxutil       pp         
100 sendmail          pp         
100 sensord           pp         
100 setrans           pp         
100 setroubleshoot    pp         
100 seunshare         pp         
100 sge               pp         
100 shorewall         pp         
100 slocate           pp         
100 slpd              pp         
100 smartmon          pp         
100 smokeping         pp         
100 smoltclient       pp         
100 smsd              pp         
100 snapper           pp         
100 snmp              pp         
100 snort             pp         
100 sosreport         pp         
100 soundserver       pp         
100 spamassassin      pp         
100 speech-dispatcher pp         
100 squid             pp         
100 ssh               pp         
100 sssd              pp         
100 staff             pp         
100 stapserver        pp         
100 stunnel           pp         
100 su                pp         
100 sudo              pp         
100 svnserve          pp         
100 swift             pp         
100 sysadm            pp         
100 sysadm_secadm     pp         
100 sysnetwork        pp         
100 sysstat           pp         
100 systemd           pp         
100 targetd           pp         
100 tcpd              pp         
100 tcsd              pp         
100 telepathy         pp         
100 telnet            pp         
100 tftp              pp         
100 tgtd              pp         
100 thin              pp         
100 thumb             pp         
100 tmpreaper         pp         
100 tomcat            pp         
100 tor               pp         
100 tuned             pp         
100 tvtime            pp         
100 udev              pp         
100 ulogd             pp         
100 uml               pp         
100 unconfined        pp         
100 unconfineduser    pp         
100 unlabelednet      pp         
100 unprivuser        pp         
100 updfstab          pp         
100 usbmodules        pp         
100 usbmuxd           pp         
100 userdomain        pp         
100 userhelper        pp         
100 usermanage        pp         
100 usernetctl        pp         
100 uucp              pp         
100 uuidd             pp         
100 varnishd          pp         
100 vdagent           pp         
100 vhostmd           pp         
100 virt              pp         
100 vlock             pp         
100 vmtools           pp         
100 vmware            pp         
100 vnstatd           pp         
100 vpn               pp         
100 w3c               pp         
100 watchdog          pp         
100 wdmd              pp         
100 webadm            pp         
100 webalizer         pp         
100 wine              pp         
100 wireshark         pp         
100 xen               pp         
100 xguest            pp         
100 xserver           pp         
100 zabbix            pp         
100 zarafa            pp         
100 zebra             pp         
100 zoneminder        pp         
100 zosremote         pp         
```

</details>

<details>
<summary><code>sudo ausearch -m ALL</code></summary>

```
+ sudo ausearch -m ALL
<no matches>
```

</details>

<details>
<summary><code>sudo journalctl --unit docker.service --no-pager --all --lines=all</code></summary>

```
+ sudo journalctl --unit docker.service --no-pager --all --lines=all
-- Logs begin at Fri 2017-05-05 20:08:20 EDT, end at Fri 2017-05-05 20:27:34 EDT. --
May 05 20:09:55 ip-172-18-1-138.ec2.internal systemd[1]: Starting Docker Application Container Engine...
May 05 20:10:05 ip-172-18-1-138.ec2.internal dockerd-current[2237]: time="2017-05-05T20:10:05.791771395-04:00" level=info msg="libcontainerd: new containerd process, pid: 2313"
May 05 20:10:32 ip-172-18-1-138.ec2.internal dockerd-current[2237]: time="2017-05-05T20:10:32.877198762-04:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
May 05 20:10:32 ip-172-18-1-138.ec2.internal dockerd-current[2237]: time="2017-05-05T20:10:32.878403552-04:00" level=warning msg="mountpoint for pids not found"
May 05 20:10:32 ip-172-18-1-138.ec2.internal dockerd-current[2237]: time="2017-05-05T20:10:32.878838769-04:00" level=info msg="Loading containers: start."
May 05 20:10:34 ip-172-18-1-138.ec2.internal dockerd-current[2237]: ..time="2017-05-05T20:10:34.037150527-04:00" level=warning msg="Running modprobe bridge br_netfilter failed with message: modprobe: WARNING: Module br_netfilter not found.\ninsmod /lib/modules/3.10.0-327.22.2.el7.x86_64/kernel/net/llc/llc.ko \ninsmod /lib/modules/3.10.0-327.22.2.el7.x86_64/kernel/net/802/stp.ko \ninsmod /lib/modules/3.10.0-327.22.2.el7.x86_64/kernel/net/bridge/bridge.ko \n, error: exit status 1"
May 05 20:10:34 ip-172-18-1-138.ec2.internal dockerd-current[2237]: time="2017-05-05T20:10:34.560662890-04:00" level=info msg="Firewalld running: false"
May 05 20:10:35 ip-172-18-1-138.ec2.internal dockerd-current[2237]: time="2017-05-05T20:10:35.114477265-04:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
May 05 20:10:35 ip-172-18-1-138.ec2.internal dockerd-current[2237]: time="2017-05-05T20:10:35.149622123-04:00" level=info msg="Loading containers: done."
May 05 20:10:35 ip-172-18-1-138.ec2.internal dockerd-current[2237]: time="2017-05-05T20:10:35.149713241-04:00" level=info msg="Daemon has completed initialization"
May 05 20:10:35 ip-172-18-1-138.ec2.internal dockerd-current[2237]: time="2017-05-05T20:10:35.149729111-04:00" level=info msg="Docker daemon" commit="3a094bd/1.12.6" graphdriver=devicemapper version=1.12.6
May 05 20:10:35 ip-172-18-1-138.ec2.internal dockerd-current[2237]: time="2017-05-05T20:10:35.154655944-04:00" level=info msg="API listen on /var/run/docker.sock"
May 05 20:10:35 ip-172-18-1-138.ec2.internal systemd[1]: Started Docker Application Container Engine.
May 05 20:11:58 ip-172-18-1-138.ec2.internal dockerd-current[2237]: time="2017-05-05T20:11:58.390946651-04:00" level=info msg="{Action=create, Username=ec2-user, LoginUID=1000, PID=3452}"
May 05 20:13:18 ip-172-18-1-138.ec2.internal dockerd-current[2237]: time="2017-05-05T20:13:18.829104320-04:00" level=info msg="{Action=create, Username=ec2-user, LoginUID=1000, PID=3581}"
May 05 20:13:22 ip-172-18-1-138.ec2.internal dockerd-current[2237]: time="2017-05-05T20:13:22.191795836-04:00" level=info msg="{Action=create, Username=ec2-user, LoginUID=1000, PID=3621}"
May 05 20:14:25 ip-172-18-1-138.ec2.internal dockerd-current[2237]: time="2017-05-05T20:14:25.896580860-04:00" level=info msg="{Action=create, Username=ec2-user, LoginUID=1000, PID=3857}"
May 05 20:15:10 ip-172-18-1-138.ec2.internal dockerd-current[2237]: time="2017-05-05T20:15:10.466949560-04:00" level=info msg="{Action=create, Username=ec2-user, LoginUID=1000, PID=3999}"
May 05 20:15:23 ip-172-18-1-138.ec2.internal dockerd-current[2237]: time="2017-05-05T20:15:23.256263764-04:00" level=info msg="{Action=create, Username=ec2-user, LoginUID=1000, PID=4082}"
```

</details>

Although it really does seem that there are no audit logs being recorded since `sudo ausearch -m ALL` returns nothing. There are comments about the context deadline being exceeded in the `etcd` logs, so I would almost want to investigate this as a cert issue except for the fact that we can 100% reproduce this error with the `--selinux-enabled` flag on the Docker daemon and 100% reproduce not having it without the flag.

**Comment by rhatdan** [comment]
If SELinux is in permissive mode, then most likely this is not a permission denied issue, and we are not seeing these issues in the AVC or the docker logs.

Turn the dontaudit rules back on by executing

semodule -B

**Comment by rhatdan** [comment]
@stevekuznetsov Can I get access to this machine?

**Comment by stevekuznetsov** [comment]
We have a reproducer for this so I can bring a machine up for you this morning @rhatdan

**Comment by stevekuznetsov** [comment]
Turned off CI machine reaper for this PR, re[test]

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
doesn't look like a known flake but [test] again anyway to see

**Comment by stevekuznetsov** [comment]
@richm the issue in the tests for this one are specifically from the patch in this PR.

**Comment by richm** [comment]
What's up with this PR?  Any progress?

**Comment by stevekuznetsov** [comment]
Lots of head-scratching. Should try again on the newer job as well.

**Comment by stevekuznetsov** [comment]
I'm not convinced it's worth the effort to continue digging -- no logs or anything to work off of is frustrating.

**Pull request closed without merging**
