### PR TITLE
[3.10] More readable format for curator logs

### PR DESCRIPTION
**Pull request by josefkarasek**

### CODE REVIEW

**Comment by richm** [comment]
@josefkarasek not sure how to retest failed travis builds - try making a slight change to your PR and push again

**Comment by jcantrill** [comment]
@richm think its worth the effort to bring this into 4.2?

**Comment by richm** [comment]
> @richm think its worth the effort to bring this into 4.2?

sure - seems pretty simple

**Comment by dobbymoodge** [comment]
Testing to see if Jenkins tests are fixed
/retest logging

**Comment by dobbymoodge** [comment]
Testing to see if Jenkins tests are fixed
/test logging

**Pull request merged**
