### PR TITLE
Add -X HEAD option

### LINKED ISSUE #363: Missing curl "-X HEAD" causing test fail in Elasticsearch run script
I think we are missing `-X HEAD` options for `curl` command here in [`run.sh`](https://github.com/openshift/origin-aggregated-logging/blob/cc6573b5744b4a06b37324d9259f2006c8f59c10/elasticsearch/run.sh#L78-L84).

This leads to failing the `test` command, like this:
````
# assuming "set -x"

++ curl -s --max-time 1 -w '%{response_code}' http://localhost:9200
+ response_code='{
  "name" : "USAgent",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "-_6fCh0mSeyiGqjpacfZ0Q",
  "version" : {
    "number" : "2.4.4",
    "build_hash" : "fcbb46dfd45562a9cf00c604b30849a6dec6b017",
    "build_timestamp" : "2017-01-03T11:33:16Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.2"
  },
  "tagline" : "You Know, for Search"
}
200'
+ test '{' '"name"' : '"USAgent",' '"cluster_name"' : '"elasticsearch",' '"cluster_uuid"' : '"-_6fCh0mSeyiGqjpacfZ0Q",' '"version"' : '{' '"number"' : '"2.4.4",' '"build_hash"' : '"fcbb46dfd45562a9cf00c604b30849a6dec6b017",' '"build_timestamp"' : '"2017-01-03T11:33:16Z",' '"build_snapshot"' : false, '"lucene_version"' : '"5.5.2"' '},' '"tagline"' : '"You' Know, for 'Search"' '}' 200 '!=' 200
./start_elasticsearch.sh: line 14: test: too many arguments
````

Notice the `test: too many arguments` in the end. (Ignore the misleading line number, this is relevant to different test script).

### PR DESCRIPTION
**Pull request by lukas-vlcek**
Closes #363

### CODE REVIEW

**Comment by lukas-vlcek** [comment]
Do we want to back-port this?

**Comment by jcantrill** [comment]
What are the cons to not backporting?  We are unlikey to get this into an earlier release unless we can demonstrate some blocker or regression issue

**Comment by lukas-vlcek** [comment]
@jcantrill If I read the code correctly then it seems that if the `test` part of the condition fails then it does not impact the flow much (we are probably lucky). 😄 
This would explain why we haven't run into this issue before.

**Comment by lukas-vlcek** [comment]
Maybe if @richm can throw a fresh pair of eyes on this as well...

**Comment by richm** [comment]
patch looks good to me, will leave it up to @jcantrill if he wants to back port it or not - looks pretty safe to backport

**Comment by richm** [comment]
[merge]

**Comment by jcantrill** [comment]
Skip backport unless some issues arise.

**Comment by richm** [comment]
[merge]

**Comment by richm** [comment]
build is taking over an hour????
[test]

**Comment by richm** [comment]
[merge]

**Pull request merged**
