### PR TITLE
Combine production & CI Dockerfiles

### PR DESCRIPTION
**Pull request by jupierce**

### CODE REVIEW

**Comment by jcantrill** [comment]
cc @vimalk78 @ewolinetz

**Comment by vimalk78** [comment]
does this mean we should use same base images in midstreams/cpaas?
@jupierce we are using following base images 
```
ubi8:8-released 
openshift/ose-base:ubi8
openshift/golang-builder:1.14 
openshift/ose-base:ubi8.ruby.25
openshift/ose-base:ubi8.python.36
openshift/ose-base:ubi8.nodejs.10
```

**Comment by jupierce** [comment]
@vimalk78 The goal of this PR is to make you be able to use the same Dockerfiles in CI as you do for your downstream builds. This is a requirement of our migration to RHEL8. 
CI will replace these FROM statements dynamically using your ci-operator configuration data (which I'm preparing [here](https://github.com/openshift/release/pull/10886)). I was using images like `registry.svc.ci.openshift.org/ocp/builder:ubi8.python.36` for my testing to ensure the Dockerfiles would work in CI. Now that I have them building, you are free to replace them as you see fit.

**Comment by jupierce** [comment]
Still a little more debugging to do.
/hold

**Comment by jupierce** [comment]
Per Jeff, probably blocked by https://github.com/openshift/cluster-logging-operator/pull/657

**Pull request merged**
