### PR TITLE
CI support for 4.3

### PR DESCRIPTION
**Pull request by richm**

### CODE REVIEW

**Comment by richm** [comment]
I think this may also require https://github.com/openshift/cluster-logging-operator/pull/245 to merge and have a new clo image built in api.ci

**Comment by richm** [comment]
/hold
until clo https://github.com/openshift/cluster-logging-operator/pull/245 is merged and built, everything is broken - so no sense rosiebot spamming us

**Comment by richm** [comment]
/retest
eo change merged - let's see if this unblocks ci

**Comment by richm** [comment]
/retest
multi-tenancy flake

**Comment by richm** [comment]
/retest
multi-tenancy flake

**Comment by richm** [comment]
finally passed - please review

**Comment by nhosoi** [comment]
/lgtm
(;_;)

**Pull request merged**
