### PR TITLE
bug 1437952. unmount /var/lib/docker/container/*/shm to allow pods to…

### PR DESCRIPTION
**Pull request by jcantrill**
… terminate

### CODE REVIEW

**Comment by jcantrill** [comment]
[test] .... does it work?

**Comment by richm** [comment]
Looks like the umount didn't work: https://ci.openshift.redhat.com/jenkins/job/test-origin-aggregated-logging/1437/s3/download/logs/container-logging-fluentd-92gd9-fluentd-elasticsearch.log
```
umounts of dead containers will fail. Ignoring...
umount: /var/lib/docker/containers/081d6df7abb9922675316deaa240734090b292cb0fb77816a631afcae4db5265/shm: not mounted
umount: /var/lib/docker/containers/27b44a95e084287bde7c5f4213c5c10b447c65adedcf8d7b2f2925afa8cd394c/shm: not mounted
umount: /var/lib/docker/containers/4f9c110af96d167196c7bf41ccdcc070a2bdf2665c1dcc5665eea69d59038053/shm: not mounted
umount: /var/lib/docker/containers/50b4dea459fde5643a04b7e414ff761cd5a52fb6b1050f2bbd8a4be5e971316a/shm: not mounted
umount: /var/lib/docker/containers/54b9301c99645130c820c50cbe95651ffa3c9b4feef351850461d424d8484bb7/shm: not mounted
umount: /var/lib/docker/containers/768ea024903af65c30374c9f1f14df218b021d877f79e5387789d16d5631e062/shm: not mounted
umount: /var/lib/docker/containers/97fb1e2de5609a030544b287f352d53c566e935cd855bf46179db0fdcf564346/shm: not mounted
umount: /var/lib/docker/containers/a926d93995d4df5264b9819116bfad4c41ba9798418565345461cbb870e8db48/shm: not mounted
umount: /var/lib/docker/containers/c005b2f86a2bf82a54346cac63ceb34c782332dd2c1478393b2211d140f7bf33/shm: not mounted
umount: /var/lib/docker/containers/dc55e1469c390232d8521cbb306d9162b7c198d2d7270273e888f05f8d70fb36/shm: not mounted
umount: /var/lib/docker/containers/df7a0c023d8a894add0428b2b1f854390e39cb6c3a2dfc68ef8167245c47ed69/shm: not mounted
umount: /var/lib/docker/containers/e69a2be29c12d115b98a964facf5ef74a2b2f74a8e0bbc3a7e3fa2580a97c31d/shm: not mounted
2017-05-18 17:14:04 -0400 [info]: reading config file path="/etc/fluent/fluent.conf"
```

The test failed because the project.logging.* log record could not be found, although the .operations.* log record was found, which is strange:
```
failed - wait_for_fluentd_to_catch_up: not found 1 record project logging for 01017df3-1af9-441d-95cb-08ffaa1b4298 after 600 seconds
Checking journal for 01017df3-1af9-441d-95cb-08ffaa1b4298...
May 18 17:14:41 ip-172-18-7-200.ec2.internal dockerd-current[4497]: {"type":"response","@timestamp":"2017-05-18T21:14:41Z","tags":[],"pid":1,"method":"get","statusCode":404,"req":{"url":"/01017df3-1af9-441d-95cb-08ffaa1b4298","method":"get","headers":{"user-agent":"curl/7.29.0","host":"localhost:5601","accept":"*/*"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1"},"res":{"statusCode":404,"responseTime":17,"contentLength":9},"message":"GET /01017df3-1af9-441d-95cb-08ffaa1b4298 404 17ms - 9.0B"}
Found 01017df3-1af9-441d-95cb-08ffaa1b4298 in journal
good - wait_for_fluentd_to_catch_up: found 1 record project .operations for 0d8d2c46-5bf3-4caa-a342-73a738da3df1
```

**Comment by jcantrill** [comment]
@richm I'm going to try and run [test] again though I don't know if the CI for this works.  I'm not concerned about the umount failures since I believe they to be immaterial and thus the reason for the warning messages.

**Comment by jcantrill** [comment]
closing as this will be resolved in #460

**Pull request closed without merging**
