### PR TITLE
[WIP]  debugging CI-tests for PR/884

### PR DESCRIPTION
**Pull request by nhosoi**

### CODE REVIEW

**Comment by richm** [comment]
. . . and of course, once debugging is added, the problem goes away . . .

**Comment by wozniakjan** [comment]
sometimes it works even without the debugging code:
- https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_aggregated_logging_ansible_json_file_debugging/3
- https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_aggregated_logging_ansible_json_file/777

But today it looks like we have another issue, docker device mapper probably lacks space
```
[openshift/origin-logging-kibana] --> Committing changes to openshift/origin-logging-kibana:f677e1d ...
[openshift/origin-logging-kibana] unable to commit build container: API error (500): {"message":"devmapper: Thin Pool has 2017 free data blocks which is less than minimum required 2128 free data blocks. Create more free space in thin pool or use dm.min_free_space option to change behavior"}
```
- https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_origin-aggregated-logging/883/test_pull_request_origin_aggregated_logging_ansible/1392/
- https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_origin-aggregated-logging/889/test_pull_request_origin_aggregated_logging_ansible/1391/

**Comment by richm** [comment]
I'm still seeing namespace `openshift` showing up in `project.*` indices some of the tests.
Please resubmit this PR without the `tests: initial version of upgrade tests` commit so we can trace which test(s) are adding these records.

**Comment by richm** [comment]
hmm - even after the very first test, there is bad data:
```
/data/src/github.com/openshift/origin-aggregated-logging/test/access_control.sh -- DEBUGGING project.openshift index -- {"count":5,"_shards":{"total":8,"successful":8,"failed":0}}
[INFO] Logging test suite test-access-control succeeded at Sun Jan 14 07:21:52 UTC 2018
```
so it isn't the tests that is adding the data - it is the normal operation of fluentd, and it doesn't appear to have anything to do with mux.

I suspect it is fluentd itself - maybe a bug - fluentd assumes records for namespace `openshift` should be tagged with `**_openshift_**`, and anything with a tag like `**_openshift_**` is redirected to the `.operations` index - https://github.com/openshift/origin-aggregated-logging/blob/master/fluentd/configs.d/filter-post-z-retag-two.conf#L7

Maybe the records being read from json-file for the `openshift` namespace are not being tagged properly with a tag matching `**_openshift_**`?

Please add the DEBUGGING check to entrypoint.sh - https://github.com/openshift/origin-aggregated-logging/blob/master/hack/testing/entrypoint.sh#L135 - just before running each `check` script - you'll also have to add some code to get the es pod.

Also change the DEBUGGING to do a `_search` instead of a `_count` so we can see exactly what other data there is and which indices are being used.

**Comment by nhosoi** [comment]
It looks these errors are indexed to project.openshift-web-console.* from the beginning if these errors occur.  (I'd think not always.)
```
"message":"I0116 00:28:10.701948 1 serve.go:89] Serving securely on 0.0.0.0:8443\n","level":"err"
"message":"W0116 00:28:10.497013 1 start.go:92] Warning: config.metricsPublicURL: Invalid value: \"\": required to view cluster metrics in the console, web console start will continue.\n","level":"err"
```
It looks openshift-web-console should have waited waited for other components to start, but it sometimes does not?

```
[INFO] Logging test suite check-EFK-running succeeded at Tue Jan 16 00:39:00 UTC 2018
No resources found.
Pre /data/src/github.com/openshift/origin-aggregated-logging/hack/testing/check-logs.sh -- DEBUGGING project.openshift index -- 
{"took":23,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":
{"total":5,"max_score":0.40883923,"hits":
[{"_index":"project.openshift-web-console.0e9d2d78-fa54-11e7-bdc6-0e3f0958da0e.2018.01.16","_type":"com.redhat.viaq.common","_id":"AWD8Zk_yVsgssvaHAUzl","_score":0.40883923,"_source":{"docker":{"container_id":"b803559a2ccc3f2626d8eb11bfc12912a68abbe400ac9160281818587fce5446"},"kubernetes":{"container_name":"webconsole","namespace_name":"openshift-web-console","pod_name":"webconsole-b6d44f866-qsgld","pod_id":"10b2126c-fa54-11e7-bdc6-0e3f0958da0e","labels":{"pod-template-hash":"628009422","webconsole":"true"},"host":"ip-172-18-13-70.ec2.internal","master_url":"https://kubernetes.default.svc.cluster.local","namespace_id":"0e9d2d78-fa54-11e7-bdc6-0e3f0958da0e"},"message":"W0116 00:28:10.495287 1 start.go:92] Warning: config.loggingPublicURL: Invalid value: \"\": required to view aggregated container logs in the console, web console start will continue.\n","level":"err","hostname":"ip-172-18-13-70.ec2.internal","pipeline_metadata":{"collector":{"ipaddr4":"10.128.0.24","ipaddr6":"fe80::602d:90ff:feed:6b5","inputname":"fluent-plugin-systemd","name":"fluentd","received_at":"2018-01-16T00:36:11.114347+00:00","version":"0.12.42 1.6.0"}},"@timestamp":"2018-01-16T00:28:10.497309+00:00"}},
{"_index":"project.openshift-web-console.0e9d2d78-fa54-11e7-bdc6-0e3f0958da0e.2018.01.16","_type":"com.redhat.viaq.common","_id":"AWD8Zk_yVsgssvaHAUzm","_score":0.40883923,"_source":{"docker":{"container_id":"b803559a2ccc3f2626d8eb11bfc12912a68abbe400ac9160281818587fce5446"},"kubernetes":{"container_name":"webconsole","namespace_name":"openshift-web-console","pod_name":"webconsole-b6d44f866-qsgld","pod_id":"10b2126c-fa54-11e7-bdc6-0e3f0958da0e","labels":{"pod-template-hash":"628009422","webconsole":"true"},"host":"ip-172-18-13-70.ec2.internal","master_url":"https://kubernetes.default.svc.cluster.local","namespace_id":"0e9d2d78-fa54-11e7-bdc6-0e3f0958da0e"},"message":"W0116 00:28:10.497013 1 start.go:92] Warning: config.metricsPublicURL: Invalid value: \"\": required to view cluster metrics in the console, web console start will continue.\n","level":"err","hostname":"ip-172-18-13-70.ec2.internal","pipeline_metadata":{"collector":{"ipaddr4":"10.128.0.24","ipaddr6":"fe80::602d:90ff:feed:6b5","inputname":"fluent-plugin-systemd","name":"fluentd","received_at":"2018-01-16T00:36:11.115131+00:00","version":"0.12.42 1.6.0"}},"@timestamp":"2018-01-16T00:28:10.497377+00:00"}},
{"_index":"project.openshift-web-console.0e9d2d78-fa54-11e7-bdc6-0e3f0958da0e.2018.01.16","_type":"com.redhat.viaq.common","_id":"AWD8Zk_yVsgssvaHAUzn","_score":0.40883923,"_source":{"docker":{"container_id":"b803559a2ccc3f2626d8eb11bfc12912a68abbe400ac9160281818587fce5446"},"kubernetes":{"container_name":"webconsole","namespace_name":"openshift-web-console","pod_name":"webconsole-b6d44f866-qsgld","pod_id":"10b2126c-fa54-11e7-bdc6-0e3f0958da0e","labels":{"pod-template-hash":"628009422","webconsole":"true"},"host":"ip-172-18-13-70.ec2.internal","master_url":"https://kubernetes.default.svc.cluster.local","namespace_id":"0e9d2d78-fa54-11e7-bdc6-0e3f0958da0e"},"message":"I0116 00:28:10.701948 1 serve.go:89] Serving securely on 0.0.0.0:8443\n","level":"err","hostname":"ip-172-18-13-70.ec2.internal","pipeline_metadata":{"collector":{"ipaddr4":"10.128.0.24","ipaddr6":"fe80::602d:90ff:feed:6b5","inputname":"fluent-plugin-systemd","name":"fluentd","received_at":"2018-01-16T00:36:11.115786+00:00","version":"0.12.42 1.6.0"}},"@timestamp":"2018-01-16T00:28:10.702201+00:00"}},
{"_index":"project.openshift-web-console.0e9d2d78-fa54-11e7-bdc6-0e3f0958da0e.2018.01.16","_type":"com.redhat.viaq.common","_id":"AWD8ZlSlVsgssvaHAVlR","_score":0.40883923,"_source":{"docker":{"container_id":"ae87b3d4f33cb05a6dbd1eceaed39b778ecca94f7d5103089c36926bb51f9652"},"kubernetes":{"container_name":"webconsole","namespace_name":"openshift-web-console","pod_name":"webconsole-bf764fb8f-xm2sr","pod_id":"5933a9fc-fa55-11e7-bdc6-0e3f0958da0e","labels":{"pod-template-hash":"693209649","webconsole":"true"},"host":"ip-172-18-13-70.ec2.internal","master_url":"https://kubernetes.default.svc.cluster.local","namespace_id":"0e9d2d78-fa54-11e7-bdc6-0e3f0958da0e"},"message":"W0116 00:36:59.004587 1 start.go:92] Warning: config.metricsPublicURL: Invalid value: \"\": required to view cluster metrics in the console, web console start will continue.\n","level":"err","hostname":"ip-172-18-13-70.ec2.internal","pipeline_metadata":{"collector":{"ipaddr4":"10.128.0.24","ipaddr6":"fe80::602d:90ff:feed:6b5","inputname":"fluent-plugin-systemd","name":"fluentd","received_at":"2018-01-16T00:37:14.434384+00:00","version":"0.12.42 1.6.0"}},"@timestamp":"2018-01-16T00:36:59.008111+00:00"}},
{"_index":"project.openshift-web-console.0e9d2d78-fa54-11e7-bdc6-0e3f0958da0e.2018.01.16","_type":"com.redhat.viaq.common","_id":"AWD8ZlSlVsgssvaHAVlS","_score":0.40883923,"_source":{"docker":{"container_id":"ae87b3d4f33cb05a6dbd1eceaed39b778ecca94f7d5103089c36926bb51f9652"},"kubernetes":{"container_name":"webconsole","namespace_name":"openshift-web-console","pod_name":"webconsole-bf764fb8f-xm2sr","pod_id":"5933a9fc-fa55-11e7-bdc6-0e3f0958da0e","labels":{"pod-template-hash":"693209649","webconsole":"true"},"host":"ip-172-18-13-70.ec2.internal","master_url":"https://kubernetes.default.svc.cluster.local","namespace_id":"0e9d2d78-fa54-11e7-bdc6-0e3f0958da0e"},"message":"I0116 00:36:59.379191 1 serve.go:89] Serving securely on 0.0.0.0:8443\n","level":"err","hostname":"ip-172-18-13-70.ec2.internal","pipeline_metadata":{"collector":{"ipaddr4":"10.128.0.24","ipaddr6":"fe80::602d:90ff:feed:6b5","inputname":"fluent-plugin-systemd","name":"fluentd","received_at":"2018-01-16T00:37:14.435264+00:00","version":"0.12.42 1.6.0"}},"@timestamp":"2018-01-16T00:36:59.379447+00:00"}}]
}}
```

**Comment by nhosoi** [comment]
A related bug: Bug 1534878 - [RFE] Collect openshift-web-console logs into .operations index
@richm, until it's fixed, CI-test should treat project.openshift-web-console as an exception?

**Comment by richm** [comment]
> A related bug: Bug 1534878 - [RFE] Collect openshift-web-console logs into .operations index
@richm, until it's fixed, CI-test should treat project.openshift-web-console as an exception?

yes - let's allow project.openshift-web-console for now

**Comment by richm** [comment]
@lukas-vlcek @portante this is another symptom of the problem that es doesn't seem to be honoring the setting not to analyze fields.  The field `kubernetes.namespace_name` is defined as a keyword/unanalyzed for exact matches.  So how is it possible that this search:

https://github.com/openshift/origin-aggregated-logging/pull/891/commits/f04aeb473aebfed45f8d89264cd36cd240d7f372
```
 +        qs='{"query":{"term":{"kubernetes.namespace_name":"'"openshift"'"}}}' 
```
returns these results?
```
[{"_index":"project.openshift-web-console.0e9d2d78-fa54-11e7-bdc6-0e3f0958da0e.2018.01.16","_type":"com.redhat.viaq.common","_id":"AWD8Zk_yVsgssvaHAUzl","_score":0.40883923,"_source":{"docker":{"container_id":"b803559a2ccc3f2626d8eb11bfc12912a68abbe400ac9160281818587fce5446"},"kubernetes":{"container_name":"webconsole","namespace_name":"openshift-web-console","pod_name":"webconsole-b6d44f866-qsgld","pod_id":"10b2126c-fa54-11e7-bdc6-0e3f0958da0e","labels":{"pod-template-hash":"628009422","webconsole":"true"},"host":"ip-172-18-13-70.ec2.internal","master_url":"https://kubernetes.default.svc.cluster.local","namespace_id":"0e9d2d78-fa54-11e7-bdc6-0e3f0958da0e"},"message":"W0116 00:28:10.495287 1 start.go:92] Warning: config.loggingPublicURL: Invalid value: \"\": required to view aggregated container logs in the console, web console start will continue.\n","level":"err","hostname":"ip-172-18-13-70.ec2.internal","pipeline_metadata":{"collector":{"ipaddr4":"10.128.0.24","ipaddr6":"fe80::602d:90ff:feed:6b5","inputname":"fluent-plugin-systemd","name":"fluentd","received_at":"2018-01-16T00:36:11.114347+00:00","version":"0.12.42 1.6.0"}},"@timestamp":"2018-01-16T00:28:10.497309+00:00"}},
```

for emphasis
```
"kubernetes":{"container_name":"webconsole","namespace_name":"openshift-web-console",...}
```
?

**Comment by nhosoi** [comment]
I've pushed this patch to this pr for testing.
    Until this bug is fixed, skip "openshift-web-console".
    Bug 1534878 - [RFE] Collect openshift-web-console logs into .operations index

**Comment by lukas-vlcek** [comment]
@richm interestingly, I have just hit https://github.com/ViaQ/elasticsearch-templates/issues/78
I am not sure why it should be `not_analyzed` while the type is set to `string` and there is also the `.raw` field. However, in the end all the released mappings specify `not_analyzed` for `kubernetes.container_name` atm (probably due to [defaults like this one](https://github.com/ViaQ/elasticsearch-templates/blob/master/namespaces/_default_.yml#L6)).

Anyway, shouldn't you be using `kubernetes.container_name.raw` to make it explicit you are after exact match?

**Comment by richm** [comment]
> Anyway, shouldn't you be using kubernetes.container_name.raw to make it explicit you are after exact match?

IMO it should be the other way around - almost all of the fields are keywords and should be not_analyzed by default.  Then, for certain fields that we will want to support "fuzzy" searching on (like the `message` field), we can add a `.raw` subfield which is analyzed.  Or something.  I'm not sure what is the Elasticsearch convention for being able to do both exact match searches and "fuzzy" match searches on the same field.  @portante

**Comment by portante** [comment]
@richm, is the `container_name.raw` field added by default or was it explicitly added in the mapping?  If it is added by default, do you know how that happened?  I thought default field types came when a mapping was not explicitly present.

**Comment by richm** [comment]
The `container_name.raw` field was added explicitly in order to support the Kibana visualizations.

**Comment by portante** [comment]
@richm, so the kibana visualizations can be changed to rely on the `container_name` field directly now that it is `not_analyzed`.

**Comment by richm** [comment]
> @richm, so the kibana visualizations can be changed to rely on the container_name field directly now that it is not_analyzed.

can you submit a PR for that?

**Comment by nhosoi** [comment]
>> @richm, so the kibana visualizations can be changed to rely on the container_name field directly now that it is not_analyzed.

> can you submit a PR for that?

https://github.com/openshift/origin-aggregated-logging/pull/903
Update to reference only the container_name field #903

**Comment by lukas-vlcek** [comment]
@portante @richm If you are going to send PR to use `container_name` instead of `container_name.raw` then please make sure you remove the `.raw` field from `container_name` mapping (see <https://github.com/ViaQ/elasticsearch-templates/blob/master/namespaces/kubernetes.yml>)

**Pull request closed without merging**
