### PR TITLE
port json-parsing to hack/lib

### PR DESCRIPTION
**Pull request by richm**
@stevekuznetsov @jcantrill @nhosoi PTAL
[test]

### CODE REVIEW

**Comment by nhosoi** [comment]
The new test script json-parsing.sh is going to be placed in $OS_O_A_L_DIR/test, while the helper python script is left behind.
`$OS_O_A_L_DIR/hack/testing/test-json-parsing.py`
Can I learn a quick rule which file is supposed to be in which directory?
```
$OS_O_A_L_DIR/hack/lib/
$OS_O_A_L_DIR/hack/testing/
$OS_O_A_L_DIR/test/
$OS_O_A_L_DIR/deployer/scripts/
```
Thanks!

**Comment by stevekuznetsov** [comment]
@nhosoi in Origin we place test set-up and entrypoint code in `hack/` and the actual stand-alone scripts that run tests in `test/`.

**Comment by nhosoi** [comment]
Thanks, @stevekuznetsov !

How about helper functions/scripts which are called from the stand-alone scripts?  Like this test-json-parsing.py?  Which is better hack/ or test/?  Or it does not matter at all?

**Comment by stevekuznetsov** [comment]
If it's tooling to support a test I'd co-locate it with the test under `test/`

**Comment by richm** [comment]
Once all of the tests are ported from `/hack/testing` to `/test` we can look at what's left in `/hack/testing` in terms of support files and figure out if we want to move them to `/test` or perhaps a subdir of test.

**Comment by nhosoi** [comment]
Thanks, @stevekuznetsov @richm.  Sounds like a good plan.

**Comment by jcantrill** [comment]
[(8) Update tests to use origin/hack libraries[logging][epic-ci][epic-ois-td]](https://trello.com/c/UBias2xZ/525-8-update-tests-to-use-origin-hack-librariesloggingepic-ciepic-ois-td)

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
[merge]

**Comment by richm** [comment]
[merge]

**Pull request merged**
