### PR TITLE
bump openshift-elasticsearch-plugin to 5.6.10.2 to fix permissions

### PR DESCRIPTION
**Pull request by jcantrill**
I believe this will also fix https://bugzilla.redhat.com/show_bug.cgi?id=1595956 and depends on https://github.com/fabric8io/openshift-elasticsearch-plugin/pull/156

### CODE REVIEW

**Comment by richm** [comment]
access control test is failing - not a flake

**Comment by jcantrill** [comment]
@richm  I have not resolved #1274 so the default should still be that admin users get a kibana index tied to their username.  Investigating....

**Comment by richm** [comment]
install flake
/test logging

**Comment by jcantrill** [comment]
@richm this will probably fail tests until https://github.com/fabric8io/openshift-elasticsearch-plugin/tree/openshift-elasticsearch-plugin-5.6.10.2 is visible in maven

**Pull request merged**
