### PR TITLE
bump deployer/common submodule to - use curator 3.x for now

### PR DESCRIPTION
**Pull request by richm**
@sosiouxme @ewolinetz bump submodule commit to fix test failures due to using curator 4.x

### CODE REVIEW

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
[test]

**Comment by sosiouxme** [comment]
I looked a fair while at https://ci.openshift.redhat.com/jenkins/job/test-origin-aggregated-logging/535/ and I can't see how that could have happened. Any ideas?

**Comment by richm** [comment]
@sosiouxme not sure what you mean.  You can't see how https://ci.openshift.redhat.com/jenkins/job/test-origin-aggregated-logging/535/ failed?  It is because the devenv ami is now using docker 1.10 and `--log-driver=journald` - so fluentd can't read any container logs, so no container logs are in ES.  I'm working on a fix now, but I keep getting a different, random failure - seems origin is not very stable atm . . .

**Comment by sosiouxme** [comment]
I meant it looked to me like some data came back and it returned 1 (error)
anyway, but maybe I'm misreading the output.

On Thu, Jun 30, 2016 at 1:14 PM, Richard Megginson <notifications@github.com

**Pull request closed without merging**
