### PR TITLE
LOG-534: Vendor cloudwatch plugin

### PR DESCRIPTION
**Pull request by jcantrill**
This PR addresses https://issues.redhat.com/browse/LOG-534 by vendoring the cloudwatch plugin

### CODE REVIEW

**Comment by jcantrill** [comment]
@bparees @sichvoge I defer to your approval here if we want to vendor this for CI use

**Comment by bparees** [comment]
@jcantrill any licensing or supportability concerns?  (I realize we're not immediately declaring support for it, but presumably that's the eventual goal).  Otherwise it's got my approval.

**Comment by jcantrill** [comment]
> @jcantrill any licensing or supportability concerns? (I realize we're not immediately declaring support for it, but presumably that's the eventual goal). Otherwise it's got my approval.

* It's MIT so I don't think licensing is an issue: https://github.com/fluent-plugins-nursery/fluent-plugin-cloudwatch-logs/blob/master/LICENSE.txt
* It's a 'nursery' plugin so maybe support is questionable but rubygems had it at 200,000+ downloads and the next closes are all forks of this one

**Comment by jcantrill** [comment]
retest

**Comment by jcantrill** [comment]
Closing until such time we are ready to readdress

**Comment by jcantrill** [comment]
replaced by https://github.com/openshift/origin-aggregated-logging/pull/2026

**Pull request closed without merging**
