### PR TITLE
add loggingPublicURL for the OpenShift UI Console kibana link

### PR DESCRIPTION
**Pull request by richm**

### CODE REVIEW

**Comment by richm** [comment]
@ewolinetz @jcantrill @nhosoi @lukas-vlcek With this patch I am able to get to the kibana link in the openshift UI console
```
firefox https://public.master.hostname.fqdn:8443
# Advanced -> Add Exception... -> uncheck "Permanently store this exception" -> Confirm Security Exception
# then do this ^^^ again if necessary if you have host aliases set up - probably not necessary with aws
Login -> Username: kibtest -> Password: kibtest -> Log In
logging -> Applications -> Pods -> logging-fluentd-1-build -> Logs -> View archive
# Advanced -> Add Exception... -> uncheck "Permanently store this exception" -> Confirm Security Exception -> To display this page ..... -> Resend
```
You should now be in kibana looking at the logs for the logging-fluentd-1-build

**Comment by richm** [comment]
[test]

**Comment by ewolinetz** [comment]
:+1: LGTM

**Comment by richm** [comment]
[merge]

**Pull request merged**
