### PR TITLE
merge latest master into master-post-release

### PR DESCRIPTION
**Pull request by richm**

### CODE REVIEW

**Comment by ewolinetz** [comment]
we couldn't just open a pr from `openshift:master` into `openshift:master-post-release`?

**Comment by richm** [comment]
> we couldn't just open a pr from openshift:master into openshift:master-post-release?

do you mean, for every PR against master that has merged since $lastmergedate, /cherrypick to master-post-release?

**Comment by ewolinetz** [comment]
@richm basically yes, we should be able to choose the source as `openshift:master` and just open that against `openshift:master-post-release` as a massive 'cherry-pick'

**Comment by richm** [comment]
> @richm basically yes, we should be able to choose the source as `openshift:master` and just open that against `openshift:master-post-release` as a massive 'cherry-pick'

ok - so that will impose an accounting burden on all of the developers to mark their PRs to master as `backport/master-post-release` and `backport/completed` when the cherrypick is merged - otherwise we will go crazy trying to answer the question "Was this PR cherrypicked to master-post-release?"

**Pull request merged**
