### PR TITLE
Fix "elasticsearch version marked as SNAPSHOT" in rhel8

### PR DESCRIPTION
**Pull request by vimalk78**
Copy of PR https://github.com/openshift/origin-aggregated-logging/pull/1966
This was fixed in `Dockerfile` but not fixed in `Dockerfile.rhel8`

/cc @ewolinetz 
/assign @jcantrill

### CODE REVIEW

**Review by periklis — APPROVED** [review]
/lgtm

**Comment by jcantrill** [comment]
overriding bz valid label for cpaas integration

**Comment by ewolinetz** [comment]
@vimalk78 any update on this?

**Comment by vimalk78** [comment]
@ewolinetz @jcantrill this PR is not building locally. This change is already propogated to downstream on Sep 15.

**Comment by ewolinetz** [comment]
```
+ chmod -R u+w,g+w /opt/app-root/src/sgconfig /usr/share/elasticsearch/index_templates
mv: cannot stat '/usr/share/elasticsearch/lib/elasticsearch-6.8.1.redhat-6.jar': No such file or directory
subprocess exited with status 1
subprocess exited with status 1
error: build error: error building at STEP "RUN ${HOME}/in...earch-$(echo $ES_VER | cut -d'.' -f1-3).jar": exit status 1
```

**Comment by jcantrill** [comment]
@vimalk78 @ewolinetz do we need this PR still?

**Pull request closed without merging**
