### PR TITLE
Restricting roles

### PR DESCRIPTION
**Pull request by ewolinetz**
Fluentd doesn't need to read, curator doesn't need to write and Kibana doesn't need to be able to query everything (the user profile should cover that)

@sosiouxme @richm

### CODE REVIEW

**Comment by ewolinetz** [comment]
[test]

**Comment by richm** [comment]
lgtm

**Comment by ewolinetz** [comment]
[test]

**Comment by ewolinetz** [comment]
[test]

**Comment by ewolinetz** [comment]
etcd related [test]

**Comment by ewolinetz** [comment]
[test]

**Comment by ewolinetz** [comment]
db wasn't ready? [test]

**Comment by ewolinetz** [comment]
flaked [test]

**Comment by richm** [comment]
```
[INFO] Waiting for database to start...
ERROR: gave up waiting for http://<no value>:5434
[ERROR] PID 2160: logging.sh:337: `return 1` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: logging.sh:337: `return 1`
[INFO] 		  2: logging.sh:470: wait_for_app
```
[test] in case this is a transient problem

**Comment by richm** [comment]
arg - aws error [test]

**Comment by ewolinetz** [comment]
aws errors again [test]

**Comment by richm** [comment]
[test] try m4.large machine

**Comment by richm** [comment]
etcd . . . [test]

**Comment by ewolinetz** [comment]
looks like what we use to grab the db ip is incorrect...

**Comment by ewolinetz** [comment]
Etcd flake... [test]

**Comment by ewolinetz** [comment]
[test] etcd again

**Comment by ewolinetz** [comment]
[test]

**Comment by richm** [comment]
[test] etcd again - is there something we can do to minimize/avoid/retry these etcd errors!?!??!!? @smarterclayton ?

**Comment by richm** [comment]
this is really aggravating - etcd [test]

**Comment by richm** [comment]
```
Executing command [oc exec logging-kibana-1-a4mjm -- curl -s --key /etc/kibana/keys/key --cert /etc/kibana/keys/cert --cacert /etc/kibana/keys/ca -H 'X-Proxy-Remote-User: kibtest' - H 'Authorization: Bearer fEPdb83dIwapFRwNVXvDQvyksRzHy5AStLx2WJk0KJY' -H 'X-Forwarded-For: 127.0.0.1' -XGET "https://172.30.207.160:9200/logging.3471d2cb-7ee1-11e6-a0ee-0eae678a61d5.*/fluentd/_search?q=hostname:ip-172-18-11-253&fields=message&size=500"]
output []
error [exit status 2]panic: exit status 2
```
@ewolinetz the search returned nothing?

**Comment by ewolinetz** [comment]
@richm hmm, i've gotten that to work on my other test machines before... let me try setting up my env using the logging.sh script and test it again

**Comment by ewolinetz** [comment]
etcd again... [test]

**Comment by ewolinetz** [comment]
same.. [test]

**Comment by ewolinetz** [comment]
etcd [test]

**Comment by richm** [comment]
[test]

**Comment by ewolinetz** [comment]
re[test]

**Comment by ewolinetz** [comment]
ES build took too long to start... [test]

**Comment by ewolinetz** [comment]
[merge] while you're at it

**Comment by smarterclayton** [comment]
What etcd flakes are these?  Can you describe them?

**Comment by richm** [comment]
@smarterclayton for example, from https://ci.openshift.redhat.com/jenkins/job/test-origin-aggregated-logging/838/consoleText
```
Uploading directory "/data/src/github.com/openshift/origin-aggregated-logging" as binary input for the build ...
Error from server: client: etcd member https://172.18.15.221:4001 has no leader
[ERROR] PID 2163: logging.sh:326: `oc start-build --from-dir $OS_O_A_L_DIR $bc` exited with status 1.
```
or from https://ci.openshift.redhat.com/jenkins/job/test-origin-aggregated-logging/839/consoleText
```
Uploading directory "/data/src/github.com/openshift/origin-aggregated-logging" as binary input for the build ...
Error from server: client: etcd cluster is unavailable or misconfigured
[ERROR] PID 2172: logging.sh:326: `oc start-build --from-dir $OS_O_A_L_DIR $bc` exited with status 1.
```

They seem to come in batches.  They will go away for a week, then we will get several test failures like this the next week.

**Comment by richm** [comment]
We've made a couple of changes to the CI test env recently, and have not seen any failures since:

- using m4.large instead of c4.large
- pre-loading all of the images used to build (rather than having the build pull all of the layers)

We haven't seen any failures related to etcd since.

**Pull request merged**
