### PR TITLE
Fluentd should write times/timestamps in UTC

### PR DESCRIPTION
**Pull request by richm**
Plus some test fixes
[test]
@ewolinetz @jcantrill @nhosoi PTAL

### CODE REVIEW

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
[test] again to see if github.com issue is a flake

**Comment by jcantrill** [comment]
LGTM

**Comment by richm** [comment]
[test]

**Comment by ewolinetz** [comment]
LGTM!

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
So the latest fun is that something has changed in the past few days with respect to client DNS configuration.  Here is the `/etc/resolv.conf` from a working deployment kibana pod:
```
search logging.svc.cluster.local svc.cluster.local cluster.local
nameserver 172.30.0.1
options ndots:5
```
Here is the latest:
```
nameserver 127.0.0.1
options ndots:5
```
Logging assumes that it can use `logging-es` which will resolve to `logging-es.logging.svc.cluster.local`.  Is there some sort of configuration switch we need to set to say "please add search to pod resolv.conf"?

**Comment by richm** [comment]
The plot thickens - from /tmp/origin-aggregated-logging/logs/openshift.log
```
I0114 03:55:58.024000    3420 server.go:664] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"ip-172-18-15-98", UID:"ip-172-18-15-98", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Warning' reason: 'MissingClusterDNS' kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. pod: "logging-curator-ops-1-8eyti_logging(85b26433-da00-11e6-b0cd-0edfed036a1a)". Falling back to DNSDefault policy.
```
This means https://github.com/kubernetes/kubernetes/blob/2df5d4d980e8a6692b00f9ced2a23b8dd5f26bdf/pkg/kubelet/kubelet.go#L1280

So now, how to set clusterDNS correctly . . .

**Comment by richm** [comment]
ok - final version - if there are no objections, I'm going to merge once the tests pass

**Comment by richm** [comment]
[merge]

**Pull request merged**
