### PR TITLE
logstash:latest is missing - use logstash:5 for compatability

### PR DESCRIPTION
**Pull request by richm**
logstash:latest is missing - use logstash:5 for compatability

### CODE REVIEW

**Comment by richm** [comment]
we need to merge this asap to unblock ci

**Comment by richm** [comment]
hrm - build passed but ci/prow/images reports Job failed
/refresh

**Comment by richm** [comment]
@nhosoi the ci/openshift-jenkins/json-file and ci/openshift-jenkins/logging jobs are broken in master - which is why they have been changed for now not to be required to merge PRs
so for now, please lgtm this PR so we can backport to release-3.11 and release-3.10

**Comment by nhosoi** [comment]
ok!  /lgtm

**Pull request merged**
