### PR TITLE
LOG-1935: Bump logging to 5.4

### PR DESCRIPTION
**Pull request by jcantrill**
### Description
This PR:
* Preps `master` branch to for Logging release 5.4

### Links
https://issues.redhat.com/browse/LOG-1935

/assign @periklis

### CODE REVIEW

**Review by periklis — CHANGES_REQUESTED** [review]
Looks good but consider to also update the defaults in `hack/deploy-logging.sh` (See https://github.com/openshift/origin-aggregated-logging/pull/2174/files)

**Comment by jcantrill** [comment]
May be blocked on:
* https://github.com/openshift/elasticsearch-operator/pull/815
* https://github.com/openshift/cluster-logging-operator/pull/1242

**Pull request merged**
