### PR TITLE
deployer: enable using PVCs

### PR DESCRIPTION
**Pull request by sosiouxme**
Creates PVCs if they don't exist, attaches to ES DCs.

### CODE REVIEW

**Comment by sosiouxme** [comment]
[test]

**Comment by richm** [comment]
lgtm - In logging.sh, what do I need to do if I want to deploy with a PVC?  Create a PVC claim for es and es-ops?  Create directories in the filesystem for es and es-ops?

**Comment by sosiouxme** [comment]
@richm I am not sure the best route to test this. If you're going to deploy with a PVC you have to have a PV or ES won't run. I would use host-mounts except those almost certainly have extra complications. Maybe we could set up an NFS server on the host?

**Comment by richm** [comment]
egads - I don't think ES likes to use nfs e.g. google "elasticsearch nfs"
ES recommends the use of the local disk for storage (or something more fault tolerant and performant than nfs).
So the logging test should try to configure a local disk PV (which is what it does now).

**Comment by richm** [comment]
ok - so we should test both (in case there is some weird bug that causes writes inside the pod to fail, but writes to "real" PVs still work).  The test will enable the ops cluster, but only configure the es-ops instance to use the real PV.  So how do I create a PV claim to use /var/lib/es-ops?

**Comment by sosiouxme** [comment]
See hack/templates/pv-hostmount.yaml for an example (needs a tweak or two)

**Comment by sosiouxme** [comment]
[test]

**Comment by sosiouxme** [comment]
[test] again, ya?

**Comment by sosiouxme** [comment]
etcd flake [test]

**Comment by sosiouxme** [comment]
fscking flakes come on!
[test]

**Comment by sosiouxme** [comment]
CI seems hosed today, try again later.

**Comment by sosiouxme** [comment]
Let's try this again. [test]

**Comment by richm** [comment]
The test failure is in the ES OPS instance: https://ci.openshift.redhat.com/jenkins/job/test-origin-aggregated-logging/116/artifact/origin/artifacts/logs/container-logging-es-ops-o5edh1wd-1-19fs8-elasticsearch.log/*view*/::

    [2016-04-15 14:19:17,369][INFO ][plugins                  ] [Shaper of Worlds] loaded [searchguard, openshift-elasticsearch-plugin, cloud-kubernetes], sites []
    {1.5.2}: Initialization Failed ...
    - ElasticsearchIllegalStateException[Failed to created node environment]
	AccessDeniedException[/elasticsearch/persistent/logging-es-ops]

**Comment by sosiouxme** [comment]
Yeah, that's probably a real error, still with the permissions on the
persistent volume.

**Comment by sosiouxme** [comment]
@ewolinetz PTAL

**Comment by ewolinetz** [comment]
squash and LGTM!

**Pull request merged**
