### PR TITLE
remove deployer/; move util.sh to hack/testing; cleanup unused code

### PR DESCRIPTION
**Pull request by richm**
remove deployer/; move util.sh to hack/testing; cleanup unused code
@jcantrill @portante @nhosoi PTAL
[test]

### CODE REVIEW

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
@stevekuznetsov any idea why jenkins is marking this test as a failure?  This is the only thing I see in the output is this:
```
########## STARTING STAGE: ASSEMBLE GCS OUTPUT ##########
...
+ scp -F ./.config/origin-ci-tool/inventory/.ssh_config openshiftdevel:/data/finished.json gcs/
scp: /data/finished.json: No such file or directory
++ export status=FAILURE
++ status=FAILURE
+ exit 0
```
but the overall test reports success?
```
########## FINISHED STAGE: SUCCESS: DEPROVISION CLOUD RESOURCES [00h 03m 35s] ##########
Archiving artifacts
Recording test results
Finished: SUCCESS
```

**Comment by stevekuznetsov** [comment]
From the top-level job: 

```
ERROR: Unable to find project for artifact copy: test_pull_request_origin_aggregated_logging_ansible_json_file
```

I noticed there were some generated jobs missing in `aos-cd-job` today -- maybe that? https://github.com/openshift/aos-cd-jobs/commit/367e21eec54f3caa1d49bb30fde1d8ad5458e092

**Comment by richm** [comment]
@stevekuznetsov ok - then something went wrong with my recent commit to add json-file support to the logging CI :-(

**Comment by richm** [comment]
I tested the "leaf" job but I didn't test it in conjunction with the "parent" job

**Comment by richm** [comment]
ok - manually added job using `sjb/push-update.sh sjb/generated/test_pull_request_origin_aggregated_logging_ansible_json_file.xml`
[test]

**Comment by richm** [comment]
[merge]

**Pull request merged**
