### PR TITLE
new location for node kubeconfig; dump rsyslog log at end of test

### PR DESCRIPTION
**Pull request by richm**

### CODE REVIEW

**Comment by richm** [comment]
/test json-file
curator flake

**Comment by richm** [comment]
some sort of weird mux flake in remote-syslog
```
SUCCESS after 0.768s: test/remote-syslog.sh:81: executing 'oc get dc logging-mux -o jsonpath='{ .status.replicas }'' expecting any result and text '0'; re-trying every 0.2s until completion or 600.000s

error: Scaling the resource failed with: Operation cannot be fulfilled on deploymentconfigs.apps.openshift.io "logging-mux": the object has been modified; please apply your changes to the latest version and try again; Current resource version Unknown
Running test/remote-syslog.sh:84: executing 'oc get pods -l component=mux' expecting any result and text '^logging-mux-.* Running '; re-trying every 0.2s until completion or 600.000s...

FAILURE after 599.963s: test/remote-syslog.sh:84: executing 'oc get pods -l component=mux' expecting any result and text '^logging-mux-.* Running '; re-trying every 0.2s until completion or 600.000s: the command timed out
```
/test json-file

**Comment by richm** [comment]
@ewolinetz @jcantrill tests finally passing - please lgtm again

**Comment by jcantrill** [comment]
@richm do we really need to cherrypick to 3.7 since the cluster structure should not have changed

**Comment by richm** [comment]
@jcantrill in general, we should cherry pick everything - otherwise, when we need to fix something that does really need to be cherry picked, it will be almost impossible if the branches have diverged significantly
The problem is that there are several 3.7 PRs which are stalled, and this is conflicting with one of them

**Pull request merged**
