### PR TITLE
bump openshift-elasticsearch-plugin to 2.4.4.15

### PR DESCRIPTION
**Pull request by jcantrill**
This PR bumps the openshift-elasticsearch-plugin to 2.4.4.15 to fix:

* bug 1476062. Allow write to kibana index
* bug 1491227. Modify request if user has back slash
* bug 1490719. Operations missing from .all alias
* Update Dockerfile to match 3.7 downstream

### CODE REVIEW

**Comment by jcantrill** [comment]
[test]

**Comment by richm** [comment]
Can we have tests to
- verify the new acl works
- verify that user-defined index patterns are not overwritten

**Comment by jcantrill** [comment]
Depends on https://github.com/fabric8io/openshift-elasticsearch-plugin/pull/100

**Comment by jcantrill** [comment]
@richm @portante This will fail until we release the change.  Test results for the given change from manually running: https://github.com/fabric8io/openshift-elasticsearch-plugin/pull/100#issuecomment-331169982

**Comment by jcantrill** [comment]
[merge]

**Comment by richm** [comment]
grr - problem with mux enabled

**Comment by richm** [comment]
[merge]

**Pull request merged**
