### PR TITLE
Take into account .audit index in curator

### PR DESCRIPTION
**Pull request by JAORMX**

### CODE REVIEW

**Comment by JAORMX** [comment]
@richm @jcantrill I'm still unsure if this covers the curator. I'm unable to find where the default configuration comes from, as it seems to be all commented out in the ConfigMap that's generated by default.

**Comment by richm** [comment]
still something going on with ci tests - fluentd logs say that fluentd cannot connect to elasticsearch

**Comment by richm** [comment]
multi-tenancy flake
/retest

**Pull request merged**
