### PR TITLE
bug 1446217. Bump plugin to use SAR to evaluate ops user

### PR DESCRIPTION
**Pull request by jcantrill**
Blocked by https://github.com/fabric8io/openshift-elasticsearch-plugin/pull/73

### CODE REVIEW

**Comment by richm** [comment]
[merge]

**Comment by jcantrill** [comment]
Dependency published in: https://fabric8-ci.fusesource.com/view/release%20builds/job/openshift-elasticsearch-plugin-release/42

**Comment by jcantrill** [comment]
@richm I think maybe 1.5.  And we could in 1.4, but I prefer to do minimum possible for the 1.4 release stream

**Comment by jcantrill** [comment]
[merge]

**Pull request merged**
