### PR TITLE
request dynamic provisioning for PVCs

### PR DESCRIPTION
**Pull request by sosiouxme**

### CODE REVIEW

**Comment by sosiouxme** [comment]
@jcantrill @ewolinetz PTAL

**Comment by sosiouxme** [comment]
[test]

**Comment by jcantrill** [comment]
lgtm

**Comment by ewolinetz** [comment]
LGTM -- is this something we can add to the automated tests at all?

**Comment by sosiouxme** [comment]
@ewolinetz since our tests happen in AWS we could theoretically leverage EBS and configure dynamic provisioning. I'm not inclined to go to the trouble just for this feature.

**Comment by sosiouxme** [comment]
I was unable to simplify down to a single template due to template shortcomings. I simplified the logic to invoke them, though.

**Comment by sosiouxme** [comment]
https://github.com/openshift/origin/issues/9321

**Comment by sosiouxme** [comment]
[merge]

**Pull request merged**
