### PR TITLE
Bug 1739558: rsyslog underperforming compared to fluentd

### PR DESCRIPTION
**Pull request by richm**
https://bugzilla.redhat.com/show_bug.cgi?id=1739558
imfile: followrename - continue to follow renamed files

Some applications do rotation by renaming the file, then continuing to
write to it for a short time, before recreating the original file. See
IMFILE for the gory details.

Introduce a new imfile parameter `followrename` (boolean) to handle this
case.  If this parameter is set, when inotify detects a rename event
(IN_MOVED_FROM), it will keep reading from the file until it sees that a
new file has been created with the same name.  It will then create a new
state file with state saved from the old state file e.g. prevLineSegment,
prevMsgSegment, and unlink the old file from the active list. the
moved_from file from the active list, and create a new active list entry
for the moved_to file, preserving the state file from the moved_from file. 
This also does some code refactoring in order to reuse some of the
functions for adding a new act_obj for the renamed file. Use
STREAMTYPE_FILE_SINGLE for monitored files instead of 
STREAMTYPE_FILE_MONITOR so that the stream module won't attempt to reopen
the file if it detects the filename has a different inode number.

Enabling valgrind testing on imfile revealed a memory leak which is fixed
in this PR.

Changed some "ignored" error messages to use LOG_INFO - if they are really
not that serious, they should not be printed by default.

Fixed some spelling errors.

(cherry picked from commit 678b7dc4fb9a74309781f260bb8ef8134ee3e6d2)

merge in latest rsyslog 8.1.z

Add a performance test
that runs a pod using logging-load-driver to write and verify logs for
records per second, skipped records, and duplicate records.

### CODE REVIEW

**Comment by richm** [comment]
doesn't work - fails when crio/kubelet compresses rotated files :-(

**Comment by nhosoi** [comment]
> doesn't work - fails when crio/kubelet compresses rotated files :-(

That means rsyslog could not catch up the crio log writing speed?  When rotated, one log is just renamed to `logname`.log.`date`.  When the next log file is rotated, the `logname`.log.`date` would be compressed...

**Comment by richm** [comment]
> > doesn't work - fails when crio/kubelet compresses rotated files :-(
> 
> That means rsyslog could not catch up the crio log writing speed? When rotated, one log is just renamed to `logname`.log.`date`. When the next log file is rotated, the `logname`.log.`date` would be compressed...

I don't think so - the symptom I see is that rsyslog skips a lot of records when this happens.  I think it has to do with the way rsyslog stores state files using the inode number, and the fact that when rsyslog rotates the second time, it reuses the inode number of the original file.  What may be happening is that when rsyslog rotates the file a second time, it somehow reuses the existing state file for that inode number, and skips over the records it thinks were already read.

**Comment by portante** [comment]
Not sure this helps, but I used https://sequencediagram.org/ to create two sequence diagrams that *might* explain the good vs bad scenarios for rsyslog (cut and paste them into the dialog box to auto generate the diagrams):

**Good**:
```
title rsyslog file rotation (good)

cri-o->log-file-0:Write 0
cri-o->log-file-0:Write 1
log-file-0->rsyslog:Read
cri-o->log-file-0:Write 2
cri-o->log-file-0:Write 3
cri-o->log-file-0:Write 4
kubelet->log-file-0:Renamed to log-file-0.YYYY-MM-DD
kubelet->cri-o:kill -HUP
cri-o->log-file-0:Close
cri-o->log-file-1:Create
cri-o->log-file-1:Write
kernel->rsyslog:inotify event for rename of log-file-0
log-file-0->rsyslog:Read
rsyslog->log-file-0:Close
kernel->rsyslog:inotify event for create of log-file-1
rsyslog->log-file-1:Open
log-file-1->rsyslog:Read
```

**Bad**:
```
title rsyslog file rotation (bad)

cri-o->log-file-0:Write 0
cri-o->log-file-0:Write 1
log-file-0->rsyslog:Read
cri-o->log-file-0:Write 2
cri-o->log-file-0:Write 3
kubelet->log-file-0:Renamed to log-file-0.YYYY-MM-DD
kernel->rsyslog:inotify event for rename of log-file-0
log-file-0->rsyslog:Read
cri-o->log-file-0:Write 4
kubelet->cri-o:kill -HUP
rsyslog->log-file-0:Close
cri-o->log-file-0:Close
cri-o->log-file-1:Create
kernel->rsyslog:inotify event for create of log-file-1
rsyslog->log-file-1:Open
cri-o->log-file-1:Write
log-file-1->rsyslog:Read
```

The "Bad" scenario is bad because (theorizing) the `rsyslog` receives the `inotify` event for the log file rename and reads from the rotated log file before `cri-o` writes its last buffer to the rotated file.

`rsyslog` would have to keep the rotated log file open for a period of time long enough for `cri-o` to receive its `HUP` signal, writes its last buffer, and close the file.

**Pull request closed without merging**
