### PR TITLE
globally remove imagePullPolicy: Always

### PR DESCRIPTION
**Pull request by jim-minter**
I'd like "imagePullPolicy: Always" to be removed, on the grounds that it makes development harder, and it should not be needed.  Is it possible?

### CODE REVIEW

**Comment by jcantrill** [comment]
The deployer is deprecated in master.  These changes will need to be applied to the openshift_logging_* roles of ansible if they have not already been applied.  @ewolinetz @portante  thoughts on wanting to apply this in general?  Make it configurable in ansible?

**Comment by jim-minter** [comment]
@jcantrill is there a note anywhere indicating that the deployer is deprecated? I couldn't find one.

**Comment by jcantrill** [comment]
There is an open PR to modify the docs and correct, but the deployer only exists to support 'oc cluster up' which will be moved to an alternative in the forthcoming release

**Comment by ewolinetz** [comment]
The reason we set the `imagePullPolicy` as `always` is so that we can ensure that when a deployment for logging is done the most recently published images are used. If it is desired that we have a way to not have this enabled then it should be an installation option, or we should document how to remove it manually.

**Comment by richm** [comment]
Can we close this PR?  or move it to openshift-ansible?

**Comment by jcantrill** [comment]
Closing this PR.  @jim-minter please open a PR against openshift-ansible if still appropriate.

**Pull request closed without merging**
