### PR TITLE
added test indexing_after_ns_removal

### PR DESCRIPTION
**Pull request by niconosenzo**
Was [PR 1142](https://github.com/openshift/origin-aggregated-logging/pull/1142). Didn't branch the fork before doing the changes. Now doing the things cleaner, also added suggestions by @richm 

Test for https://bugzilla.redhat.com/show_bug.cgi?id=1575662

### CODE REVIEW

**Comment by portante** [comment]
Does this test verify that the pod UIDs in the metadata for the logs in each index matches the expected UIDs for the pods associated with those namespaces?

Does this test enumerate how many orphaned logs there are?

**Comment by richm** [comment]
> Does this test verify that the pod UIDs in the metadata for the logs in each index matches the expected UIDs for the pods associated with those namespaces?

no

> Does this test enumerate how many orphaned logs there are?

no

**Pull request merged**
