### PR TITLE
host openshift-elasticsearch-plugin on github instead of building

### PR DESCRIPTION
**Pull request by jcantrill**
(cherry picked from commit 1bc5dde83d4914172f2d8289174053838926e397)

backport of #899 

cc @sosiouxme

### CODE REVIEW

**Comment by richm** [comment]
not a flake
```
[openshift/origin-logging-elasticsearch] --> ADD lib /tmp/lib
[openshift/origin-logging-elasticsearch] stat elasticsearch/lib: no such file or directory
[ERROR] PID 5022: hack/build-images.sh:56: `return "${result}"` exited with status 1.
```

**Comment by jcantrill** [comment]
/retest  
@richm I am locally unable to reproduce that error which is perplexing.  I manually ran docker build as well as the build-images

**Comment by richm** [comment]
ok - perhaps it was a flake after all

**Pull request merged**
