### PR TITLE
use new elasticsearch plugin with bulk handling and logstash key

### PR DESCRIPTION
**Pull request by richm**
https://github.com/ViaQ/fluent-plugin-elasticsearch/releases/tag/v1.9.5.1

### CODE REVIEW

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
@portante

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
@jcantrill so the plan would be to carry this patched plugin ourselves and in the meantime work with upstream to accept the PRs

**Comment by jcantrill** [comment]
@richm This is the patch with @portante original changes to fix dropping messages when there is an exception?

**Comment by richm** [comment]
@jcantrill yes, this fixes the bulk index rejection problem, dropping messages

**Comment by richm** [comment]
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1470862

**Comment by richm** [comment]
[merge]

**Pull request merged**
