### PR TITLE
[3.6] Flushing fluentd pos files prior to starting up

### PR DESCRIPTION
**Pull request by ewolinetz**
3.6 Backport of https://github.com/openshift/origin-aggregated-logging/pull/734

### CODE REVIEW

**Comment by richm** [comment]
@ewolinetz I think https://github.com/openshift/origin-aggregated-logging/pull/749 will solve this test flake

**Comment by richm** [comment]
could you perhaps do a rebase instead of merge commits?

**Comment by ewolinetz** [comment]
@richm sure, i was lazy and used github's ui to resolve the conflict...

**Comment by ewolinetz** [comment]
i definitely rebased, im not sure why the bot isn't recognizing that

**Comment by richm** [comment]
@ewolinetz I don't see an updated commit?

**Comment by ewolinetz** [comment]
something doesn't seem right with this branch.. closing and will open another to backport

**Comment by ewolinetz** [comment]
https://github.com/openshift/origin-aggregated-logging/pull/757

**Pull request closed without merging**
