### PR TITLE
bump es plugin to 2.4.4.13 for user based roles

### PR DESCRIPTION
**Pull request by jcantrill**
This PR:
 
* bumps the openshift-elasticsearch-plugin to v2.4.4.12
* allows users with multiple project to query across indicies by changing to user based roles from projects

### CODE REVIEW

**Comment by jcantrill** [comment]
[test]

**Comment by richm** [comment]
@jcantrill do we want to backport this to 3.6?

**Comment by jcantrill** [comment]
[test] flake?

**Comment by jcantrill** [comment]
@richm  It would be nice to backport since it is a deficiency in the original design.  I don't know if we see issues in the field.  Alternatively, I'm not certain we will be able to backport the sharing of kibana dashboards for operators without this change.  @portante what are your thoughts?  Should we create an issue and backport?

**Comment by portante** [comment]
Let's wait on backporting until we have a good handle on other issues first.

**Comment by jcantrill** [comment]
I'll mark it as backport 3.6 and 3.5 and we can wait on doing that but atleast it is a candidate

**Comment by jcantrill** [comment]
[test]

**Comment by richm** [comment]
[merge]

**Comment by richm** [comment]
es-ops could not start due to insufficient memory - trying again to see if this is a flake [merge]

**Comment by jcantrill** [comment]
@richm we recently made the change to set the request memory to the limit memory which has ramifications on the pod being deployed to the node.  Maybe this is another case where we need to make default modifications to do our testing

**Comment by richm** [comment]
[merge]

**Comment by richm** [comment]
[merge]

**Comment by richm** [comment]
[merge]

**Comment by lukas-vlcek** [comment]
I guess this would be related? https://github.com/fabric8io/openshift-elasticsearch-plugin/issues/99

**Comment by jcantrill** [comment]
[test]

**Comment by richm** [comment]
@jcantrill should we close this PR in favor of the one for 2.4.4.13?

**Comment by jcantrill** [comment]
Added change from #632 since it wont pass without being able to build the ES image and pass the test

**Comment by jcantrill** [comment]
[merge]

**Comment by jcantrill** [comment]
[merge]

**Pull request merged**
