### PR TITLE
add additional debugging

### PR DESCRIPTION
**Pull request by richm**

### CODE REVIEW

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
[test]

**Comment by sosiouxme** [comment]
LGTM

**Comment by richm** [comment]
[merge]

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
[merge]

**Pull request merged**
