### PR TITLE
add tools from jcantrill/openshift-logging-tools

### PR DESCRIPTION
**Pull request by richm**
add tools from jcantrill/openshift-logging-tools
https://github.com/jcantrill/openshift-logging-tools

### CODE REVIEW

**Comment by jcantrill** [comment]
@richm do we want to submodule the repo instead?  might make it easier to pull it in as they update

**Comment by richm** [comment]
> @richm do we want to submodule the repo instead? might make it easier to pull it in as they update

who is "they"?

**Comment by jcantrill** [comment]
@richm  ...'we'

**Comment by richm** [comment]
I don't understand - wouldn't it be easier for us to contribute PRs directly against the single shared openshift/origin-aggregated-logging repo?

**Comment by jcantrill** [comment]
Closing this PR.  My preference is to either submodule them in or create an openshift repo.  The issue with either of these implies there is some official support which I'm not sure we want to take on .  Additionally, I like the idea of not pulling them in here because my experience has been to simply clone them onto a target host which is significantly easier with a dedicated repo vs all of logging

**Pull request closed without merging**
