### PR TITLE
bug 1524644. Curator configuration produces wrong regular expressions

### PR DESCRIPTION
**Pull request by josefkarasek**
For example `^.operations.` instead of `^\.operations\..*$`
Both regexes match, but the first one only accidentaly. Example index name:
`.operations.1827ac8a-ef8f-11e7-92de-0ebdd5807cb2.2018.01.02`

Curator code: https://github.com/elastic/curator/blob/3.5/curator/api/filter.py#L90-L138

Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1524644

### CODE REVIEW

**Comment by jcantrill** [comment]
Do we have any test to verify what we are seeing here?

**Comment by josefkarasek** [comment]
@jcantrill  https://github.com/openshift/origin-aggregated-logging/blob/master/test/curator.sh

**Comment by ewolinetz** [comment]
@josefkarasek should we also be cherry picking this?

**Pull request merged**
