### PR TITLE
Point OPS_HOST to the default elasticsearch ops cluster

### PR DESCRIPTION
**Pull request by georgegoh**
Proposed fix for issue #437

### CODE REVIEW

**Comment by richm** [comment]
@georgegoh Have you verified that this fix solves your problem?  Because that file isn't used anymore, it is only used for CI testing.  Since 3.5 the fluentd template is in ansible.

**Comment by georgegoh** [comment]
@richm In my case, my cluster was on 3.4 and I set up EFK after install.

**Comment by richm** [comment]
@georgegoh ok - please submit a PR against the release-1.4 branch

**Comment by georgegoh** [comment]
Closing this to create a new PR under the release-1.4 branch.

New PR at
https://github.com/openshift/origin-aggregated-logging/pull/439

**Pull request closed without merging**
