### PR TITLE
Fix bulk rejection test

### PR DESCRIPTION
**Pull request by jcantrill**
Fix bulk rejection test to unblock https://github.com/openshift/openshift-ansible/pull/10357

### CODE REVIEW

**Comment by richm** [comment]
not sure why the travis test failed . . . not sure how to make it retest, unless you push a change to something

**Comment by nhosoi** [comment]
> not sure why the travis test failed

At least, filter_concat looks broken...  Can we merge pr/1386, then try again?

**Comment by richm** [comment]
sure - we have a lot of PRs in the test/merge queue . . .

**Pull request merged**
