### PR TITLE
Bug 1732059: Move to Elastic 5.6.16 to resolve Kibana security flaw

### PR DESCRIPTION
**Pull request by jcantrill**
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1732059 by bumping to 5.6.16

Depends on:
* https://github.com/fabric8io/openshift-elasticsearch-plugin/pull/187
* https://github.com/openshift/origin-kibana/pull/34
* Downstream dependencies

### CODE REVIEW

**Comment by jcantrill** [comment]
cc @richm

**Comment by jcantrill** [comment]
Seems to not be picking up the fix to the plugin

**Comment by richm** [comment]
rsyslog flake supposed to be fixed by https://github.com/openshift/cluster-logging-operator/pull/238
/retest

**Pull request merged**
