### PR TITLE
Merge es2.x upgrade into master

### PR DESCRIPTION
**Pull request by jcantrill**
Changes to merge es2.x into master

### CODE REVIEW

**Comment by jcantrill** [comment]
@ewolinetz  please review to see if its all good [test]

**Comment by ewolinetz** [comment]
LGTM

**Comment by ewolinetz** [comment]
there currently is a security fix required with the OpenShift Elasticsearch Plugin fyi: https://github.com/fabric8io/openshift-elasticsearch-plugin/issues/46

**Comment by jcantrill** [comment]
[merge]

**Pull request merged**
