### PR TITLE
Bug 1721290: Update the method used to create manifest for source first build

### PR DESCRIPTION
**Pull request by richm**
For https://jira.coreos.com/browse/LOG-393
For fluentd, and rsyslog, the images
where we have non-RPM content, we need to generate a
manifest for SRT to use, to track security issues in
the components we use.

For rsyslog, at source update time, when the
`hack/update-rsyslog-vendor-src.sh` script is run, it will
generate a `rsyslog/rh-manifest.txt` file containing the rpm
package name and version.

For fluentd, at source update time, when the
`hack/update-fluentd-vendor-src.sh` script is run, it will
generate a `fluentd/rh-manifest.txt` file containing the rpm
package (if any, or the gemname), the version, and the homepage
of the gem component.

(cherry picked from commit f6f5a851ae3431d7b0d59f2a30d93a01965f007c)

### CODE REVIEW

**Comment by richm** [comment]
This is the manual cherrypick of https://github.com/openshift/origin-aggregated-logging/pull/1607

**Comment by richm** [comment]
please review

**Comment by richm** [comment]
please review

**Comment by ewolinetz** [comment]
lgtm, this will need a bug linked to it so it can be merged in though

**Comment by richm** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1721290

**Comment by richm** [comment]
bz is linked - please review

**Pull request merged**
