### PR TITLE
fix recent eventrouter and fluentd-forward test flakes

### PR DESCRIPTION
**Pull request by richm**
I think that the eventrouter and fluentd-forward tests are leaving
fluentd in some strange state that causes test failures in
subsequent tests

### CODE REVIEW

**Comment by richm** [comment]
@jcantrill we'll see if this fixes the recent flakes . . .

**Comment by nhosoi** [comment]
/lgtm
@richm, thanks for adding the cleanup code.  I noticed I forgot to reset the mux client while working on #1424...  Your fix is much better.

**Comment by richm** [comment]
centos repo flakes
/test json-file

**Comment by richm** [comment]
centos repo flakes
/test images

**Comment by richm** [comment]
centos repo flakes
/test images

**Comment by richm** [comment]
centos repo flakes
/test images

**Comment by richm** [comment]
centos repo flakes
/test images

**Pull request merged**
