### PR TITLE
Vendor kibana plugin for 3.6

### PR DESCRIPTION
**Pull request by jcantrill**
Backport of #592

### CODE REVIEW

**Comment by jcantrill** [comment]
[test]

**Comment by jcantrill** [comment]
[test] flake?

**Comment by richm** [comment]
@jcantrill @stevekuznetsov Is this the problem that logging CI doesn't work for the release-3.6 branch?
```
TASK [openshift_master_facts : Set Default scheduler predicates and priorities] ***
task path: /usr/share/ansible/openshift-ansible/roles/openshift_master_facts/tasks/main.yml:113
fatal: [localhost]: FAILED! => {
    "failed": true, 
    "generated_timestamp": "2017-08-17 10:26:11.265557", 
    "msg": "An unhandled exception occurred while running the lookup plugin 'openshift_master_facts_default_predicates'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Unknown short_version 3.7"
}
```

**Comment by jcantrill** [comment]
@sdodson do you have any insight into the failure that @richm lists for this issue? It is a blocker for our 3.6 CI

**Comment by sdodson** [comment]
Somewhere in aos-cd-jobs we need to update them so that they install the appropriate release for a given branch.

**Comment by richm** [comment]
@sdodson Are you saying that we can't use the devenv with the latest origin code precompiled on it, we should instead use a "plain" devenv and just install origin 3.6 from upstream binaries (e.g. CentOS PaaS SIG packages)?

**Comment by sdodson** [comment]
I'm unfortunately not familiar with the devenv tooling, I just know that
this job needs to be amended to ensure that PRs against release-3.6 install
from 3.6 repos rather than including 3.7 builds.

On Fri, Aug 18, 2017 at 9:02 AM, Richard Megginson <notifications@github.com

**Comment by jcantrill** [comment]
@jupierce In the absence of @stevekuznetsov can you help us try and resolve this blocker for us?

**Comment by stevekuznetsov** [comment]
@jhadvig this is to do with your target/dependency branch logic

**Comment by stevekuznetsov** [comment]
NVM, this is because we have an unversioned build stage -- looking into it

**Comment by jcantrill** [comment]
[test]

**Comment by richm** [comment]
```
+ wget https://raw.githubusercontent.com/openshift/origin-ci-tool/master/oct/ansible/oct/callback_plugins/generate_junit.py
--2017-08-23 09:50:53--  https://raw.githubusercontent.com/openshift/origin-ci-tool/master/oct/ansible/oct/callback_plugins/generate_junit.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.32.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.32.133|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2017-08-23 09:51:09 ERROR 500: Internal Server Error.

++ export status=FAILURE
```
[test] flake?

**Comment by richm** [comment]
[merge]

**Pull request merged**
