### PR TITLE
vendor in the source files instead of the gem

### PR DESCRIPTION
**Pull request by richm**
get source files from
https://github.com/ViaQ/fluent-plugin-viaq_docker_audit_log_parser/commit/c38cb33a88a00832274d53655e2e174b7e6d6705
Also gets rid of the record-modifier gem
/test

### CODE REVIEW

**Comment by richm** [comment]
does @nhosoi have /lgtm rights?  If so, then something is wrong with @openshift-bot

**Comment by nhosoi** [comment]
@richm, I see lgtm label is set after my "/lgtm" about an hour ago...

**Pull request merged**
