### PR TITLE
Update the architecture page

### PR DESCRIPTION
**Pull request by alanconway**
- move to central origin_aggregated_logging repo
- more detailed data-flow diagrams
- clearer terminology

/cc @periklis

### CODE REVIEW

**Review by periklis — APPROVED** [review]
/lgtm

**Comment by alanconway** [comment]
/hold
stop the madness, investigate failures

**Comment by jcantrill** [comment]
Added valid label since docs change only

**Comment by alanconway** [comment]
/hold
stop testing this till the tests are fixed

**Comment by alanconway** [comment]
Closing, this page is out of date by now. Hasn't proved very  useful anywa, probably will replace it with something better focused.

**Pull request closed without merging**
