### PR TITLE
Bug 1722898: Logging data from all projects are stored to .orphaned indexes with Elasticsearch

### PR DESCRIPTION
**Pull request by richm**
obsoletes https://github.com/openshift/origin-aggregated-logging/pull/1605
(cherry picked from commit 64a3e96a9e68ce0432abe2e969022d954e8ab27b)

### CODE REVIEW

**Comment by richm** [comment]
This is a special case.  This PR should have been backported before we branched for 4.1, but it didn't make it for some reason.  Now, it is blocking https://github.com/openshift/origin-aggregated-logging/pull/1673 and other 4.1 backports.  So, even though there is no bz associated with this PR, I would like to get it merged anyway to unblock other merges.  Alternatives are:
* combine this PR with the https://github.com/openshift/origin-aggregated-logging/pull/1673 backport
* use the BZ associated with https://github.com/openshift/origin-aggregated-logging/pull/1673 for this PR

**Comment by ewolinetz** [comment]
lgtm, @bparees what would be the ideal process for getting this into 4.1? I'm guessing we would need a bz linked, right?

**Comment by bparees** [comment]
> lgtm, @bparees what would be the ideal process for getting this into 4.1? I'm guessing we would need a bz linked, right?

yes it needs a BZ (including referencing the BZ in the PR title).  You can use an existing BZ that this is necessary for.  The patch manager is going to want to see that this code has already gone into 4.2 and that the 4.2 targeted BZ has been verified by QE.

**Comment by richm** [comment]
ok - changed title to be a valid 4.1 bz (even though this PR is only indirectly involved with the bz)
https://bugzilla.redhat.com/show_bug.cgi?id=1722898

**Comment by richm** [comment]
/test full-integ-aws
flake?

**Pull request merged**
