### PR TITLE
bug 1596099. Use IndexRequest instead of UpdateRequest

### PR DESCRIPTION
**Pull request by jcantrill**
This PR fixes https://bugzilla.redhat.com/show_bug.cgi?id=1596099 by pulling in a new version of the openshift-elasticsearch-plugin to use IndexRequest instead of UpdateRequest

### CODE REVIEW

**Comment by jcantrill** [comment]
/hold

Until release of 3.10

**Comment by jcantrill** [comment]
@ewolinetz No because it was determined to not be a 3.10 blocker bug so it has to go in a z stream.  Also, Im not quite sure why the tests were skipped?

**Comment by smarterclayton** [comment]
Jobs are fixed in https://github.com/openshift/release/pull/1027, might take a few minutes before /refresh will work for you.

**Pull request merged**
