### PR TITLE
Rebuild elasticsearch to bump the version jackson dependency

### PR DESCRIPTION
**Pull request by jcantrill**
### Description
This PR bumps elasticsearch to include a custom build which includes a new jackson library

/hold
cc @ewolinetz

### CODE REVIEW

**Comment by ewolinetz** [comment]
@jcantrill we also need to do this with the opendistro plugin, right?
otherwise huge :+1:

**Comment by jcantrill** [comment]
> @jcantrill we also need to do this with the opendistro plugin, right?
> otherwise huge

If it pulls in the jackson lib, then yes.  If not, I don't think so since the es version is still `6.8.1`

**Comment by vimalk78** [comment]
We need this change in downstream Dockerfile also?

**Comment by ewolinetz** [comment]
@jcantrill it does, it has an older 2.9.x version

**Comment by jcantrill** [comment]
> We need this change in downstream Dockerfile also?

we do but this is really only to sanity check that the bump in the library does not break functionality

**Comment by jcantrill** [comment]
> @jcantrill it does, it has an older 2.9.x version

so confused... it doesnt appear to have jackson, the version we built anyway:
```
$ unzip -l opendistro_security-0.10.1.0-redhat-00001.zip | grep jack
```

**Comment by jcantrill** [comment]
need more investigation of why its missing:
```
$ unzip -l opendistro_security-0.10.0.0.zip | grep jack
     4714  08-08-2019 01:25   jjwt-jackson-0.10.5.jar
  1247577  08-08-2019 01:25   jackson-databind-2.8.11.2.jar
    55784  08-08-2019 01:25   jackson-annotations-2.8.0.jar
[jeff.cantrill@decker tmp]$ unzip -l opendistro_security-0.10. | grep jack
opendistro_security-0.10.0.0.zip               opendistro_security-0.10.1.0-redhat-00001.zip  
[jeff.cantrill@decker tmp]$ unzip -l opendistro_security-0.10.1.0-redhat-00001.zip | grep jack

```

**Comment by jcantrill** [comment]
@ewolinetz @periklis looks like all the tests passed on this change to bump Jackson. Please verify Kibana is able to reindex as needed and manual sanity check nothing is broken. 

Cc @vimalk78

**Comment by ewolinetz** [comment]
I see the following when restarting kibana after creating two users previously which looks to be the same as current:
```
{"type":"log","@timestamp":"2021-03-30T18:38:29Z","tags":["status","plugin:opendistro_security@6.8.1","info"],"pid":116,"state":"yellow","message":"Status changed from yellow to yellow - Setting up index template.","prevState":"yellow","prevMsg":"Routes for Security configuration GUI registered."}
{"type":"log","@timestamp":"2021-03-30T18:38:29Z","tags":["listening","info"],"pid":116,"message":"Server running at http://localhost:5601"}
{"type":"log","@timestamp":"2021-03-30T18:38:29Z","tags":["info","migrations"],"pid":116,"message":"Creating index .kibana_-1145792675_testuser_2."}
{"type":"log","@timestamp":"2021-03-30T18:38:29Z","tags":["info","migrations"],"pid":116,"message":"Reindexing .kibana_-1145792675_testuser to .kibana_-1145792675_testuser_1"}
{"type":"log","@timestamp":"2021-03-30T18:38:31Z","tags":["info","migrations"],"pid":116,"message":"Migrating .kibana_-1145792675_testuser_1 saved objects to .kibana_-1145792675_testuser_2"}
{"type":"log","@timestamp":"2021-03-30T18:38:31Z","tags":["info","migrations"],"pid":116,"message":"Pointing alias .kibana_-1145792675_testuser to .kibana_-1145792675_testuser_2."}
{"type":"log","@timestamp":"2021-03-30T18:38:32Z","tags":["info","migrations"],"pid":116,"message":"Finished in 2892ms."}
{"type":"log","@timestamp":"2021-03-30T18:38:32Z","tags":["info","migrations"],"pid":116,"message":"Creating index .kibana_-377444158_kubeadmin_2."}
{"type":"log","@timestamp":"2021-03-30T18:38:32Z","tags":["info","migrations"],"pid":116,"message":"Reindexing .kibana_-377444158_kubeadmin to .kibana_-377444158_kubeadmin_1"}
{"type":"log","@timestamp":"2021-03-30T18:38:33Z","tags":["info","migrations"],"pid":116,"message":"Migrating .kibana_-377444158_kubeadmin_1 saved objects to .kibana_-377444158_kubeadmin_2"}
{"type":"log","@timestamp":"2021-03-30T18:38:33Z","tags":["info","migrations"],"pid":116,"message":"Pointing alias .kibana_-377444158_kubeadmin to .kibana_-377444158_kubeadmin_2."}
{"type":"log","@timestamp":"2021-03-30T18:38:34Z","tags":["info","migrations"],"pid":116,"message":"Finished in 1915ms."}
{"type":"log","@timestamp":"2021-03-30T18:38:34Z","tags":["status","plugin:opendistro_security@6.8.1","info"],"pid":116,"state":"green","message":"Status changed from yellow to green - Open Distro Security plugin version 6.8.1 initialised.","prevState":"yellow","prevMsg":"Setting up index template."}
```

no errors regarding incorrect HTTP methods during reindexing.

**Pull request merged**
