### PR TITLE
figure out the name of the SG index

### PR DESCRIPTION
**Pull request by jcantrill**
I believe this is the change need to 'unblock' https://github.com/openshift/openshift-ansible/pull/4364

### CODE REVIEW

**Comment by jcantrill** [comment]
[test]

**Comment by jcantrill** [comment]
[test] flake?

**Comment by richm** [comment]
The error output doesn't make sense to me in that it says the failure is at origin-aggregated-logging/logging.sh line 448

There is no such file.

hack/testing/logging.sh does not have 448 lines

however, based on the output, the failure is here: https://github.com/jcantrill/origin-aggregated-logging/blob/d03394ae460e5744cfc70684f0d5c832fa47114c/hack/testing/logging.sh#L233
```
espod=`get_running_pod es`
sg_index=$(oc exec $espod -- python -c "import yaml; print yaml.load(open('/usr/share/elasticsearch/config/elasticsearch.yml'))['searchguard']['config_index_name']" | xargs -i sh -c "echo {}")
wait_for_es_ready $espod 30 $sg_index/rolesmapping/0
```
That is, the sg index never becomes ready.  And, we don't know why, because none of the pod logs are in the S3 artifacts :-( @stevekuznetsov What's happening with the S3 artifacts?  How can we get the pods logs in there?

**Comment by stevekuznetsov** [comment]
Looking into pod logs now

**Comment by jcantrill** [comment]
@richm @stevekuznetsov maybe this is related to the other PR you have were you said you saw issues...i think its still open in this repo

**Comment by stevekuznetsov** [comment]
Y'all are still using `/tmp/origin-aggregated-logging` instead of the typical TMPDIR stuff we have in Origin so we're just grabbing the wrong dir for artifacts later. Let me add that to the job def.

**Comment by stevekuznetsov** [comment]
Fixed in https://github.com/openshift/aos-cd-jobs/pull/348 -- rerun of tests should yield pod logs

**Comment by jcantrill** [comment]
[test]

**Comment by stevekuznetsov** [comment]
We can see pod logs now for [the failed job](https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_aggregated_logging_prior/60) like for [`elasticsearch_logging-es-data-master-fjpzvsfn`](https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_aggregated_logging_prior/60/s3/download/origin-aggregated-logging/logs/containers/k8s_elasticsearch_logging-es-data-master-fjpzvsfn-1-5z53h_logging_463b5100-5698-11e7-85da-0e778e0d595c_0.log) under the `origin-aggregated-logging/logs/containers/` directory in S3

**Comment by jcantrill** [comment]
[merge][severity:blocker]

**Pull request merged**
