### PR TITLE
port es-copy to the new hack/lib tests

### PR DESCRIPTION
**Pull request by richm**
@stevekuznetsov @jcantrill @nhosoi PTAL
[test]

### CODE REVIEW

**Comment by nhosoi** [comment]
When the CI-test is launched with mux enabled and the fluentd is started with some MUX_CLIENT_MODE, you may want to skip this test case since the mux client fluentd just sends one set of the log messages to the mux ignoring the copy output config.

Note: It is going to be replaced with this new script :), but in test-es-copy.sh in #556/#559 which is not merged yet, I skipped the test like this...
```
+if [ "$USE_MUX_CLIENT" = "true" ] ; then
+    echo "Skipping -- This test is exclusive to USE_MUX_CLIENT != true."
+    exit 0
+fi
```

**Comment by richm** [comment]
[test]

**Comment by jcantrill** [comment]
[(8) Update tests to use origin/hack libraries[logging][epic-ci][epic-ois-td]](https://trello.com/c/UBias2xZ/525-8-update-tests-to-use-origin-hack-librariesloggingepic-ciepic-ois-td)

**Comment by jcantrill** [comment]
[(8) Update tests to use origin/hack libraries[logging][epic-ci][epic-ois-td]](https://trello.com/c/UBias2xZ/525-8-update-tests-to-use-origin-hack-librariesloggingepic-ciepic-ois-td)

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
Marked as do not merge until I can figure out what's going on with the fluentd performance.

**Comment by richm** [comment]
ok - please review
[test]

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
[merge]

**Comment by richm** [comment]
[merge]

**Pull request merged**
