### PR TITLE
Update fluentd to latest v0.14.18

### PR DESCRIPTION
**Pull request by amitkumarj441**
Signed-off-by : Amit Kumar Jaiswal <amitkumarj441@gmail.com>

### CODE REVIEW

**Comment by richm** [comment]
Unfortunately we can't yet move to fluentd 0.14.  Hopefully in the next major (3.7) release.

**Comment by amitkumarj441** [comment]
@richm Sure. Thanks for letting me know about this info.

**Comment by portante** [comment]
Also, according to http://www.fluentd.org/download, 0.12 is considered "stable" and ready for production use.  When 0.14 moves to that, we should consider it then.

**Comment by cosmo0920** [comment]
Now, Fluentd v1 , which is just bumped up version from v0.14, became stable release and v0.12 became old stable.

**Comment by richm** [comment]
maybe when rhel8/centos8 is available we can switch - but for now, we're stuck on ruby 2.0 :-(

**Pull request closed without merging**
