### PR TITLE
update to latest fluentd + dependencies

### PR DESCRIPTION
**Pull request by richm**

### CODE REVIEW

**Comment by richm** [comment]
see rh-manifest.txt https://github.com/openshift/origin-aggregated-logging/pull/1764/files#diff-25f6c72d1584664d80283638f4076a3b for the short list of changes

**Comment by richm** [comment]
please review

**Comment by ewolinetz** [comment]
EO build issue? `cp: cannot stat '/tmp/artifacts/eo/manifests/4.2': No such file or directory`

**Comment by richm** [comment]
> EO build issue? `cp: cannot stat '/tmp/artifacts/eo/manifests/4.2': No such file or directory`

https://github.com/openshift/origin-aggregated-logging/pull/1765

**Comment by richm** [comment]
/hold
until clo https://github.com/openshift/cluster-logging-operator/pull/245 is merged and built, everything is broken - so no sense rosiebot spamming us

**Pull request merged**
