### PR TITLE
Bumping up default time and changing variable naming for ENV exposure

### PR DESCRIPTION
**Pull request by ewolinetz**
Will also need to make update in openshift-ansible for the readiness probe timeout and expose this env var in the ES DC

### CODE REVIEW

**Comment by richm** [comment]
I think we need to merge a change to the DC at the same time: https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_logging_elasticsearch/templates/es.j2#L103
```
            timeoutSeconds: 4
            periodSeconds: 5
```
I think the way it works is that the timeoutSeconds is the same as the timeout inside the probe script, and periodSeconds must be greater than that.  @lukas-vlcek please comment

**Comment by ewolinetz** [comment]
@richm https://github.com/openshift/openshift-ansible/pull/4351

**Comment by ewolinetz** [comment]
@richm @lukas-vlcek bump on this

**Comment by ewolinetz** [comment]
[merge]

**Comment by ewolinetz** [comment]
i'll also make this change for the enterprise image(s) that apply

**Comment by stevekuznetsov** [comment]
[test_installer]

**Comment by ewolinetz** [comment]
re[merge]

**Pull request merged**
