### PR TITLE
disable curator test

### PR DESCRIPTION
**Pull request by jcantrill**
Disabled curator test for time being since its blocking all other PRs

### CODE REVIEW

**Comment by jcantrill** [comment]
One test is blocking at least these:

* https://github.com/openshift/origin-aggregated-logging/pull/1111
* https://github.com/openshift/openshift-ansible/pull/8126

**Comment by richm** [comment]
ok - but note that this won't fix the es5.x branch tests - the curator failure is in ansible there, installing the cronjob

**Comment by ewolinetz** [comment]
Can we revert this once https://github.com/openshift/openshift-ansible/pull/8139 merges?

**Comment by jcantrill** [comment]
@ewolinetz yes

**Comment by ewolinetz** [comment]
https://github.com/openshift/openshift-ansible/pull/8139 has been merged in and i'll work to get the 3.9 cherrypick merged in

**Pull request merged**
