### PR TITLE
Bug 1718705 - [RFE] Add feature in fluentd to send logs over UDP to a…

### PR DESCRIPTION
**Pull request by nhosoi**
…n external syslog server.

Introducing REMOTE_SYSLOG_TYPE environment variable to switch between syslog_buffered (TCP)
and syslog (UDP).

### CODE REVIEW

**Comment by nhosoi** [comment]
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1718705

**Comment by richm** [comment]
needs https://github.com/openshift/origin-aggregated-logging/pull/1661

**Pull request merged**
