### PR TITLE
Updating version of kibana installed to 4.1.2 and updating docs aroun…

### PR DESCRIPTION
**Pull request by ewolinetz**
…d scc to use for ES when using a hostmount

### CODE REVIEW

**Comment by ewolinetz** [comment]
@jcantrill @sosiouxme PTAL

**Comment by jcantrill** [comment]
LGTM

**Comment by sosiouxme** [comment]
Looks great. Side note, it's become clear the official docs for dealing with ES volumes are inadequate. A discussion of how multiple instances attach separate volumes and the tradeoffs of hostmount vs NAS is in order. Even our own ops guys got quite the wrong impression from what we have now. It is somewhere on my list of priorities to create a PR for this... but feel free to preempt me :)

**Comment by ewolinetz** [comment]
@sosiouxme created #65 to track the need to improve our ES volume documentation

**Pull request merged**
