### PR TITLE
updated for viaq version 0.0.10

### PR DESCRIPTION
**Pull request by richm**
updated for viaq version 0.0.10
@jcantrill ptal
[test]

### CODE REVIEW

**Comment by richm** [comment]
ok to merge?

**Comment by jcantrill** [comment]
@richm Its ok to merge but I don't know if we are in 'special' status now that we are past devcut

**Comment by richm** [comment]
@jcantrill this is to fix https://bugzilla.redhat.com/show_bug.cgi?id=1479645

**Comment by richm** [comment]
[merge]

**Pull request merged**
