### PR TITLE
Prepare for RHEL 8

### PR DESCRIPTION
**Pull request by yselkowitz**

### CODE REVIEW

**Comment by jcantrill** [comment]
I generally approve of this change but not certain where and when this can be consumed or if we have infra in place to build the changes.

**Comment by yselkowitz** [comment]
We are handling the migration of OKD/OCP to RHEL 8 content centrally for the entire product.  In order to ensure a smooth transition, in those cases where incompatible changes are required in a Dockerfile, we are creating new Dockerfile.rhel8 files and pointing the post-transition build infrastructure to use those files, e.g. https://github.com/openshift/ocp-build-data/commit/9c0a702f28969c271d8dde7bcc1b1d38ab196600 .  Therefore, this PR has to land before we can make the switch.  (After the transition is complete, we can arrange for merging changes back into plain Dockerfiles if you so wish.)

**Comment by jcantrill** [comment]
/lgtm
/hold cancel

cc @vimalk78 we'll have to figure out what this means for our future cpaas work

**Comment by yselkowitz** [comment]
Hmm three hours later and @jcantrill's /lgtm doesn't seem to be having any affect?

**Comment by sdodson** [comment]
/lgtm
based on https://github.com/openshift/origin-aggregated-logging/pull/1947#issuecomment-665015134

**Comment by crawford** [comment]
/hold cancel
based on https://github.com/openshift/origin-aggregated-logging/pull/1947#issuecomment-665015134

**Pull request merged**
