### PR TITLE
Conform to image guidelines

### PR DESCRIPTION
**Pull request by bbguimaraes**
https://trello.com/c/2kZC1Hts/204-2-audit-the-logging-images-and-impl-image-guidelines-logging-epic-ois-td

### CODE REVIEW

**Comment by bbguimaraes** [comment]
@ewolinetz, @richm: PTAL

Also, is `curator/run.sh` still necessary or could we remove it and update the
Dockerfile's `CMD`?

**Comment by richm** [comment]
@bbguimaraes LGTM - and yes, you can get rid of curator/run.sh - there is no reason for it

**Comment by ewolinetz** [comment]
LGTM +1 to removing `curator/run.sh` and updating the Dockerfile instead

**Comment by bbguimaraes** [comment]
Updated.

**Comment by ewolinetz** [comment]
[test]

**Comment by ewolinetz** [comment]
test failed when kicking off a build... and then got stuck dumping logs

**Comment by ewolinetz** [comment]
[test]

**Comment by ewolinetz** [comment]
looks like we're having build issues currently on the ami

**Comment by ewolinetz** [comment]
[test]

**Comment by jcantrill** [comment]
@bbguimaraes  LGTM, please squash and push updates.

**Comment by bbguimaraes** [comment]
Squashed and updated.

**Comment by ewolinetz** [comment]
silly etcd [merge]

**Pull request merged**
