### PR TITLE
Bug 1519213 - NoMethodError if remote_syslog enabled remote_syslog_ta…

### PR DESCRIPTION
**Pull request by nhosoi**
…g_key

fluent-plugin-remote-syslog: replacing tag_key with @tag_key
                             adding rescue around record[@tag_key]
Note: out_syslog.rb and out_syslog_buffered.rb are copied from
      https://github.com/docebo/fluent-plugin-remote-syslog and
      locally modified.  Once the changes made on the files are
      accepted by the plugin, out_syslog.rb and out_syslog_buffered.rb
      are to be removed and the changes on Dockerfile* are to be undone.

Adding test cases for tag_key to remote_syslog.sh

### CODE REVIEW

**Comment by nhosoi** [comment]
Yes, this is the PR.
https://github.com/docebo/fluent-plugin-remote-syslog/pull/12

**Comment by nhosoi** [comment]
Not sure what is wrong, but building failed in the upstream fluent-plugin-remote-syslog...

continuous-integration/travis-ci/pr — The Travis CI build could not complete due to an error
https://travis-ci.org/docebo/fluent-plugin-remote-syslog/builds/312670193?utm_source=github_status&utm_medium=notification

**Comment by richm** [comment]
why isn't this merging?

**Comment by portante** [comment]
Not sure this is legal to do.  We can't just copy source code into our repository like this if it is licensed.  I think that code is under the MIT license, at least in the gemspec it says [MIT](https://github.com/docebo/fluent-plugin-remote-syslog/blob/master/fluent-plugin-remote-syslog.gemspec#L13).

**Comment by richm** [comment]
I've asked legal for advice

**Comment by nhosoi** [comment]
@portante, @richm,
> I think that code is under the MIT license, at least in the gemspec it says MIT.
Good to hear that.
A community member submitted this pr on 2017-03-22, but there has been no activities in the pr since then.
https://github.com/docebo/fluent-plugin-remote-syslog/pull/9
So, even if the plugin does not have a LICENSE file nor a license section in each source file, the plugin is "protected"?

**Comment by portante** [comment]
@nhosoi, better safe than sorry and check with legal.

**Comment by nhosoi** [comment]
@porante, you are right.  I've opened this pr following the suggestion from the Legal team.
https://github.com/openshift/origin-aggregated-logging/pull/836

**Pull request merged**
