### PR TITLE
[release-3.10] Update eventrouter submodule to fix CentOS image.

### PR DESCRIPTION
**Pull request by patrickdillon**
Update submodule after golang package was removed from CentOS 7.6

### CODE REVIEW

**Comment by richm** [comment]
es didn't start - no indication why in logs - try again?  flake?
/retest

**Comment by richm** [comment]
I think 3.10 branch is still broken

**Comment by patrickdillon** [comment]
json-file and logging seem to fail when the Service Catalog does not install. When I look through the logs it looks like controller-manager is stuck in a crashloop because it cant mount the secret controllermanager-ssl. This seems to be a race condition. I'm going to try retesting over the weekend, when there is less demand on the CI node.

**Comment by richm** [comment]
@jcantrill please force merge this PR - then I'll remove the eventrouter hacks from https://github.com/openshift/origin-aggregated-logging/pull/1536 and it should pass too - then we should have working release-3.10 ci

**Comment by richm** [comment]
@jcantrill please force merge this PR - then I'll remove the eventrouter hacks from #1536 and it should pass too - then we should have working release-3.10 ci

**Pull request merged**
