### PR TITLE
update for ES2.x branch

### PR DESCRIPTION
**Pull request by jcantrill**

### CODE REVIEW

**Comment by danmcp** [comment]
[test]

**Comment by danmcp** [comment]
@jcantrill Thoughts on the failure?

**Comment by jcantrill** [comment]
@danmcp asked @ewolinetz  to comment.  He thinks it looks like an etcd failure so I believe the merge for the specific branch was successful.  Test flake that is unrelated??

**Comment by danmcp** [comment]
[test]

**Comment by danmcp** [comment]
@jcantrill You happy with what this job did?

**Comment by jcantrill** [comment]
@danmcp WFM.

**Comment by danmcp** [comment]
[merge]

**Pull request merged**
