### PR TITLE
bump plugin to 2.4.4.15 for 3.6

### PR DESCRIPTION
**Pull request by jcantrill**
3.6 Backport of #641

### CODE REVIEW

**Comment by jcantrill** [comment]
[test]

**Comment by richm** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_aggregated_logging_ansible/587/ failed - [test] flake

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
[test]

**Comment by richm** [comment]
[test] flake
```    "msg": "An unhandled exception occurred while running the lookup plugin 'openshift_master_facts_default_predicates'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Unknown short_version 3.7"
```

**Comment by richm** [comment]
[test] flake again

**Comment by richm** [comment]
ok - definitely not a flake - looks like CI is broken for release-3.6 branch :-(  @jcantrill can you take a look?
```
TASK [openshift_master_facts : Set Default scheduler predicates and priorities] ***
task path: /usr/share/ansible/openshift-ansible/roles/openshift_master_facts/tasks/main.yml:113
fatal: [localhost]: FAILED! => {
    "failed": true, 
    "generated_timestamp": "2017-09-25 12:33:26.134574", 
    "msg": "An unhandled exception occurred while running the lookup plugin 'openshift_master_facts_default_predicates'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Unknown short_version 3.7"
}
```

**Comment by richm** [comment]
saw a similar flake earlier today that was cleared up by apparently a later ansible , so re[test]

**Pull request merged**
