### PR TITLE
origin fix for bug 1369646

### PR DESCRIPTION
**Pull request by sosiouxme**
Make the upgrade set the correct secret volume on the logging-kibana-ops
DC; in earlier versions, it got a separate-but-equal secret, but in the
present versions both kibana DCs should use the same
logging-kibana-proxy secret.

### CODE REVIEW

**Comment by sosiouxme** [comment]
@ewolinetz FYI also I wasn't sure about testing for this in the upgrade... would have to set the kibana-proxy DC volume back to the earlier secret, and actually copy that secret, and then validate that the upgrade puts it back how it's supposed to be... what do you think?

**Comment by ewolinetz** [comment]
@sosiouxme yeah, i think we take that for granted. 
I think it'd be kind of tricky to put it back in a bad state unless we just use _any_ cert.. not necessarily the one it had before. Then we could verify if kibana-ops and kibana have the same certificate?

**Comment by sosiouxme** [comment]
[merge] now, add tests later

**Comment by ewolinetz** [comment]
[merge]

**Comment by sosiouxme** [comment]
builds will fail until https://github.com/openshift/origin-aggregated-logging/pull/217 goes in

**Comment by sosiouxme** [comment]
alright now [merge]

**Comment by ewolinetz** [comment]
i dont think #217 went in yet...

**Pull request merged**
