### PR TITLE
Es5 multitenant

### PR DESCRIPTION
**Pull request by jcantrill**
This PR adds changes to support the openshift-elasticsearch-plugin to ES 5.5

### CODE REVIEW

**Comment by jcantrill** [comment]
[(5) build/port openshift-elasticsearch-plugin to 5.x [logging][epic-ois-es5]](https://trello.com/c/sWMbQwn8/542-5-build-port-openshift-elasticsearch-plugin-to-5x-loggingepic-ois-es5)

**Comment by richm** [comment]
/retest
thin pool flake

**Comment by richm** [comment]
needs an es5.x branch in openshift-ansible?
```
+ cd /data/src/github.com/openshift/openshift-ansible
+ git checkout es5.x
error: pathspec 'es5.x' did not match any file(s) known to git.
++ export status=FAILURE
```

**Comment by jcantrill** [comment]
Probably, but I wasnt even expecting CI to past; I hadnt gotten that far yet in fixing everything

**Comment by jcantrill** [comment]
closing in favor of #892

**Pull request closed without merging**
