### PR TITLE
remove ES_COPY feature

### PR DESCRIPTION
**Pull request by jcantrill**
This PR removes the ES_COPY feature that has been deprecated since 3.3

### CODE REVIEW

**Comment by jcantrill** [comment]
[test]

**Comment by jcantrill** [comment]
companion pr https://github.com/openshift/origin-aggregated-logging/pull/674

**Comment by jcantrill** [comment]
[(2) Remove deprecated ES_COPY method of forwarding logs to external ES [epic-td]](https://trello.com/c/hk39Z7q0/591-2-remove-deprecated-escopy-method-of-forwarding-logs-to-external-es-epic-td)

**Comment by nhosoi** [comment]
Do we also need to remove this file es-ops-copy-config.conf?

And remove these includes, too?
openshift/output-applications.conf:   @include ../dynamic/es-copy-config.conf
openshift/output-operations.conf:  @include ../dynamic/es-ops-copy-config.conf

**Comment by richm** [comment]
Need to remove `hack/testing/test-es-copy.sh`

You'll need to remove es-ops-copy-config.conf as well.  Note that there still may be an `@include es-copy-config.conf` in the fluent.conf, so perhaps just making these files 0 length if the `@include` for non-existent file causes an error.

I'm not sure what the test is testing - it is still running the es-copy test: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_aggregated_logging_ansible/583/console
```
[INFO] Logging test suite test-es-copy started at Thu Sep 21 13:12:22 EDT 2017
[INFO] Starting es-copy test at Thu Sep 21 13:12:23 EDT 2017
Running test/es-copy.sh:91: executing 'oc get pods -l component=fluentd' expecting any result and text '^logging-fluentd-.* Running '; re-trying every 0.2s until completion or 60.000s...
...
[INFO] Logging test suite test-es-copy succeeded at Thu Sep 21 13:13:59 EDT 2017
```

**Comment by richm** [comment]
need to remove `fluentd/configs.d/openshift/es-ops-copy-config.conf` too.
Otherwise, looks good

**Comment by richm** [comment]
try with newly updated CI [test]

**Comment by richm** [comment]
[merge]

**Pull request merged**
