### PR TITLE
disable CVO and OLM for testing

### PR DESCRIPTION
**Pull request by richm**
For testing, we have to disable CVO, then OLM, then we can disable/enable CLO and EO as needed.

### CODE REVIEW

**Comment by richm** [comment]
I don't know if anyone is around - please review and `/lgtm` so we can unblock CI

**Comment by richm** [comment]
and - if anyone knows how to disable OLM, please let me know - https://github.com/openshift/origin-aggregated-logging/blob/master/hack/test-logging.sh#L78 doesn't work now, something restarts OLM - @shawn-hurley

**Comment by jcantrill** [comment]
> and - if anyone knows how to disable OLM, please let me know - https://github.com/openshift/origin-aggregated-logging/blob/master/hack/test-logging.sh#L78 doesn't work now, something restarts OLM - @shawn-hurley

To follow up on my slack message:  Disabling the cluster-version-operator will disable changes to OLM

**Comment by richm** [comment]
please review

**Pull request merged**
