### PR TITLE
fix operator deployment to deploy static resources

### PR DESCRIPTION
**Pull request by jcantrill**
Deploy static resources that OLM will not

cc @periklis @vimalk78

### CODE REVIEW

**Comment by jcantrill** [comment]
@periklis i think we will need to backport a similar change to 4.4 since i think your update is moving there.. correct?

**Comment by periklis** [comment]
@jcantrill Yes we need to cherry-pick this on for `release-4.4`

**Comment by periklis** [comment]
This needs to be amended after merging openshift/cluster-logging-operator/pull/389 because the static roles for `openshift-config-managed` will be droped

**Pull request closed without merging**
