### PR TITLE
Bug 1500086 - no authentication required to access elasticsearch

### PR DESCRIPTION
**Pull request by richm**
https://bugzilla.redhat.com/show_bug.cgi?id=1500086
Test access control in many different ways, both against
Elasticsearch directly and via Kibana.
- proper token and username has access to correct projects
- proper token and username is denied access to disallowed projects
- admin has access to all indices
- username with no token is an error
- username with bogus token is an error
- username with wrong token is an error
- no username and no token is an error
- admin with no token is an error
- admin with bogus token is an error
- client cert auth with kibana cert issued by unknown CA is an error
/test

### CODE REVIEW

**Comment by richm** [comment]
/retest
curator flake

**Comment by portante** [comment]
So there are no changes to the code, just test environment.  Perhaps worth stating that explicitly, since the subject refers to a BZ that one might consider is fixed by this change?

**Comment by richm** [comment]
This PR is only to add a test - it does not fix the BZ referred to, but it does add a test to ensure the behavior fixed by the BZ is working.

**Comment by richm** [comment]
@ewolinetz We will need to make sure that the openshift-elasticsearch-plugin work you are doing doesn't cause a regression - I never could get the SAR request to work properly when I was using the new es api java code.

**Comment by ewolinetz** [comment]
@richm the work I'm doing is just to reenable the integration tests, no actual code change

**Comment by richm** [comment]
> @richm the work I'm doing is just to reenable the integration tests, no actual code change

Are you upgrading the `kubernetes-client.version` ?  If so, be aware that that may change the way the api behaves.  That's what I ran into - version 3 SAR request did not behave the same way as 1.3.99.

**Comment by richm** [comment]
can I get a lgtm?

**Comment by ewolinetz** [comment]
@richm ack, i did upgrade that... is there an integration test I can write to verify it?

**Comment by richm** [comment]
> @richm ack, i did upgrade that... is there an integration test I can write to verify it?

This PR will verify it - not sure if there is an openshift-elasticsearch-plugin integration test for doing token auth for a SAR request.

**Comment by richm** [comment]
can I get a lgtm?

**Pull request merged**
