### PR TITLE
bug 1679864. Allow cluster admins to retrieve indice list

### PR DESCRIPTION
**Pull request by jcantrill**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1679864

### CODE REVIEW

**Comment by jcantrill** [comment]
@richm overriding these tests as change will not affect the outcome

**Comment by richm** [comment]
I suppose - but it looks like we have another test correction:
```
+ oc create -n openshift-logging -f manifests/05-deployment.yaml
deployment.apps/elasticsearch-operator created
make[1]: Leaving directory `/go/src/github.com/openshift/elasticsearch-operator'
oc create -n openshift-logging -f hack/cr.yaml
clusterlogging.logging.openshift.io/example created
Now using project "openshift-logging" on server "https://api.ci-op-y5jrjp52-65162.origin-ci-int-aws.dev.rhcloud.com:6443".
ERROR: operator did not start pods after 300 seconds
NAME                       READY   UP-TO-DATE   AVAILABLE   AGE
cluster-logging-operator   1/1     1            1           8m16s
elasticsearch-operator     1/1     1            1           8m13s
kibana                     1/1     1            1           8m2s
NAME                                        READY   STATUS    RESTARTS   AGE
cluster-logging-operator-6bc7cd6f98-4jv7q   1/1     Running   0          8m17s
elasticsearch-operator-fc5d88675-jk5m9      1/1     Running   0          8m14s
fluentd-5rwnk                               1/1     Running   0          7m58s
fluentd-psvzd                               1/1     Running   0          7m58s
fluentd-qtkjq                               1/1     Running   0          7m58s
fluentd-s8wh9                               1/1     Running   0          7m58s
fluentd-sgjnl                               1/1     Running   0          7m58s
fluentd-w9zp7                               1/1     Running   0          7m58s
kibana-6967ff5b96-rnd2w                     2/2     Running   0          8m3s
```
that is - the clo did not create the elasticsearch deployment or the elasticsearch pod :-(

**Pull request merged**
