### PR TITLE
Upgrade to Common Data Model 0.0.14

### PR DESCRIPTION
**Pull request by lukas-vlcek**

### CODE REVIEW

**Comment by lukas-vlcek** [comment]
@richm Do you think failing IT tests is expected when index template changes?

**Comment by richm** [comment]
@lukas-vlcek CI tests are failing all over the place, in many PRs, and do not appear to be related to the fixes in the PRs.  Once again, I find myself in the position of trying to debug CI . . .

**Comment by lukas-vlcek** [comment]
the json-file test hasn't finished yet but I can already see the following error in the log:

```
[INFO] now auth using admin + token
Running test/access_control.sh:263: executing 'test 0 -gt 1' expecting success...
FAILURE after 0.020s: test/access_control.sh:263: executing 'test 0 -gt 1' expecting success: the command returned the wrong error code:
```

This is relevant to the following code <https://github.com/openshift/origin-aggregated-logging/blob/06925e7159824df0c0c7fe63e6aeabb9aec2a166/test/access_control.sh#L259-L263>

I am not sure if this is relevant to index-pattern and index mappings changes.

**Comment by richm** [comment]
> I am not sure if this is relevant to index-pattern and index mappings changes.

It isn't related.
We are being plagued by CI problems.  This isn't the only one.
Any help debugging CI would be appreciated.
Until we fix CI, nothing is going to merge.

**Comment by richm** [comment]
another odd access_control problem - flake?
/test logging

**Comment by richm** [comment]
curator flake
/test logging

**Comment by richm** [comment]
curator flake
/test logging

**Comment by lukas-vlcek** [comment]
Thanks @richm the CI stability is insane.

**Pull request merged**
