### PR TITLE
Updating upgrade documentation for service account clarifications

### PR DESCRIPTION
**Pull request by ewolinetz**
To address https://bugzilla.redhat.com/show_bug.cgi?id=1336625

@sosiouxme PTAL

### CODE REVIEW

**Comment by sosiouxme** [comment]
LGTM although i want to remove all deployer-related business to the deployer readme :) although it's already huge...

**Comment by ewolinetz** [comment]
[merge]

**Comment by ewolinetz** [comment]
failing until #139 is resolved

**Comment by ewolinetz** [comment]
[test]

**Comment by ewolinetz** [comment]
[merge]

**Comment by ewolinetz** [comment]
[test]

**Comment by ewolinetz** [comment]
[merge]

**Pull request merged**
