### PR TITLE
Fix mux test not to create project.default

### PR DESCRIPTION
**Pull request by richm**
Fixed the mux test which was creating project.default
re-enabled the correct-index-names test

(cherry picked from commit adc0b3ab0f3dda3578a41247bb6da61322e5cdab)

### CODE REVIEW

**Comment by nhosoi** [comment]
/lgtm

I'm just curious, if these rules [1] are replaced with [2], it could eliminate project.default?  Or not?
```
[1]
-        rewriterule1 MESSAGE .+ project.testproj.external\n\
-        rewriterule2 message .+ project.testproj.external\n\
[2]
+        rewriterule1 MESSAGE !.+ project.testproj.external\n\
+        rewriterule2 MESSAGE .+ project.testproj.external\n\
```

**Comment by richm** [comment]
> I'm just curious, if these rules [1] are replaced with [2], it could eliminate project.default? Or not?

I don't think so.  The problem is with journald logs which have `CONTAINER_NAME` set with the `default` namespace.

**Comment by nhosoi** [comment]
@richm, thanks for the clarification.  You already have my /lgtm, anyway.

**Comment by ewolinetz** [comment]
:+1: thanks @richm

**Comment by richm** [comment]
can I get a /lgtm?

**Comment by richm** [comment]
/test logging
curator flake

**Pull request merged**
