### PR TITLE
Refactor gen log throttle

### PR DESCRIPTION
**Pull request by jcantrill**
blocked on #350

### CODE REVIEW

**Comment by jcantrill** [comment]
[merge]

**Comment by jcantrill** [comment]
[merge] ansible dependency is fixed.

**Comment by jcantrill** [comment]
[merge] test flake?

**Comment by richm** [comment]
@jcantrill The problem is that `YAML.load_file()` will return `false` if the file has no yaml in it.  `map` is not a valid method for the `false` class.  The default file `/etc/fluent/configs.d/user/throttle-config.yaml` contains only comments.
```
$ pwd
~/origin-aggregated-logging
$ irb
irb(main):001:0> require 'yaml'
=> true
irb(main):002:0> YAML.load_file("fluentd/configs.d/user/throttle-conf.yaml")
=> false
irb(main):003:0> YAML.load_file("fluentd/configs.d/user/throttle-conf.yaml").map
NoMethodError: undefined method `map' for false:FalseClass
Did you mean?  tap
	from (irb):3
	from /usr/bin/irb:11:in `<main>'
```
This is the error from https://ci.openshift.redhat.com/jenkins/job/test-origin-aggregated-logging/1230/s3/download/logs/containers/k8s_fluentd-elasticsearch.1fb423d7_logging-fluentd-cgslb_logging_ec2283af-1583-11e7-a65a-0ecf144b3860_828d9bc5.log

    generate_throttle_configs.rb:222:in `<main>': undefined method `map' for false:FalseClass (NoMethodError)

**Pull request merged**
