### PR TITLE
get-cluster-run-tests.sh - new script to build/deploy/run

### PR DESCRIPTION
**Pull request by richm**
This is the new version of get-machine-run-tests.sh.

It will build your logging images, and the operator images,
deploy a new cluster using openshift-install, push the images
to that cluster, deploy logging, and launch the logging CI
tests.

Assumes you have GOPATH set.

Assumes you have the following repos cloned from https://github.com/openshift/
under $GOPATH/src/github/openshift:

- origin-aggregated-logging
- elasticsearch-operator
- cluster-logging-operator
- installer

Optional but recommended, under same location:

- shared-secrets
- release

Use $HOME/.config/$bn to set environment variables.

WORKDIR - default is a tmp dir - set this if you want to keep your cluster
files in a known location so that you can easily destroy the cluster
after use e.g. you will need to manually do

/path/to/openshift/install/bin/openshift-install --dir $WORKDIR/installdir destroy cluster

after you are done.

BUILD_IMAGES - default is true - set to false if you want to skip building the
images e.g. if you have already built them - this step takes a long time

DEPLOY_CLUSTER - default is true - set to false if you already have a cluster

PUSH_IMAGES - default is true - set to false if you didn't BUILD_IMAGES or
otherwise will pull images from somewhere else

TEST_LOGGING - default is true - set to false if you do not want to deploy
logging and run the logging CI tests

OPENSHIFT_INSTALL_PULL_SECRET_PATH - no default - this is the absolute path
of the file containing the pull secrets used with the openshift-installer
to deploy the cluster.  If DEPLOY_CLUSTER=true, you must have set
OPENSHIFT_INSTALL_PULL_SECRET_PATH.  For example

OPENSHIFT_INSTALL_PULL_SECRET_PATH=$HOME/.pullsecret

where $HOME/.pullsecret contains something like

{"auths":{"cloud.openshift.com":{"auth":"asdjflaskdlfakjsdfljsdfl....

The file should be the file downloaded from https://cloud.openshift.com/clusters/install

OPENSHIFT_INSTALL_SSH_PUB_KEY_PATH - default $HOME/.ssh/id_rsa.pub - also for
DEPLOY_CLUSTER=true

See hack/build-images.sh and hack/deploy-openshift-cluster.sh for more environment
variables you might find useful.

### CODE REVIEW

**Comment by richm** [comment]
Depends on https://github.com/openshift/elasticsearch-operator/pull/119 and https://github.com/openshift/cluster-logging-operator/pull/153 for full functionality.

**Comment by nhosoi** [comment]
> This is the new version of get-machine-run-tests.sh.

Do we still use oct, activate, etc. from this tool set?  Or no more?
https://github.com/openshift/origin-ci-tool

**Comment by richm** [comment]
> > This is the new version of get-machine-run-tests.sh.
> 
> Do we still use oct, activate, etc. from this tool set? Or no more?
> https://github.com/openshift/origin-ci-tool

no - oct is gone

**Pull request merged**
