### PR TITLE
support jemalloc provided by fluentd; test repo

### PR DESCRIPTION
**Pull request by richm**
support the use of jemalloc provided in the fluentd package
support passing in a test repo to test builds
/test

### CODE REVIEW

**Comment by jcantrill** [comment]
@richm did i miss something in the PR.  I didnt see any ref to jemalloc in the commit?

**Comment by richm** [comment]
The downstream fluentd package bundles jemalloc and provides the jemalloc-config program in `/usr/libexec/fluentd/bin`

**Comment by richm** [comment]
this is primarily for downstream - can I get a lgtm?

**Comment by richm** [comment]
/test json-file
aws flake

**Pull request merged**
