### PR TITLE
deployer: refactor into functions

### PR DESCRIPTION
**Pull request by sosiouxme**
It's hard to see what's going on here with all the whitespace changes but essentially I wrapped everything in functions and did a little prettifying along the way. Particularly the nodeselector bits are improved.

### CODE REVIEW

**Comment by sosiouxme** [comment]
[test]

**Comment by sosiouxme** [comment]
flake... [test]

**Comment by sosiouxme** [comment]
[test]

**Comment by sosiouxme** [comment]
@ewolinetz @richm PTAL probably don't want this hanging around for too long if you're working on upgrade capability.

Tests passed before I squashed

**Comment by ewolinetz** [comment]
tests aside, LGTM thanks @sosiouxme , this should make the migration script much easier :+1:

**Comment by sosiouxme** [comment]
so [test] it... test it good.

**Comment by ewolinetz** [comment]
[test]

**Comment by richm** [comment]
[test]

**Comment by ewolinetz** [comment]
do we want to revert the two test pokes?

**Comment by sosiouxme** [comment]
Rebased and squashed.

**Comment by ewolinetz** [comment]
LGTM

**Pull request merged**
