### PR TITLE
bump kibana to version 4.6.4

### PR DESCRIPTION
**Pull request by richm**
@jcantrill @ewolinetz PTAL
[test]

### CODE REVIEW

**Comment by jcantrill** [comment]
Lgtm. why the bump?

**Comment by richm** [comment]
> Lgtm. why the bump?
Just part of the periodic "keep up with the latest stable version" to avoid security issues, tech debt, etc.

**Comment by ewolinetz** [comment]
:+1:

**Comment by richm** [comment]
[merge]

**Pull request merged**
